<?php
$owner = $this->owner;
$admin = $this->admin;
$project = $this->project;
$user = $this->user;
$architect = $this->architect;
$address = $this->address;
$specifier = $this->specifier;
$specifierAddress = $this->specifierAddress;
$location = $this->location;
$company = $this->company;
$status = $this->status;
$marketSegment = $this->marketSegment;
$addressList = $this->addressList;
$specifierList = $this->specifierList;
$generalContractor = $this->generalContractor;
$awardedContractor = $this->awardedContractor;
$projectID = $project['project_id'];
$this->headTitle('Edit Project: ' . $projectID . ' - ' . $project['project_name']);
echo $this->headTitle();
$projectCreateDate = $project['created_at'];
$projectDueDate = $project['due_date'];
$projectRequiredDate = $project['require_date'];
?>

<!-- Right panel -->


<!-- Main content wrapper -->
<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <h1 class="font-mono text-5xl font-semibold tracking-wide uppercase">Project</h1>
    <p class="text-muted-foreground">Editting project #<?= $this->escapeHtml($projectID) ?> - <?= $this->escapeHtml($project['project_name']) ?></p>

    <!-- Form -->
    <div class="flex flex-col gap-4 md:gap-6">
        <div class="fade-in-up" aria-labelledby="project-information">
            <form action="/project/<?= $this->escapeHtml(
                                        $projectID
                                    ) ?>/edit" method="post" class="form" id='project_content' data-save-btn="#form-btn-save-project" data-form="#projectForm" data-page="edit">
                <div class="widget-table bg-widget-background rounded-xl p-6">
                    <!--<div class="widget-button">
						<div class="widget-pin">
							<input type="checkbox" id="project-pin" name="project-pin">
							<label for="project-pin">Pin project</label>
						</div>
					</div>-->
                    <div class="widget-header">
                        <div class="widget-title">
                            <p class="leading-none font-semibold text-lg">Project Information</p>
                        </div>
                    </div>
                    <div class="line"></div>
                    <div class="widget-section">
                        <div class="formRow">
                            <input type="hidden" id='project_id' value='<?= $this->escapeHtml($projectID) ?>'>
                            <input type="hidden" id="user_session_id" name='user_session_id' value='<?= $user['id'] ?>'>
                            <input type="hidden" id='create_date' name='create_date'
                                value='<?= $this->escapeHtml($projectCreateDate?->format('Y-m-d') ?? '') ?>' />

                            <div class="grid gap-2 required-field">
                                <label for="project_name">Project Name</label>
                                <input type="text" id='project_name' class="validate[required]"
                                    placeholder="Project Name" name='project_name'
                                    value='<?= $this->escapeHtml($project['project_name']) ?>' />
                            </div>

                            <div class="grid gap-2 required-field">
                                <label for="project_address">Project Location</label>
                                <input type="text" name='project_address' id="project_address"
                                    class="validate[required]" value="<?= $this->escapeHtml($project['project_address']) ?>" />
                            </div>

                            <div class="grid gap-2">
                                <label for="location_id">Centura Location</label>
                                <select name="location_id" id="location_id">
                                    <?php foreach ($location as $l) { ?>
                                        <option value="<?= $this->escapeHtml($l['location_id']) ?>" <?php if (
                                                                                                        $l['location_id'] == $project['centura_location_id']
                                                                                                    ) {
                                                                                                        echo 'selected';
                                                                                                    } ?>>
                                            <?= $this->escapeHtml($l['branch_description']) ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2 required-field">
                                <label for="status">Project Stage</label>
                                <select name="status" id="status" class="validate[required]">
                                    <option value="">-- Select Status --</option>
                                    <?php foreach ($status as $s) { ?>
                                        <option value="<?= $this->escapeHtml($s['status_id']) ?>" <?php if ($s['status_id'] == $project['status_id']) {
                                                                                                        echo 'selected';
                                                                                                    } ?>>
                                            <?= $this->escapeHtml($s['status_desc']) ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2 required-field">
                                <label for='market_segment_id'>Project Segment</label>
                                <select name="market_segment_id" id='market_segment_id' class="validate[required]">
                                    <option value="">-- Choose Segment --</option>
                                    <?php foreach ($marketSegment as $s) { ?>
                                        <option value="<?= $this->escapeHtml($s['market_segment_id']) ?>" <?php if (
                                                                                                                $s['market_segment_id'] == $project['market_segment_id']
                                                                                                            ) {
                                                                                                                echo 'selected';
                                                                                                            } ?>>
                                            <?= $this->escapeHtml($s['market_segment_desc']) ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2 form-worksheet-owner">
                                <label for="owner_id">Worksheet Owner</label>
                                <input id="owner_id" name="owner_id" type="text" value="<?= $this->escapeHtml($project['owner_id']) ?>"
                                    readonly />
                            </div>

                            <div class="grid gap-2">
                                <label for="reed">REED ID</label>
                                <input type="text" name="reed" id="reed" value="<?= $this->escapeHtml($project['reed']) ?>" />
                            </div>

                            <div class="grid gap-2">
                                <label for="due_date">Tender Due Date</label>
                                <input id="due_date" type="text" name='due_date' class="flatpickr"
                                    value="<?= $this->escapeHtml($projectDueDate?->format('Y-m-d') ?? '') ?>" />
                            </div>

                            <div class="grid gap-2">
                                <label for='required_date'>Required Date</label>
                                <input id='required_date' type="text" name='required_date' class="flatpickr"
                                    value="<?= $this->escapeHtml($projectRequiredDate?->format('Y-m-d')) ?>" />
                            </div>

                            <?php if ($user['approve_id'] != null) { ?>
                                <div class="grid gap-2 form-worksheet-owner">
                                    <label for="shared_id">Share Worksheet</label>
                                    <input id="shared_id" name="shared_id" type="text" value="<?= $this->escapeHtml($project['shared_id']) ?>" />
                                </div>
                            <?php } else { ?>
                                <input type="hidden" id="shared_id" name="shared_id" value="<?= $this->escapeHtml($project['shared_id']) ?>" />
                            <?php } ?>

                            <div class="grid gap-2">
                                <label for="project_id_ext">Project ID</label>
                                <input id="project_id_ext" type="text" name='project_id_ext'
                                    value="<?= $this->escapeHtml($project['project_id_ext']) ?>" readonly />
                            </div>
                        </div>
                    </div>

                    <div class="line"></div>

                    <details id="contractor-details">
                        <summary>Contractor</summary>
                        <div class="widget-section">
                            <div class="formRow">
                                <div class="grid gap-2">
                                    <label for="general_contractor_name">General Contractor</label>
                                    <input type="text" id="general_contractor_name" name="general_contractor_name"
                                        placeholder="Add general contractor" value='<?php if (!empty($generalContractor)) {
                                                                                        echo $generalContractor['customer_name'] . ' - ' . $generalContractor['company_id'];
                                                                                    } ?>' />
                                    <input type="hidden" id="general_contractor_id" name="general_contractor_id"
                                        value="<?= $this->escapeHtml($project['general_contractor_id']) ?>" />
                                </div>

                                <div class="grid gap-2">
                                    <label for="awarded_contractor_name">Awarded Contractor</label>
                                    <input type="text" id="awarded_contractor_name" name="awarded_contractor_name"
                                        placeholder="Add awarded contractor" value='<?php if (!empty($awardedContractor)) {
                                                                                        echo $awardedContractor['customer_name'] . ' - ' . $awardedContractor['company_id'];
                                                                                    } ?>' />
                                    <input type="hidden" id='awarded_contractor_id' name='awarded_contractor_id'
                                        value="<?= $this->escapeHtml($project['awarded_contractor_id']) ?>">
                                </div>
                            </div>
                        </div>
                    </details>

                    <?php if ($owner) { ?>

                        <div class="line"></div>

                        <div class="widget-footer">
                            <div class="widget-footer-button">
                                <button disabled id="form-btn-save-project" type="submit" form="project_content" title="Save project information"
                                    class="button action save-project-button small">
                                    <span class="button-wrap text-[10px] font-bold">
                                        <span class="icon icon-save"></span>
                                        Save
                                    </span>
                                </button>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </form>
        </div>

        <div class="fade-in-up" aria-labelledby="architect-information">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <p class="leading-none font-semibold text-lg">Architect Information</p>
                    </div>
                </div>
                <div class="line"></div>
                <div class="widget-section">
                    <form action="/project/<?= $this->escapeHtml(
                                                $projectID
                                            ) ?>/editarchitect" method="post" class="form" id='project-architect-form' data-page="edit">
                        <details id="architect-details">
                            <summary>Architect & Specifier</summary>
                            <div class="widget-section">
                                <div class="widget-header">
                                    <div class="widget-title">
                                        <h4>Architect</h4>
                                    </div>
                                    <div class="widget-button">
                                        <button type="button" title="Add new architect"
                                            class="button action has-icon add-item-button small" id="add-architect-project-edit">
                                            <span class="button-wrap text-[10px] font-bold">
                                                <span class="icon icon-add"></span>
                                                New Architect
                                            </span>
                                        </button>
                                    </div>
                                </div>

                                <div class="formRow">
                                    <div class="grid gap-2">
                                        <label for="architect_name">Architect Name</label>
                                        <input type='text' name="architect_name" id='architect_name' class="tipN"
                                            original-title="Search by ID or Name" value='<?= $architect['architect_name'] ?? '' ?>' />
                                        <input type="hidden" name='architect_id' id='architect_id' value="<?= $this->escapeHtml(
                                                                                                                $architect['architect_id'] ?? ''
                                                                                                            ) ?>" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="architect_company_id">Company</label>
                                        <select id="architect_company_id" name="architect_company_id">
                                            <?php foreach ($company as $l) { ?>
                                                <option value="<?= $this->escapeHtml($l['company_id']) ?>" <?php if (
                                                                                                                $l['company_id'] ===
                                                                                                                ($architect['company_id'] ?? DEFAULT_COMPANY)
                                                                                                            ) {
                                                                                                                echo 'selected';
                                                                                                            } ?>>
                                                    <?= $this->escapeHtml($l['company_name']) ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="architect_rep_id">Architect Representative</label>
                                        <input type="text" id="architect_rep_id" name="architect_rep_id"
                                            value="<?= $this->escapeHtml($architect['architect_rep_id'] ?? '') ?>" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="architect_type_id">Architect Type</label>
                                        <select id="architect_type_id" name="architect_type_id">
                                            <option value="">-- Choose architect type --</option>
                                            <?php foreach ($this->architectType as $a) { ?>
                                                <option value="<?= $this->escapeHtml($a['architect_type_id']) ?>" <?= $this->escapeHtml(
                                                                                                                        $a['architect_type_id'] === ($architect['architect_type_id'] ?? '') ? 'selected' : ''
                                                                                                                    ) ?>><?= $this->escapeHtml($a['architect_type_desc']) ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="architect_class_id">Architect Class</label>
                                        <input type="text" id="architect_class_id" name="architect_class_id"
                                            value="<?= $this->escapeHtml($architect['class_id'] ?? '') ?>">
                                    </div>
                                </div>
                            </div>

                            <div class="line"></div>

                            <div class="widget-section">
                                <h4>Address</h4>
                                <div class="formRow">
                                    <input type="hidden" name='address_id' id='address_id' value="<?= $this->escapeHtml($address['address_id'] ?? '') ?>">
                                    <div class="grid gap-2 ">
                                        <label for="address_list">Address List</label>
                                        <select name='address_list' id='address_list'>
                                            <option value="new">+ Add New Address</option>
                                            <?php if (!empty($addressList)):
                                                foreach ($addressList as $a): ?>
                                                    <option value="<?= $this->escapeHtml($a['address_id']) ?>" <?= $a['address_id'] ===
                                                                                                                    $project['architect_address_id']
                                                                                                                    ? 'selected'
                                                                                                                    : '' ?>>
                                                        <?= $this->escapeHtml($a['name']) ?>
                                                    </option>
                                            <?php endforeach;
                                            endif; ?>
                                        </select>
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="address_name">Address Nickname</label>
                                        <input type='text' name="address_name" id='address_name'
                                            value="<?= $this->escapeHtml($address['name'] ?? '') ?>">
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_address1">Address 1</label>
                                        <input type='text' name="phys_address1" id='phys_address1'
                                            value="<?= $this->escapeHtml($address['phys_address1'] ?? '') ?>" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_address2">Address 2</label>
                                        <input type='text' name="phys_address2" id='phys_address2'
                                            value="<?= $this->escapeHtml($address['phys_address2'] ?? '') ?>" placeholder="Optional" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_city">City</label>
                                        <input type='text' name="phys_city" id='phys_city' value="<?= $this->escapeHtml(
                                                                                                        $address['phys_city'] ?? ''
                                                                                                    ) ?>" placeholder="Optional" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_state">Province</label>
                                        <input type='text' name="phys_state" id='phys_state'
                                            value="<?= $this->escapeHtml($address['phys_state'] ?? '') ?>" placeholder="Optional" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_postal_code">Postal Code</label>
                                        <input type='text' name="phys_postal_code" id='phys_postal_code'
                                            value="<?= $this->escapeHtml($address['phys_postal_code'] ?? '') ?>" placeholder="Optional" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="phys_country">Country</label>
                                        <input type='text' name="phys_country" id='phys_country'
                                            value="<?= $this->escapeHtml($address['phys_country'] ?? '') ?>" placeholder="Optional" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="central_phone_number">Company Phone Number</label>
                                        <input id='central_phone_number' name='central_phone_number' type="tel"
                                            class="maskPhone" value="<?= $this->escapeHtml($address['central_phone_number'] ?? '') ?>"
                                            placeholder="(123) 456-7890" />
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="email_address">Email</label>
                                        <input type="text" id='email_address' name='email_address'
                                            value="<?= $this->escapeHtml($address['email_address'] ?? '') ?>" placeholder="Optional">
                                    </div>

                                    <div class="grid gap-2">
                                        <label for="url">URL</label>
                                        <input type="url" id='url' name='url' value="<?= $this->escapeHtml(
                                                                                            $address['url'] ?? ''
                                                                                        ) ?>" placeholder="Optional">
                                    </div>
                                </div>
                            </div>

                            <div class="line"></div>

                            <div class="widget-section">
                                <h4>Specifier</h4>
                                <div class="formRow">
                                    <input type="hidden" id='specifier_id' name="specifier_id" value="<?= $this->escapeHtml(
                                                                                                            $project['specifier_id']
                                                                                                        ) ?>" />
                                    <input type="hidden" id='specifier_address_id' name="specifier_address_id"
                                        value="<?= $this->escapeHtml($specifierAddress['address_id'] ?? '') ?>" />
                                    <div class="grid gap-2 ">
                                        <label for="specifier_name">Specifier</label>
                                        <select name='specifier_name' id='specifier_name'>
                                            <option value="new">+ Add New Specifier</option>
                                            <?php if (!empty($specifierList)):
                                                foreach ($specifierList as $spec): ?>
                                                    <option value="<?= $this->escapeHtml($spec['specifier_id']) ?>" <?= $spec['specifier_id'] ===
                                                                                                                        $project['specifier_id']
                                                                                                                        ? 'selected'
                                                                                                                        : '' ?>>
                                                        <?= $spec['first_name'] . ' ' . $spec['last_name'] ?>
                                                    </option>
                                            <?php endforeach;
                                            endif; ?>
                                        </select>
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="specifier_first_name">First Name</label>
                                        <input type='text' id='specifier_first_name' name="specifier_first_name"
                                            class="tipN" value="<?= $this->escapeHtml($specifier['first_name'] ?? '') ?>" />
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="specifier_last_name">Last Name</label>
                                        <input type='text' id='specifier_last_name' name="specifier_last_name"
                                            placeholder="Optional" value="<?= $this->escapeHtml($specifier['last_name'] ?? '') ?>" />
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="specifier_job_title">Job Title</label>
                                        <input type='text' id='specifier_job_title' name="specifier_job_title"
                                            class="tipN" placeholder="Optional" value="<?= $this->escapeHtml($specifier['job_title'] ?? '') ?>" />
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="specifier_phone_number">Phone Number</label>
                                        <input type='tel' id='specifier_phone_number' name="specifier_phone_number"
                                            class="maskPhone" placeholder="(123) 456-7890" value="<?= $this->escapeHtml(
                                                                                                        $specifier['central_phone_number'] ?? ''
                                                                                                    ) ?>" />
                                    </div>

                                    <div class="grid gap-2 ">
                                        <label for="specifier_email">Email</label>
                                        <input type='text' id='specifier_email' name="specifier_email" class="tipN"
                                            placeholder="Optional" value="<?= $this->escapeHtml($specifierAddress['email_address'] ?? '') ?>" />
                                    </div>
                                </div>
                            </div>

                            <div class="line"></div>
                            <div class="widget-footer">
                                <div class="widget-footer-button">
                                    <button disabled id="form-btn-save-architect-project" type="submit" title="Save architect information"
                                        class="button action save-architect-button small">
                                        <span class="button-wrap text-[10px] font-bold">
                                            <span class="icon icon-save"></span>
                                            Save
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </details>
                    </form>
                </div>
            </div>
        </div>

        <div class="fade-in-up" aria-labelledby="quoted-items">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <p class="leading-none font-semibold text-lg">Items</p>
                    </div>
                    <div class="widget-button">
                        <?php if ($owner) { ?>
                            <button type="button" title="Add new item" class="button action has-icon add-item-button small"
                                id="widget-btn-add-item">
                                <span class="button-wrap text-[10px] font-bold">
                                    <span class="icon icon-add"></span>
                                    Add Item
                                </span>
                            </button>
                        <?php } ?>
                    </div>
                </div>

                <div class="line"></div>

                <div class="widget-section">
                    <table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap"
                        id="item-table" data-init="item">
                        <thead>
                            <tr>
                                <th>Item</th>
                                <th>Quantity</th>
                                <th>Unit Price</th>
                                <th>UOM</th>
                                <th>Stock Status</th>
                                <th>Total Price</th>
                                <th>Note</th>
                                <th>Options</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <div class="fade-in-up" aria-labelledby="project-log">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <p class="leading-none font-semibold text-lg">Project Log</p>
                    </div>
                    <div class="widget-button">
                        <?php if ($owner) { ?>
                            <button type="button" title="Add new log" class="button action has-icon add-log-button small"
                                id="widget-btn-add-note">
                                <span class="button-wrap text-[10px] font-bold">
                                    <span class="icon icon-add"></span>
                                    Add log
                                </span>
                            </button>
                        <?php } ?>
                    </div>
                </div>

                <div class="line"></div>

                <div class="widget-section">
                    <table cellpadding="0" cellspacing="0" width="100%" class="sTable display" id='note-table' data-init="projectNote">
                        <thead>
                            <tr>
                                <th>Date Add</th>
                                <th>Note</th>
                                <th>Next Action</th>
                                <th>Reminder Time</th>
                                <th>Author</th>
                                <th class="action">Options</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <div class="fade-in-up" aria-labelledby="quote-by-project">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <p class="leading-none font-semibold text-lg">Project Quotes</p>
                    </div>
                    <div class="widget-button">
                        <?php if ($owner and $admin) { ?>
                            <button type="button" title="Add new quote"
                                class="button action has-icon add-quote-button small" id="widget-btn-add-quote">
                                <span class="button-wrap text-[10px] font-bold">
                                    <span class="icon icon-add"></span>
                                    Make Quote
                                </span>
                            </button>
                        <?php } ?>
                    </div>
                </div>

                <div class="line"></div>

                <div class="widget-section">
                    <table width="100%" class="sTable display" id='project-quote-table' data-init="projectQuote">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Customer</th>
                                <th>Contact</th>
                                <th>Quote Date</th>
                                <th>Expire Date</th>
                                <th>Ship Required Date</th>
                                <th>Approve Status</th>
                                <th>P21 Order ID</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <?= $this->render('modal/item'); ?>

    <?= $this->render('modal/note'); ?>

    <?= $this->render('modal/customer'); ?>
</div>


<script type="text/javascript">
    window.isOwner = <?= $owner ? 'true' : 'false' ?>;
</script>
