<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="light">

<head>

    <?php echo $this->headTitle('P2Q')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Project to Quote')
    ?>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico.png">
    <link href="/css/index.css" rel="stylesheet" type="text/css">
    <?php //echo $this->headLink(); 
    ?>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- jMigrate CDN -->
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.js"></script>

    <!-- jQuery UI CDN -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>

    <!-- DataTables CDN -->
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.3/date-1.5.2/fc-5.0.0/r-3.0.1/rr-1.5.0/sl-2.0.0/datatables.min.css" rel="stylesheet">

    <script src="https://cdn.datatables.net/v/dt/dt-2.0.3/date-1.5.2/fc-5.0.0/r-3.0.1/rr-1.5.0/sl-2.0.0/datatables.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/luxon@3.4.4/build/global/luxon.min.js"></script>
    <!-- Hamburger menu -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<script type="text/javascript" src="/js/plugins/ui/jquery.ui.widget.js"></script>        
<script type="text/javascript" src="/js/plugins/ui/jquery.ui.mouse.js"></script>          
<script type="text/javascript" src="/js/plugins/ui/jquery.ui.resizable.js"></script>
-->

    <script type="text/javascript" src="/js/plugins/spinner/ui.spinner.js"></script>
    <script type="text/javascript" src="/js/plugins/spinner/jquery.mousewheel.js"></script>

    <script type="text/javascript" src="/js/plugins/charts/excanvas.min.js"></script>
    <script type="text/javascript" src="/js/plugins/charts/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/uniform.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.cleditor.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.tagsinput.min.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/autogrowtextarea.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.maskedinput.min.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.dualListBox.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.inputlimiter.min.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/chosen.jquery.min.js"></script>

    <script type="text/javascript" src="/js/plugins/wizard/jquery.form.js"></script>
    <script type="text/javascript" src="/js/plugins/wizard/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/js/plugins/wizard/jquery.form.wizard.js"></script>

    <script type="text/javascript" src="/js/plugins/uploader/plupload.js"></script>
    <script type="text/javascript" src="/js/plugins/uploader/plupload.html5.js"></script>
    <script type="text/javascript" src="/js/plugins/uploader/plupload.html4.js"></script>
    <script type="text/javascript" src="/js/plugins/uploader/jquery.plupload.queue.js"></script>

    <!--<script type="text/javascript" src="/js/plugins/tables/tablesort.min.js"></script>
<script type="text/javascript" src="/js/plugins/tables/resizable.min.js"></script>-->

    <script type="text/javascript" src="/js/plugins/ui/jquery.tipsy.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.collapsible.min.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.progress.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.colorpicker.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.jgrowl.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.breadcrumbs.js"></script>
    <script type="text/javascript" src="/js/plugins/ui/jquery.sourcerer.js"></script>

    <script type="text/javascript" src="/js/plugins/calendar.min.js"></script>
    <script type="text/javascript" src="/js/plugins/elfinder.min.js"></script>

    <script type="text/javascript" src="/js/custom.js"></script>

    <?php //echo $this->headScript(); 
    ?>
</head>

<body>
    <div id="root">
        <div class="page-wrapper category-html document-page">

            <!-- Header -->
            <?php echo $this->render('header.phtml') ?>

            <!-- Main -->
            <div class="main-wrapper" id="main-wrapper">
                <?php echo $this->layout()->content ?>
            </div>
            <!--
        <div class="loading" style="z-index:1003; top:0;left:0; width:100%; height:100%; background: url(/images/loaders/loader4.gif) #AAA center center no-repeat;position:absolute;display:none;opacity: .30;"> </div>
        -->
        </div>
    </div>
    <script type="text/javascript" src="/js/home.js"></script>
    <script type="text/javascript" src="/js/p2q.js"></script>
</body>

<!-- Footer -->
<footer class="footer">
    <?php echo $this->render('footer.phtml') ?>
</footer>

</html>