<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="light">

<head>

    <?php echo $this->headTitle('P2Q')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Project to Quote')
    ?>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico.png">
    <link href="/css/index.css" rel="stylesheet" type="text/css">
    <?php //echo $this->headLink(); 
    ?>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- jMigrate CDN -->
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.js"></script>

    <!-- jQuery UI CDN -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>

    <!-- DataTables CDN -->
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.3/date-1.5.2/fc-5.0.0/r-3.0.1/rr-1.5.0/sl-2.0.0/datatables.min.css" rel="stylesheet">

    <script src="https://cdn.datatables.net/v/dt/dt-2.0.3/date-1.5.2/fc-5.0.0/r-3.0.1/rr-1.5.0/sl-2.0.0/datatables.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/luxon@3.4.4/build/global/luxon.min.js"></script>
    <!-- Hamburger menu -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.maskedinput.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <?php //echo $this->headScript();
    ?>
    <script>
        (function() {
            const theme = localStorage.getItem("theme");
            if (theme === "dark" || theme === "light") {
                document.documentElement.className = theme;
            }
        })();
    </script>
</head>

<body>
    <div id="root">

        <div id="js-flash-container"></div>

        <?php if ($this->flashMessenger()->hasSuccessMessages()): ?>
            <div class="flash-message widget-table success">
                <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
                    <p><?= $this->escapeHtml($message) ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if ($this->flashMessenger()->hasErrorMessages()): ?>
            <div class="flash-message widget-table error">
                <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
                    <p><?= $this->escapeHtml($message) ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <div class="page-wrapper category-html document-page">

            <!-- Header -->
            <?php echo $this->render('header.phtml') ?>

            <!-- Main -->
            <div class="main-wrapper" id="main-wrapper">
                <?php echo $this->layout()->content ?>
            </div>

        </div>

        <div class="loading" style="display:none;">
            <div class="loading-overlay">
                <div class="spinner"></div>
                <p>Loading, please wait...</p>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/js/home.js"></script>
    <script type="text/javascript" src="/js/p2q.js"></script>
</body>

<!-- Footer -->
<footer class="footer">
    <?php echo $this->render('footer.phtml') ?>
</footer>

</html>