<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="light">

<head>

    <?php echo $this->headTitle('P2Q')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Project to Quote')
    ?>

    <meta charset="utf-8">

    <link rel="icon" type="image/x-icon" href="/images/favicon.ico.png">
    <link href="/css/index.css" rel="stylesheet">
    <link href="/build/main.css" rel="stylesheet">
    <link href="/build/Inter.var.css" rel="stylesheet">
    <?php //echo $this->headLink();
    ?>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- jMigrate CDN -->
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.js"></script>

    <!-- jQuery UI CDN -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <script type="text/javascript" scr="/node_modules/htmx-ext-head-support/dist/head-support.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/luxon@3.4.4/build/global/luxon.min.js"></script>
    <!-- Hamburger menu
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 -->
    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="/js/plugins/forms/jquery.maskedinput.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" />
    <?php //echo $this->headScript();
    ?>
    <script>
        (function() {
            const theme = localStorage.getItem("theme");
            if (theme === "dark" || theme === "light") {
                document.documentElement.className = theme;
            }
        })();
    </script>
</head>

<body x-data="loadingState" hx-ext="head-support">
    <div id="root">

        <div id="js-flash-container">
            <?php if ($this->flashMessenger()->hasSuccessMessages()): ?>
                <div class="flash-message widget-table success">
                    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
                        <p><?= $this->escapeHtml($message) ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if ($this->flashMessenger()->hasErrorMessages()): ?>
                <div class="flash-message widget-table error">
                    <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
                        <p><?= $this->escapeHtml($message) ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>

        <div class="page-wrapper category-html document-page">

            <!-- Header -->
            <?php echo $this->render('header.phtml') ?>

            <!-- Main -->
            <div class="main-wrapper" id="main-wrapper">
                <main id="content" class="main-content" hx-target="this" hx-swap="innerHTML">
                    <?php echo $this->layout()->content ?>
                </main>
            </div>

        </div>

        <div class="loading" x-show="loading" x-transition style="display: none;">
            <div class="loading-overlay">
                <div class="spinner"></div>
                <p>Loading, please wait...</p>
            </div>
        </div>

        <div id="search-overlay" class="search-overlay">
            <div class="search-box overlay-style" id="search-box">
                <input type="text" id="architect-search" placeholder="Search architect by ID or name..." />
                <ul class="autocomplete-list"></ul>
                <button id="close-search" title="Close">&#10005;</button>
            </div>
        </div>
    </div>
    <?php
    $manifest = json_decode(file_get_contents('public/build/.vite/manifest.json'), true);
    $appScript = $manifest['resources/js/app.js']['file'];
    $appCss = $manifest['resources/js/app.js']['css'][0] ?? null;
    ?>
    <?php if ($appCss): ?>
        <link rel="stylesheet" href="/build/<?= $appCss ?>">
    <?php endif; ?>
    <script type="module" src="/build/<?= $appScript ?>"></script>
</body>

<!-- Footer -->
<footer class="footer">
    <?php echo $this->render('footer.phtml') ?>
</footer>

</html>
