<?php
$session =  Zend_Registry::get('session');
$session_user = $session->user;
$project = $this->project;
$projectDueDate = $project['due_date'];

$quote = $this->quote;
$quoteID = $quote['quote_id'];
$quoteDate = $quote['quote_date'];
$quoteShipRequiredDate = $quote['ship_required_date'];
$quoteExpireDate = $quote['expire_date'];

$architect_rep = $this->architect_rep;
$contact = $this->contact;
$customer = $this->customer;
$contactList = $this->contactList;

$approved = 3;
$waitingApprove = 2;
$disapproved = 4;

$oeID = $this->oe_id['order_no'];

$maintainenceMode = 0;

if ($maintainenceMode != 0 and $session_user['sale_role'] != 'admin') {
?>
	<main id="content" class="main-content">
		<div class="main-page-content">
			<header class="main-page-content-header">
				<h1>This page is currently in maintainence mode. Please check back later. Sorry for the inconvenience!</h1>
			</header>
		</div>
	</main>
<?php } else { ?>


	<!-- Main content-->
	<main id="content" class="main-content">
		<div class="main-page-content">
			<header class="main-page-content-header">
				<div class="options-menu">
					<button class="quick-link options-button" id="options-button" type="button">
						<span class='icon icon-menu'></span>
						Options
					</button>

					<!-- Right panel -->
					<div class="sidebar-container" id="options-menu-items">
						<?php if ($quote['quote_status_id'] != $approved) { ?>
							<a href="/quote/approve/id/<?= $quoteID ?>" title="" class='button quick-link approve'>
								<span class='icon icon-approval'></span>
								Approve
							</a>

						<?php } ?>
						<?php if ($quote['quote_status_id'] == $approved) { ?>
							<a class='button quick-link' href="/mail/quote/id/<?= $quoteID ?>" title="mail">
								<span class='icon icon-mail'></span>
								Mail Quote
							</a>
							<a href="/quote/ready/id/<?= $quoteID ?>" title="" class='button quick-link ready_quote'>
								<span class='icon icon-undo'></span>
								Undo Approve
							</a>

						<?php } ?>
						<?php if ($quote['quote_status_id'] != $disapproved) { ?>

							<a href="/quote/disapprove/id/<?= $quoteID ?>" title="" class='button quick-link disapprove'>
								<span class='icon icon-cancel-circle'></span>
								Disapprove
							</a>

						<?php } ?>
						<a class="button quick-link" target="_blank" href="/quote/edit/id/<?= $quoteID ?>" title="Edit this quote">
							<span class='icon icon-external'></span>
							Go to Edit</a></li>
						<a class="button quick-link" target="_blank" href="/project/edit/id/<?= $project['project_id'] ?>" title="Go to project for this quote">
							<span class='icon icon-external'></span>
							Go to Project</a></li>

						<a class='button quick-link' href="<?= 'http://' . SITEURL . "/dompdf/print.php?url=" . 'http://' . SITEURL . "/quote/print/id/" . $quoteID . "?company=" . substr($quote['quote_id_ext'], 0, 3) . "&name=Centura_Quote_" . $quoteID . '.pdf' ?>" title="print">
							<span class='icon icon-pdf'></span>
							Print Quote
						</a>

						<?php if ($quote['quote_status_id'] != $approved) { ?>
							<a href="/quote/delete/id/<?= $quoteID ?>" title="" class='button quick-link delete_quote'>
								<span class='icon icon-trash'></span>
								Delete
							</a>

						<?php } ?>
					</div>
				</div>

				<h1>Quote Approval</h1>
			</header>

			<div class="widget-information">
				<div class="widget-table dashboard">
					<span class='svg icon icon-list'></span>
					<div class="project-information project-name">
						<h2><?= $project['project_name'] ?></h2>
						<p><?= ($project['project_address'] == 'N/A') ? '' : $project['project_address'] ?></p>
						</br>
						<p>by <b><?= $project['owner_id'] ?></b></p>
						<?php if (($project['shared_id']) != null) { ?>
							<p>shared with <b><?= $project['shared_id'] ?></b></p>
						<?php } ?>
					</div>
				</div>

				<div class="widget-table dashboard">
					<span class='svg icon icon-number'></span>
					<div class="project-information">
						<p>P21 Order ID</p>
						<h2><?php if ($oeID != "") {
								echo $oeID;
							} else {
								echo 'Unavailable';
							} ?></h2>
					</div>
				</div>

				<div class="widget-table dashboard">
					<span class='svg icon icon-money-1'></span>
					<div class="project-information">
						<p>Project status</p>
						<h2><?= $project['status_desc'] ?></h2>
					</div>
				</div>

				<div class="widget-table dashboard">
					<span class='svg icon icon-calender'></span>
					<div class="project-information">
						<p>Due date</p>
						<h2><?= $projectDueDate->format('Y-m-d') ?></h2>
					</div>
				</div>

				<?php
				switch ($quote['quote_status_id']) {
					case $approved: ?>
						<div class="widget-table dashboard quote-status status-approved">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Approved</h2>
							</div>
							<span class='svg icon icon-checkmark-circle'></span>
						</div>
					<?php break;

					case $waitingApprove: ?>
						<div class="widget-table dashboard quote-status status-waiting">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Waiting for approval</h2>
							</div>
							<span class='svg icon icon-information-circle'></span>
						</div>
					<?php break;

					case $disapproved: ?>
						<div class="widget-table dashboard quote-status status-disapproved">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Disapproved</h2>
							</div>
							<span class='svg icon icon-cancel-circle'></span>
						</div>
					<?php break;

					default: ?>
						<div class="widget-table dashboard quote-status status-notsubmitted">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Not submitted</h2>
							</div>
							<span class='svg icon icon-cancel-circle'></span>
						</div>
				<?php break;
				} ?>
			</div>

			<div class="middleNav">
				<ul>
					<li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
						<ul class="mSub1">
							<li><a href="#" title="">Share user</a></li>
							<li><a href="#" title="">Show Teamworks</a></li>
						</ul>
					</li>

					<li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
						<ul class="mSub4">
							<li><a href="#" title="">Add</a></li>
							<li><a href="#" title="">Save</a></li>
							<li><a href="#" title="">Edit</a></li>
							<li><a href="#" title="">Delete</a></li>
						</ul>
					</li>
				</ul>
			</div>

			<!-- Form -->
			<form method='post' class="form" id="quote_content">
				<div class="widget-table" id="customer_info">
					<input type="hidden" id="project_id" name='project_id' value="<?= $project['project_id'] ?>" />

					<div class="widget-header">
						<div class="widget-title">
							<h2>Quote details</h2>
						</div>
						<div class="widget-button">
							<button type="button" class="button action has-icon new-customer small" id="add_new_mode">
								<span class="button-wrap">
									<span class="icon icon-add"></span>
									New Customer
								</span>
							</button>
							<button type="button" class="button action has-icon discard-customer small basic" style='display:none;' id="discard_new_mode">
								<span class="button-wrap">
									<span class="icon icon-undo"></span>
									Discard Adding
								</span>
							</button>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<h3>Quote Infomation</h3>
						<div class="formRow">
							<div class="oneTwo">
								<label for="quote_id">Quote Number</label>
								<input id="quote_id" type="text" value='<?= $quoteID ?>' readonly />
							</div>
							<div class="oneTwo">
								<label for='type_id'>Quote Type</label>
								<select name="type_id" id='type_id' class="validate[required]">
									<option value="">Select Quote type</option>
									<?php foreach ($this->type as $t) { ?>
										<option value="<?= $t['type_id'] ?>" <?php if ($t['type_id'] == $quote['type_id']) echo 'selected'; ?>><?= $t['type_desc'] ?></option>
									<?php } ?>
								</select>
							</div>
							<div class="oneTwo">
								<label for='market_segment'>Project Segment</label>
								<input readonly id="market_segment" type="text" value='<?= $project['market_segment_desc'] ?>' />
							</div>

							<div class="oneTwo">
								<label for="ship_required_date">Ship Required Date</label>
								<input id="ship_required_date" type="text" class="datepicker" name='ship_required_date' value="<?php
																																if ($quoteShipRequiredDate && $quoteShipRequiredDate > new DateTime('2000-01-01')) {
																																	echo $quoteShipRequiredDate->format('Y-m-d');
																																} ?>" />
							</div>
							<div class="oneTwo">
								<label for="expire_date">Quote Expire Date</label>
								<input id="expire_date" type="text" class="datepicker" name='expire_date' value="<?php
																													if ($quoteExpireDate == null || $quoteExpireDate < $quoteDate) {
																														echo $quoteDate->modify('+60 days')->format('Y-m-d');
																													} else {
																														echo $quoteExpireDate->format('Y-m-d');
																													}
																													?>" />
							</div>
							<div class="oneTwo">
								<label for='architect_rep_id'>Architectural Representative</label>
								<input readonly id='architect_rep_id' name='architect_rep_id' type="text" value='<?= $architect_rep['name'] . ' - ' .  $architect_rep['default_company'] ?>' />
							</div>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<h3>Customer</h3>
						<div class="formRow">
							<input type="hidden" id="customer_id" name="customer_id" value="<?= $customer['customer_id'] ?>" />
							<input type="hidden" id="salesrep_id" name="salesrep_id" value="<?= $customer['salesrep_id'] ?>" />
							<div class="oneTwo required-field">
								<label for="customer_name">Customer</label>
								<input id='customer_name' name='customer_name' type="text" value="<?= $customer['customer_name'] ?>" />
							</div>

							<div class="oneTwo">
								<label for="company_id">Company ID</label>
								<input type="text" name='company_id' id='company_id' value="<?= $customer['company_id'] ?>" readonly />
							</div>

							<div class="oneTwo">
								<label for='salesrep_full_name'>Sales Representative</label>
								<input id='salesrep_full_name' name='salesrep_full_name' type="text" value="<?= $customer['salesrep_full_name'] ?>" readonly />
							</div>

							<div class="oneTwo">
								<label for="credit_term">Credit Terms</label>
								<input id="credit_term" type="text" value="<?= $customer['terms_desc'] ?>" readonly />
							</div>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<h3>Contact</h3>
						<div class="formRow">
							<input type="hidden" id="contact_id" name="contact_id" value="<?= $contact['contact_id'] ?>" />
							<div class="oneTwo required-field">
								<label for="contact_name">Contact</label>
								<select name='contact_name' id='contact_name' class="validate[required]">
									<option value=''>-- Please search for a customer first --</option>
									<?php
									foreach ($contactList as $c) { ?>
										<option value="<?= $c['contact_id'] ?>" <?php if ($c['contact_id'] == $quote['contact_id']) echo 'selected' ?>><?= $c['contact_full_name'] ?></option>
									<?php }
									?>
								</select>
							</div>

							<div class="oneTwo">
								<label for="first_name">First Name</label>
								<input readonly id='first_name' name='first_name' type="text" value="<?= $contact['first_name'] ?>">
							</div>

							<div class="oneTwo">
								<label for="last_name">Last Name</label>
								<input readonly id='last_name' name='last_name' type="text" value="<?= $contact['last_name'] ?>">
							</div>

							<div class="oneTwo">
								<label for="phys_address1">Address 1</label>
								<input readonly id='phys_address1' name='phys_address1' type="text" value="<?= $contact['phys_address1'] ?>" />
							</div>

							<div class="oneTwo">
								<label for="phys_address2">Address 2</label>
								<input readonly id='phys_address2' name='phys_address2' type="text" value="<?= $contact['phys_address2'] ?>">
							</div>

							<div class="oneTwo">
								<label for="phys_city">City</label>
								<input readonly id='phys_city' name='phys_city' type="text" value="<?= $contact['phys_city'] ?>">
							</div>

							<div class="oneTwo">
								<label for="phys_state">Province</label>
								<input readonly id='phys_state' name='phys_state' type="text" value="<?= $contact['phys_state'] ?>">
							</div>

							<div class="oneTwo">
								<label for="phys_postal_code">Postal Code</label>
								<input readonly id='phys_postal_code' name='phys_postal_code' type="text" value="<?= $contact['phys_postal_code'] ?>">
							</div>

							<div class="oneTwo">
								<label for="phys_country">Country</label>
								<input readonly id='phys_country' name='phys_country' type="text" value="<?= $contact['phys_country'] ?>">
							</div>

							<div class="oneTwo">
								<label for="central_phone_number">Phone Number</label>
								<input readonly id='central_phone_number' name='central_phone_number' type="text" class="maskPhoneExt" value="<?= $contact['central_phone_number'] ?>" />
							</div>


							<div class="oneTwo">
								<label for="email_address">Email</label>
								<input readonly type="text" value="<?= $contact['email_address'] ?>" id='email_address' name='email_address'>
							</div>

						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<h3>Approval</h3>
						<div class="formRow">
							<div class="oneTwo required-field">
								<label for="price_approve_id">Quote Approval</label>
								<?php if ($session_user['approve_id'] != null) { ?>
									<select name="price_approve_id" id="price_approve_id" class="validate[required]">
										<option value="">Select Approval</option>
										<?php foreach ($this->approval as $a) { ?>
											<option value="<?= $a['id'] ?>" <?php if ($a['id'] == $quote['price_approve_id']) echo 'selected'; ?>><?= $session_user['first_name'][0] . $session_user['last_name'][0] . ' / ' . $a['name'] . ' - ' . $a['default_company'] ?></option>
										<?php } ?>
									</select>
								<?php } else { ?>
									<select name="price_approve_id" id="price_approve_id">
										<?php foreach ($this->approval as $a) { ?>
											<?php if ($a['id'] == $quote['price_approve_id']) { ?><option value="<?= $a['id'] ?>" selected><?= $session_user['first_name'][0] . $session_user['last_name'][0] . ' / ' . $a['name'] . ' - ' . $a['default_company'] ?></option> <?php } ?>
										<?php } ?>
									</select>
								<?php } ?>
							</div>

							<div class="oneTwo required-field">
								<label for="lead_time_id">Lead Time</label>
								<select name="lead_time_id" id="lead_time_id" class="validate[required]">
									<option value="">Select Lead Time</option>
									<?php foreach ($this->leadtime as $a) { ?>
										<option value="<?= $a['lead_time_id'] ?>" <?php if ($quote['lead_time_id'] == $a['lead_time_id']) {
																						echo 'selected';
																					} ?>><?= $a['lead_time_desc'] ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<h3>Comment</h3>
						<div class="formRow">
							<div class="oneTwo">
								<label for="quote-note">Quote Note</label>
								<textarea id="quote-note" rows="5" cols="" name="note" placeholder="Add quote note here..."><?= $quote['note'] ?></textarea>
							</div>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-footer">
						<div class="widget-footer-button">
							<button disabled id="save_quote" type="button" title="Save quote information" class="button action save-quote-button small">
								<span class="button-wrap">
									Save
								</span>
							</button>
						</div>
					</div>
				</div>
			</form>

			<section aria-labelledby="items" id="section4" data-nav="Items">
				<div class="widget-table">
					<div class="widget-header">
						<div class="widget-title">
							<h2>Items</h2>
						</div>
						<div class="widget-button">
							<button type="button" title="Add new item" class="button action has-icon add-item-button small" id="opener">
								<span class="button-wrap">
									<span class="icon icon-add"></span>
									Add Item
								</span>
							</button>
						</div>
					</div>

					<div class="line"></div>

					<div class="widget-section">
						<table width="100%" class="sTable display nowrap" id="items">
							<thead>
								<tr>
									<th data-priority="1">Item</th>
									<th data-priority="1">Quality</th>
									<th data-priority="1">Unit Price</th>
									<th data-priority="1">UOM</th>
									<th data-priority="1">Total Price</th>
									<th data-priority="2">Note</th>
									<th data-priority="1">Options</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</section>

			<div id="dialog-message" title="Add Item">
				<form action="" class="dialog" id='item'>
					<div class="dialog-form">
						<div class="oneTwo required-field">
							<label for='item_id'>Item ID </label>
							<input type="hidden" name="item" id='item_input' />
							<input type="text" name='item_id' id="item_id" class="validate[required]" />
						</div>

						<div class="oneTwo required-field">
							<label for='uom'>UOM</label>
							<select name="uom" id='uom' class="validate[required]">
								<option value=''>-- Select UOM --</option>
							</select>
						</div>

						<div class="oneTwo required-field">
							<label for='price'>Price ($)</label>
							<input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="*You can override the price" />
						</div>

						<div class="oneTwo required-field">
							<label for='qty'>Quantity</label>
							<input type="text" name="qty" id='qty' class="validate[required]" />
						</div>

						<div class="oneTwo dialog-note">
							<label for='note'>Note</label>
							<textarea rows="10" name='note' id='note' maxlength="255" class="validate[maxSize[255]]"></textarea>
							<input type="hidden" id="is_edit" value='0' />
						</div>
					</div>
				</form>
			</div>
		</div>
	</main>
<?php }
?>

<script type="text/javascript">
	$("textarea").each(function() {
		this.setAttribute("style", "height:" + (this.scrollHeight) + "px;overflow-y:hidden;");
	}).on("input", function() {
		this.style.height = 0;
		this.style.height = (this.scrollHeight) + "px";
	});

	let itemTable = $("#items").DataTable({
		ajax: {
			url: "/quote/item/id/" + $('#quote_id').val(),
			dataSrc: ''
		},
		processing: true,
		columns: [{
				data: "item_id",
				render: function(data, type, row, meta) {
					return '<b class="item-name">' + data + '</b>' + '<br>' + row.item_desc;
				}
			},
			{
				data: "quantity",
				render: function(data) {
					let qty = Number.parseFloat(data).toFixed(0);
					return '<b>' + qty + '</b>';
				}
			},
			{
				data: "unit_price",
				render: function(data) {
					return '<b>' + data + '</b>';
				}
			},
			{
				data: "uom",
				render: function(data) {
					return '<b>' + data + '</b>';
				}
			},
			{
				data: "subtotal",
				render: function(data) {
					return '<b>' + data + '</b>';
				}
			},
			{
				data: "note",
				render: function(data) {
					let formattedText = data.replace(/(?:\r\n|\r|\n)/g, '<br>');
					return '<p>' + formattedText + '</p>';
				}
			},
			{
				data: "item_id",
				render: function(data, type, row, meta) {
					//var oldData = getolddata($(this).closest('tr'));
					return '<div class="row-button">' +
						'<a title="Edit this item" class="edit" href="#">' +
						'<span class="button-wrap">' +
						'<span class="icon icon-edit"></span>' +
						'</span></a>' +
						'<a title="Delete this item" class="item_delete" href="/quote/deleteitem/uid/' + row.item_uid + '"' +
						'index="' + data + '">' +
						'<span class="button-wrap">' +
						'<span class="icon icon-delete"></span>' +
						'</span></a></div>';
				}
			},
			{
				data: "item_uid",
				visible: false
			}
		],
		columnDefs: [{
			targets: '_all',
			className: 'dt-head-center'
		}, {
			targets: [0, 1, 2, 3, 4],
			className: 'dt-body-center'
		}],
		layout: {
			topStart: null,
			topEnd: null
		},
		order: [[7, 'desc']], // sort by item uid, newest item on top
		paging: false,
		scrollX: true,
		fixedColumns: {
			start: 1,
			end: 1
		}
	});


	function resetForm($form) {
		$form.find('input:text, input:password, input:file, select, textarea').val('');
		$form.find('input:radio, input:checkbox')
			.prop('checked', false)
			.prop('selected', false);
	}

	var current_edit_row = '';

	$(function() {

		let currentRow = '';

		$('#items tbody').on('click', 'tr', function() {
			currentRow = itemTable.row(this).data();
			//console.log(currentRow['product_id'], currentRow['note'], currentRow['qty']);
		});

		function getolddata(row) {
			let item_uid = currentRow['item_uid'];
			let item_id = currentRow['item_id'];
			let note = currentRow['note'];
			let qty = currentRow['quantity'];
			let unit_price = currentRow['unit_price'];
			let uom = currentRow['uom'];
			let data = {
				'item_uid': item_uid,
				'old_item_id': item_id,
				'old_uom': uom,
				'old_price': unit_price,
				'old_qty': qty,
				'old_note': note
			};
			return data;
		}

		$("#dialog-message").dialog({
			autoOpen: false,
			modal: true,
			width: 800,
			minWidth: 800,
			open: function() { // fade in background
				$('.ui-widget-overlay').hide().fadeIn();
			},
			beforeClose: function() { //fade out background
				$('.ui-widget-overlay:first')
					.clone()
					.appendTo('body')
					.show()
					.fadeOut(400, function() {
						$(this).remove();
					});
			},
			buttons: [{
					id: "add-item-confirm-button",
					text: "Add",
					click: function() {
						if ($("#item").validationEngine('validate') == true) {
							if ($('#is_edit').val() == 1) {
								edititem();
							} else {
								additem();
							}
							$(this).dialog("close");
							resetForm($('#item'));
						}
					}
				},
				{
					id: "add-item-cancel-button",
					text: "Cancel",
					click: function() {
						$(this).dialog("close");
					}
				}
			]
		});

		$('#opener').on("click", function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});

		$(document).on("click", "a.edit", function() {
			$("#dialog-message").dialog("open");
			current_edit_row = $(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});

		function set_edit(row) {
			$("#dialog-message").dialog("option", "title", "Edit Item");
			$('#is_edit').val(1);

			let oldData = getolddata(current_edit_row);

			$('#item #item_id').val(oldData['old_item_id']);
			$('#item #price').val(oldData['old_price']);
			$('#item #qty').val(oldData['old_qty']);
			$('#item #note').val(oldData['old_note']);

			getoumedit(oldData['old_item_id'], oldData['old_uom'], oldData['old_price']);
		}

		function edititem() {
			var olddata = getolddata(current_edit_row);
			$.ajax({
				url: '/quote/edititem/uid/' + olddata['item_uid'],
				type: "post",
				data: $("#item").serialize(),
				success: function(data) {
					itemTable.ajax.reload();
				}
			});
		}

		function additem() {
			$('.loading').show();
			$.ajax({
				url: '/quote/additem/id/' + $('#quote_id').val(),
				type: "post",
				data: $("#item").serialize(),
				success: function(data) {
					itemTable.ajax.reload();
				}
			});
		}

		function getoumedit(item_id, unit_number, price) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = JSON.parse(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option[value=' + unit_number + ']').attr('selected', 'selected');
					$('#uniform-uom span').html(unit_number);
					$('#price').val(price);
					$('.loading').hide();
				}
			});

		}

		$(".dialog #item_id").autocomplete({
			source: '/item/index/',
			minLength: 2,
			focus: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				return false;
			},
			select: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				$("#item_id ").val(ui.item.item_id);
				getoum(ui.item.item_id);
				$('#uom').removeAttr('disabled');
				$('#uniform-uom').removeClass('disabled');
				return false;
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a><b>" + item.item_id + " - " + item.item_desc + "</b></a>")
				.appendTo(ul);
		};

		function getoum(item_id) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = JSON.parse(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option').eq(0).attr("selected", "selected");
					$('#uniform-uom span').html(uom[0].uom);
					getprice();
					$('.loading').hide();
				}
			});

		}

		function getprice() {
			$('.loading').show();
			$.ajax({
				url: '/item/price/id/' + $("#item_id ").val() + '/uom/' + $("#uom ").val(),
				type: "get",
				success: function(data) {
					var price = JSON.parse(data);
					$('#price').val(price.price);
					$('.loading').hide();
				}
			});

		}

		$("#uom,#uniform-uom").on("change", function() {
			getprice();
			return false;
		});

		$(document).on('click', ".item_delete", function(e) {
			e.preventDefault();
			if (confirm("Are you sure you want to delete this item?") == true) {
				$('.loading').show();
				$.ajax({
					url: $(this).attr('href'),
					type: "get",
					success: function(data) {
						itemTable.ajax.reload();
						$('.loading').hide();
					}
				});
			}
		});

		function getcustomerbyid(id) {
			$.ajax({
				url: '/customer/fetchbyid/id/' + id,
				type: "get",
				success: function(data) {
					var result = JSON.parse(data);
					if (result != null) {
						$('#customer_id').val(result.customer_id);
						$('#customer_name').val(result.customer_name);
						$('#company_id').val(result.company_id);
						$('#salesrep_id').val(result.salesrep_id);
						$('#salesrep_full_name').val(result.salesrep_full_name);
						$('#credit_term').val(result.terms_desc);
					} else {
						alert('Can\'t find customer');
						$('#customer_info input').val('');
					}
				}
			});
		}

		function getContacts(customerID) {
			$.ajax({
				url: '/customer/contact/id/' + customerID,
				type: "get",
				success: function(data) {
					var contact = JSON.parse(data);
					var list = '';
					$.each(contact, function(i, item) {
						list = list + '<option value="' + item.contact_id + '">' + item.contact_full_name + '</option>';
					});
					$('#contact_name').html(list);
					$('#contact_name option').eq(0).attr("selected", "");
					$('#uniform-contact_name span').html(contact[0].contact);
					getContactInfo();
				}
			});
		}

		function getContactInfo() {
			$.ajax({
				url: '/customer/contactinfo/id/' + $('#contact_name').val(),
				type: "get",
				success: function(data) {
					var result = JSON.parse(data);
					if (result != null) {
						$('#contact_id').val(result.contact_id);
						$('#first_name').val(result.first_name);
						$('#last_name').val(result.last_name);
						$('#phys_address1').val(result.phys_address1);
						$('#phys_address2').val(result.phys_address2);
						$('#phys_city').val(result.phys_city);
						$('#phys_state').val(result.phys_state);
						$('#phys_postal_code').val(result.phys_postal_code);
						$('#phys_country').val(result.phys_country);
						$('#central_phone_number').val(result.central_phone_number);
						$('#email_address').val(result.email_address);
					}
				}
			});
		}

		$("#contact_name, #uniform-contact_name").on("change", function() {
			getContactInfo();
			return false;
		});

		/*
		function getOldCustomer() {
			let quoteTo = $('#quote').val();
			let firstName = $('#first_name').val();
			let lastName = $('#last_name').val();
			let address1 = $('#address').val();
			let address2 = $('#phys_address2').val();
			let city = $('#phys_city').val();
			let province = $('#mail_state').val();
			let postalCode = $('#mail_postal_code').val();
			let country = $('#phys_country').val();
			let phoneNumber = $('#tel').val();
			let contact = $('#contact').val();
			let email = $('#customer_email').val();
			let companyId = $('#company_id').val();
			let customerId = $('#contact_id').val();
			let oldData = {
				'oldQuoteTo': quoteTo,
				'oldFirstName': firstName,
				'oldLastName': lastName,
				'oldAddress1': address1,
				'oldAddress2': address2,
				'oldCity': city,
				'oldProvince': province,
				'oldPostalCode': postalCode,
				'oldCountry': country,
				'oldPhoneNumber': phoneNumber,
				'oldContact': contact,
				'oldEmail': email,
				'oldCustomerId': customerId,
				'oldCompanyId': companyId
			};
			return oldData;
		};

		let oldCustomer = '';

		$('#add_new_mode').on("click", function() {
			oldCustomer = getOldCustomer();
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id, #contact_id, #sale_rep').prop('readonly', false);
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id, #contact_id, #sale_rep').val('');
			$('#quote, #address, #tel, #customer_email').addClass('validate[required]');
			$('#add_new_mode').hide();
			$('#discard_new_mode').show();
		});

		$('#discard_new_mode').on("click", function() {
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id, #contact_id, #sale_rep').prop('readonly', true);
			$('#quote').val(oldCustomer['oldQuoteTo']);
			$('#first_name').val(oldCustomer['oldFirstName']);
			$('#last_name').val(oldCustomer['oldLastName']);
			$('#address').val(oldCustomer['oldAddress1']);
			$('#phys_address2').val(oldCustomer['oldAddress2']);
			$('#phys_city').val(oldCustomer['oldCity']);
			$('#mail_state').val(oldCustomer['oldProvince']);
			$('#mail_postal_code').val(oldCustomer['oldPostalCode']);
			$('#phys_country').val(oldCustomer['oldCountry']);
			$('#tel').val(oldCustomer['oldPhoneNumber']);
			$('#contact').val(oldCustomer['oldContact']);
			$('#customer_email').val(oldCustomer['oldEmail']);
			$('#contact_id').val(oldCustomer['oldCustomerId']);
			$('#company_id').val(oldCustomer['oldCompanyId']);

			$('#quote, #address, #tel,#customer_email').removeClass('validate[required]');
			$('#add_new_mode').show();
			$('#discard_new_mode').hide();
			oldCustomer = '';
		});

		$("#customer_email").autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.contact_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.email + "<br>" + item.first_name + ' ' + item.last_name + "</a>")
				.appendTo(ul);
		};*/

		$("#customer_name").autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
				getContacts(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.customer_id + " - " + item.company_id + "<br>" + item.customer_name + "</a>")
				.appendTo(ul);
		};

		/*
		$("#contact").autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.contact_id);
			},

		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};*/

		let unsave = false;

		$('#quote_content').on("change", function() {
			$('#save_quote').prop("disabled", false);
			unsave = true;
		});

		$('#save_quote').on("click", function(e) {
			e.preventDefault();
			if ($("#quote_content").validationEngine('validate') == true) {
				//$('#quote_content').trigger("submit");
				document.getElementById("quote_content").submit();
				unsave = false;
			}
		});

		window.onbeforeunload = function() {
			if (unsave) {
				$('#save_quote').trigger("focus");
				return "You have unsaved changes project information. Do you want to leave this page and discard your changes or stay on this page?";
			}
		}

		$('a.delete_quote').on("click", function(e) {
			if (confirm("You are about to delete this quote. Continue?") == true) {
				unsave = false; // prevent double pop-up
				$.ajax({
					url: $(this).attr('href'),
					type: "post",
					success: function(data) {}
				});
			} else {
				e.preventDefault();
			}
		});

		$('a.ready_quote').on("click", function(e) {
			unsave = false;
			e.preventDefault();
			$('.loading').show();
			$.ajax({
				url: $(this).attr('href'),
				type: "get",
				success: function(data) {
					window.scrollTo(0, 0);
					location.reload();
				}
			});
		});

		$('a.approve').on("click", function(e) {
			e.preventDefault();
			if ($("#quote_content").validationEngine('validate') == true) {
				if (confirm("You are about to approve this quote. Any changes will be saved. Continue?") == true) {
					unsave = false; // prevent double pop-up
					$.ajax({
						url: $(this).attr('href'),
						type: "post",
						data: $('#quote_content').serialize(),
						success: function(data) {
							window.location.reload();
							window.scrollTo(0, 0);
						}
					});
				}
			} else {
				return false;
			}

		});

		$('a.disapprove').on("click", function(e) {
			e.preventDefault();
			if (confirm("Are you sure you want to disapprove this quote?") == true) {
				unsave = false; // prevent double pop-up
				$.ajax({
					url: $(this).attr('href'),
					type: "get",
					success: function(data) {
						window.location.reload();
						window.scrollTo(0, 0);
					}
				});
			}
		});
	});
</script>