<div
    x-data="addressModal()"
    x-init="
		    window.addressModalComponent = $data;
            document.getElementById('architect-edit-add-address').addEventListener('click', () => open = true);"
    x-effect="
            if (open) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
                closeModal();
        }">

    <!-- Modal Overlay -->
    <div
        x-show="open"
        x-transition
        @keydown.escape.window="open = false"
        class="flex items-center justify-center z-50 fixed inset-0 bg-black/50"
        style="display: none;">
        <!-- Modal Box -->
        <div
            class="bg-background ring-neutral z-50 grid w-full max-w-[calc(100%-2rem)] gap-4 rounded-xl border border-none bg-clip-padding p-6 shadow-2xl ring-4 ring-neutral-200/80 sm:max-w-2xl dark:bg-neutral-900 dark:ring-neutral-800"
            x-transition>
            <div class="flex flex-col gap-2 text-center sm:text-left">
                <h2
                    class="leading-none font-semibold text-lg"
                    x-text="isEditing ? 'Edit Address' : 'Add Address'">
                </h2>
                <p
                    class="text-muted-foreground text-sm"
                    x-text="isEditing ? 'Edit address info.' : 'Add an address to this architect.'">
                </p>
            </div>

            <div class="text-popover-foreground flex h-full w-full flex-col overflow-hidden">
                <div class="max-h-[300px] scroll-py-1 overflow-x-hidden overflow-y-auto no-scrollbar min-h-100 scroll-pt-2 scroll-pb-1.5">
                    <form id="address-form" @submit.prevent="submitForm" class="form">
                        <div class="flex flex-col gap-4 md:gap-6 md:grid md:grid-cols-2">
                            <input type="hidden" name='address_id' id='address_id' />
                            <div class="grid gap-2 ">
                                <label for="address_name">Address Nickname</label>
                                <input type='text' name="address_name" id='address_name'
                                placeholder="Head Office, Work, ..."/>
                            </div>

                            <div class="grid gap-2 ">
                                <label for="phys_address1">Address 1</label>
                                <input required type='text' name="phys_address1" id='phys_address1' placeholder="Required" />
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_address2">Address 2</label>
                                <input type='text' name="phys_address2" id='phys_address2' placeholder="Optional" />
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_city">City</label>
                                <input type='text' name="phys_city" id='phys_city' placeholder="Optional" />
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_state">Province</label>
                                <input type='text' name="phys_state" id='phys_state' placeholder="Optional" />
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_postal_code">Postal Code</label>
                                <input type='text' name="phys_postal_code" id='phys_postal_code' placeholder="Optional" />
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_country">Country</label>
                                <input type='text' name="phys_country" id='phys_country' placeholder="Optional" />
                            </div>

                            <div class="grid gap-2">
                                <label for="central_phone_number">Phone Number</label>
                                <input id='central_phone_number' name='central_phone_number' type="tel" class="maskPhone" placeholder="(123) 456-7890" />
                            </div>

                            <div class="grid gap-2">
                                <label for="email_address">Email</label>
                                <input type="text" value="" id='email_address' name='email_address' placeholder="Optional">
                            </div>

                            <div class="grid gap-2">
                                <label for="url">URL</label>
                                <input type="url" value="" id='url' name='url' placeholder="Optional">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                <button type="button" class="btn-outline" @click="closeModal()">Cancel</button>
                <button
                    type="submit"
                    class="btn bg-blue-500 hover:bg-blue-500/90 dark:bg-blue-400 hover:dark:bg-blue-400/90"
                    form="address-form">
                    Save
                </button>
            </div>
        </div>
    </div>
</div>
