<div
    x-data="customerModal()"
    x-init="
        window.customerModalComponent = $data;
        document.getElementById('widget-btn-add-quote')?.addEventListener('click', () => open = true);
        document.getElementById('options-btn-add-quote')?.addEventListener('click', () => open = true);"
    x-effect="
            if (open) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
                closeModal();
        }">

    <!-- Modal Overlay -->
    <div
        x-show="open"
        class="flex items-center justify-center z-50 fixed inset-0 bg-black/50"
        x-transition
        @keydown.escape.window="open = false"
        style="display: none;">
        <!-- Modal Box -->
        <div
            class="bg-background ring-neutral fixed z-50 grid w-full max-w-[calc(100%-2rem)] gap-4 rounded-xl border border-none bg-clip-padding p-6 shadow-2xl ring-4 ring-neutral-200/80 sm:max-w-5xl sm:max-h-screen dark:bg-neutral-900 dark:ring-neutral-800"
            x-transition>
            <div class="flex flex-col gap-2 text-center sm:text-left">
                <h2 class="leading-none font-semibold text-lg">Add quote</h2>
                <p class="text-muted-foreground text-sm">Add a customer and contact for this quote.</p>
            </div>

            <div class="text-popover-foreground flex h-full w-full flex-col overflow-hidden">
                <div class="max-h-[400px] scroll-py-1 overflow-x-hidden overflow-y-auto no-scrollbar min-h-80 scroll-pt-2 scroll-pb-1.5">
                    <form id="make-quote-form" @submit.prevent="submitForm" class="form">
                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
                            <input type="hidden" id="customer_id" name="customer_id" value="">
                            <input type="hidden" id="contact_id" name="contact_id" value="">
                            <div class="grid gap-2 required-field">
                                <label for="customer_name">Customer</label>
                                <input type="text" value="" id="customer_name" class='tipN validate[required]' placeholder="Search by ID or name">
                            </div>

                            <div class="grid gap-2">
                                <label for="company_id">Company ID</label>
                                <input id="company_id" type="text">
                            </div>

                            <div class="grid gap-2">
                                <label for="salesrep_full_name">Sales Representative</label>
                                <input id="salesrep_full_name" type="text">
                            </div>
                        </div>

                        <div class="h-[1px] bg-border my-4"></div>

                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
                            <div class="grid gap-2 required-field">
                                <label for="contact_name">Contact</label>
                                <select id="contact_name" class="validate[required]">
                                    <option value=''>-- Please search for a customer first --</option>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="first_name">First Name</label>
                                <input type="text" id="first_name">
                            </div>

                            <div class="grid gap-2">
                                <label for="last_name">Last Name</label>
                                <input type="text" id="last_name">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_address1">Address 1</label>
                                <input type="text" id="phys_address1">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_address2">Address 2</label>
                                <input type="text" id="phys_address2">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_city">City</label>
                                <input type="text" id="phys_city">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_state">Province</label>
                                <input type="text" id="phys_state">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_postal_code">Postal Code</label>
                                <input type="text" id="phys_postal_code">
                            </div>

                            <div class="grid gap-2">
                                <label for="phys_country">Country</label>
                                <input type="text" id="phys_country">
                            </div>

                            <div class="grid gap-2">
                                <label for="central_phone_number">Phone Number</label>
                                <input type="text" id="central_phone_number" class="maskPhoneExt">
                            </div>

                            <div class="grid gap-2">
                                <label for="email_address">Email</label>
                                <input type="text" id="email_address">
                            </div>
                        </div>
                    </form>
                </div>

                <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                    <button type="button" class="btn-outline" @click="closeModal()">Cancel</button>
                    <button
                        type="submit"
                        class="btn bg-blue-500 hover:bg-blue-500/90 dark:bg-blue-400 hover:dark:bg-blue-400/90"
                        form="make-quote-form"
                        id="customer-make-quote-btn">
                        Make Quote
                    </button>
                </div>
            </div>
        </div>
