<div
        x-data="noteModal()"
        x-init="
		    window.noteModalComponent = $data;
            document.getElementById('widget-btn-add-note').addEventListener('click', () => open = true);"
        x-effect="
            if (open) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
                closeModal();
        }">

        <!-- Modal Overlay -->
        <div
            x-show="open"
            class="flex items-center justify-center z-50 fixed inset-0 bg-black/50"
            x-transition
            @keydown.escape.window="open = false"
            style="display: none;">
            <!-- Modal Box -->
            <div
                class="bg-background ring-neutral fixed z-50 grid w-full max-w-[calc(100%-2rem)] gap-4 rounded-xl border border-none bg-clip-padding p-6 shadow-2xl ring-4 ring-neutral-200/80 sm:max-w-2xl dark:bg-neutral-900 dark:ring-neutral-800"
                x-transition>
                <div class="flex flex-col gap-2 text-center sm:text-left">
                    <h2
                        class="leading-none font-semibold text-lg"
                        x-text="isEditing ? 'Edit Note' : 'Add Note'">
                    </h2>
                    <p
                        class="text-muted-foreground text-sm"
                        x-text="isEditing ? 'Edit a note.' : 'Add a project note. A reminder about the project can also be set here.'">
                    </p>
                </div>

                <div class="text-popover-foreground flex h-full w-full flex-col overflow-hidden">
                    <div class="max-h-[400px] scroll-py-1 overflow-x-hidden overflow-y-auto no-scrollbar min-h-80 scroll-pt-2 scroll-pb-1.5">
                        <form id="dialog-note-form" @submit.prevent="submitForm">
                            <div class="flex flex-col md:gap-6 md:grid md:grid-cols-[2fr_1fr]">
                                <div class="flex flex-col gap-4 mb-4">
                                    <input type="hidden" name="note_id" id="note_id">
                                    <div class="grid gap-2 required-field">
                                        <label class="label" for="note_title">Title</label>
                                        <input class="input" type="text" name='note_title' id='note_title' placeholder="Title"></input>
                                    </div>

                                    <div class="grid gap-2 required-field">
                                        <label class="label" for="project_note">Content</label>
                                        <textarea rows="12" name='project_note' id='project_note' class="validate[required]"
                                            placeholder="Log content"></textarea>
                                    </div>
                                </div>

                                <div class="flex flex-col gap-4 mb-4">
                                    <div class="grid gap-2">
                                        <label class="label" for="next_action">Reminder</label>
                                        <textarea rows="12" name="next_action" id='next_action'
                                            placeholder="Can be left empty. Reminder will be sent via email if the follow up date is set."></textarea>
                                    </div>

                                    <div class="grid gap-2">
                                        <label class="label" for="follow_up_date">Reminder Time</label>
                                        <input type="text" class="input flatpickr-time" name='follow_up_date' id='follow_up_date'
                                            placeholder="Select time..." readonly>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                    <button type="button" class="btn-outline" @click="closeModal()">Cancel</button>
                    <button type="submit" class="btn bg-blue-500 hover:bg-blue-500/90 dark:bg-blue-400 hover:dark:bg-blue-400/90" form="dialog-note-form">Save</button>
                </div>
            </div>
        </div>
    </div>
