<dialog
    id="confirm-convert-dialog"
    class="dialog"
    aria-labelledby="confirm-convert-dialog-title"
    aria-describedby="confirm-convert-dialog-description">
    <article>
        <header>
            <h2 id="confirm-convert-dialog-title">Are you sure?</h2>
            <p id="confirm-convert-dialog-description">This will convert this opportunity to a project.</p>
        </header>

        <footer>
            <button class="btn-outline" onclick="document.getElementById('confirm-convert-dialog').close()">Cancel</button>
            <button class="confirm-convert-button btn-primary">Continue</button>
        </footer>
    </article>
</dialog>
