<div
    x-data="projectModal()"
    x-init="document.getElementById('architect-edit-add-project').addEventListener('click', () => open = true);"
    x-effect="
            if (open) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
                closeModal();
        }">

    <!-- Modal Overlay -->
    <div
        x-show="open"
        class="flex items-center justify-center z-50 fixed inset-0 bg-black/50"
        x-transition
        @keydown.escape.window="open = false"
        style="display: none;">
        <!-- Modal Box -->
        <div
            class="bg-background ring-neutral fixed z-50 grid w-full max-w-[calc(100%-2rem)] gap-4 rounded-xl border border-none bg-clip-padding p-6 shadow-2xl ring-4 ring-neutral-200/80 sm:max-w-5xl sm:max-h-screen dark:bg-neutral-900 dark:ring-neutral-800"
            x-transition>
            <div class="flex flex-col gap-2 text-center sm:text-left">
                <h2 class="leading-none font-semibold text-lg">New Project</h2>
                <p class="text-muted-foreground text-sm">Add a new project for this architect.</p>
            </div>

            <div class="text-popover-foreground flex h-full w-full flex-col overflow-hidden">
                <div class="max-h-[400px] scroll-py-1 overflow-x-hidden overflow-y-auto no-scrollbar min-h-80 scroll-pt-2 scroll-pb-1.5">
                    <form id="architect-edit-project-form" @submit.prevent="submitForm">
                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
                            <div class="grid gap-2">
                                <label for="project_name">Project Name</label>
                                <input required type="text" id='project_name' name='project_name' />
                            </div>

                            <div class="grid gap-2">
                                <label for='project_address'>Project Location</label>
                                <input required id='project_address' name='project_address' type="text" />
                            </div>

                            <div class="grid gap-2">
                                <label for="location_id">Centura Location</label>
                                <select name="location_id" id="location_id">
                                    <?php foreach ($locations as $l) { ?>
                                        <option
                                            value='<?= $this->escapeHtml($l['location_id']) ?>'
                                            <?php if ($l['location_id'] === DEFAULT_LOCATION_ID) {
                                                echo 'selected';
                                            } ?>>
                                            <?= $l['branch_description'] ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="status">Project Stage</label>
                                <select required name="status" id='status'>
                                    <option value="">-- Select stage --</option>
                                    <?php foreach ($projectStatus as $s) { ?>
                                        <option value='<?= $this->escapeHtml($s['id']) ?>'><?= $s['status_desc'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="market_segment_id">Project Segment</label>
                                <select required name="market_segment_id" id='market_segment_id'>
                                    <option value="">-- Choose market segment --</option>
                                    <?php foreach ($marketSegment as $s) { ?>
                                        <option value='<?= $this->escapeHtml($s['id']) ?>'><?= $s['market_segment_desc'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="reed">REED ID</label>
                                <input type="text" name='reed' original-title="REED Format" id='reed' />
                            </div>

                            <div class="grid gap-2">
                                <label for="due_date">Tender Due Date</label>
                                <input readonly type="text" id="due_date" name='due_date' class="flatpickr" placeholder="Due date" />
                            </div>

                            <div class="grid gap-2">
                                <label for="require_date">Required Date</label>
                                <input readonly type="text" id="require_date" name='require_date' class="flatpickr" placeholder="Required date" />
                            </div>

                            <?php if ($user['approve_id'] != null) : ?>
                                <div class="grid gap-2">
                                    <label for="shared_id">Share Worksheet</label>
                                    <input type="text" id="shared_id" name="shared_id" placeholder="Share this project with other salesrep" />
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="h-[1px] bg-border my-4"></div>

                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:gap-6">
                            <div class="grid gap-2">
                                <label for="address_id">Address List</label>
                                <select name='address_id' id='address_id'>
                                    <?php if (! empty($addressList)) :
                                        foreach ($addressList as $a) : ?>
                                            <option value='<?= $this->escapeHtml($a['id']) ?>'>
                                                <?= $a['name'] . ' - ' . $a['phys_address1'] ?>
                                            </option>
                                    <?php endforeach;
                                    endif; ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="specifier_id">Specifier</label>
                                <select name='specifier_id' id='specifier_id'>
                                    <?php if (! empty($specifierList)) :
                                        foreach ($specifierList as $spec) : ?>
                                            <option value='<?= $this->escapeHtml($spec['id']) ?>'>
                                                <?= $spec['first_name'] . ' ' . $spec['last_name'] ?>
                                            </option>
                                    <?php endforeach;
                                    endif; ?>
                                </select>
                            </div>
                        </div>

                        <div class="h-[1px] bg-border my-4"></div>

                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:gap-6">
                            <div class="grid gap-2">
                                <label for="general_contractor_name">General Contractor</label>
                                <input type="text" id="general_contractor_name" name="general_contractor_name" class='reverse-autocomplete' placeholder="Add general contractor" original-title="Type Company Name" />
                                <input type="hidden" id="general_contractor_id" name="general_contractor_id" />
                            </div>

                            <div class="grid gap-2">
                                <label for="awarded_contractor_name">Awarded Contractor</label>
                                <input id="awarded_contractor_name" name="awarded_contractor_name" type="text" class='reverse-autocomplete' placeholder="Add awarded contractor" original-title="Type Company Name" />
                                <input id="awarded_contractor_id" name="awarded_contractor_id" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                <button type="button" class="btn-outline" @click="closeModal()">Cancel</button>
                <button type="submit" class="btn bg-blue-500 hover:bg-blue-500/90 dark:bg-blue-400 hover:dark:bg-blue-400/90" form="architect-edit-project-form">Save</button>
            </div>
        </div>
    </div>
</div>
