<div
    x-data="specifierModal()"
    x-init="
		    window.specifierModalComponent = $data;
            document.getElementById('architect-edit-add-specifier').addEventListener('click', () => open = true);"
    x-effect="
            if (open) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
                closeModal();
        }">

    <!-- Modal Overlay -->
    <div
        x-show="open"
        x-transition
        @keydown.escape.window="open = false"
        class="flex items-center justify-center z-50 fixed inset-0 bg-black/50"
        style="display: none;">
        <!-- Modal Box -->
        <div
            class="bg-background ring-neutral z-50 grid w-full max-w-[calc(100%-2rem)] gap-4 rounded-xl border border-none bg-clip-padding p-6 shadow-2xl ring-4 ring-neutral-200/80 sm:max-w-xl dark:bg-neutral-900 dark:ring-neutral-800"
            x-transition>
            <div class="flex flex-col gap-2 text-center sm:text-left">
                <h2
                    class="leading-none font-semibold text-lg"
                    x-text="isEditing ? 'Edit Specifier' : 'Add Specifier'">
                </h2>
                <p
                    class="text-muted-foreground text-sm"
                    x-text="isEditing ? 'Edit specifier info.' : 'Add a specifier to this architect.'">
                </p>
            </div>

            <div class="text-popover-foreground flex h-full w-full flex-col overflow-hidden">
                <div class="max-h-[300px] scroll-py-1 overflow-x-hidden overflow-y-auto no-scrollbar min-h-50 scroll-pt-2 scroll-pb-1.5">
                    <form id="specifier-form" @submit.prevent="submitForm" class="form">
                        <div class="flex flex-col gap-4 md:gap-6 md:grid md:grid-cols-2">
                            <input type="hidden" id='specifier_id' name="specifier_id" />
                            <input type="hidden" id='specifier_address_id' name="specifier_address_id" />
                            <div class="grid gap-2 ">
                                <label for="specifier_first_name">First Name</label>
                                <input
                                    type='text'
                                    id='specifier_first_name'
                                    name="specifier_first_name"
                                    class="tipN" />
                            </div>

                            <div class="grid gap-2 ">
                                <label for="specifier_last_name">Last Name</label>
                                <input
                                    type='text'
                                    id='specifier_last_name'
                                    name="specifier_last_name"
                                    placeholder="Optional" />
                            </div>

                            <div class="grid gap-2 ">
                                <label for="specifier_job_title">Job Title</label>
                                <input
                                    type='text'
                                    id='specifier_job_title'
                                    name="specifier_job_title"
                                    placeholder="Optional" />
                            </div>

                            <div class="grid gap-2 ">
                                <label for="specifier_phone_number">Phone Number</label>
                                <input
                                    type='tel'
                                    id='specifier_phone_number'
                                    name="specifier_phone_number"
                                    class="maskPhone"
                                    placeholder="(123) 456-7890" />
                            </div>

                            <div class="grid gap-2 ">
                                <label for="specifier_email">Email</label>
                                <input
                                    type='text'
                                    id='specifier_email'
                                    name="specifier_email"
                                    placeholder="Optional" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                <button type="button" class="btn-outline" @click="closeModal()">Cancel</button>
                <button
                    type="submit"
                    class="btn bg-blue-500 hover:bg-blue-500/90 dark:bg-blue-400 hover:dark:bg-blue-400/90"
                    form="specifier-form">
                    Save
                </button>
            </div>
        </div>
    </div>
</div>
