   <? $session =  Zend_Registry::get('session'); ?>
 <!-- Title area -->
  <? $project = $this->project;?>
    <div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
                <h5>Price Quote</h5>
                <span>Project Name: <b><?=$project['project_name'] ?></b></span> | <span>Project Quote No: <b><?=$project['quote_no'] ?></b></span>  | <span>Worksheet Owner: <b><?=$project['owner'] ?></b></span> | <span>Status: <b><?=$project['status_name'] ?></b></span>  | <span>Due Date: <b><?=$project['due_date']->format('Y-m-d')  ?></b></span>
            </div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id='status'>
            <? if($this->quote['approve_status'] == 1 ) {?>
            <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote is waiting for approval.</p>
         	 </div>
          	<? }?>
          	<? if($this->quote['approve_status'] == 10 ) {?>
            <div class="nNote nSuccess hideit">
            <p><strong>INFORMATION: </strong>Quote has been approved.</p>
            </div>
          	<? }?>
          	<? if($this->quote['approve_status'] == -1 ) {?>
            <div class="nNote nFailure hideit">
            <p><strong>INFORMATION: </strong>Quote is disapproved.</p>
            </div>
          	<? }?>
          </div>
        </div>
    </div>
    
    <div class="line"></div>
 <!-- Page statistics area -->
    <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                    <? if($this->quote['approve_status'] != 10 ) {?>
                    	<li><a href="/quote/approve/id/<?=$this->quote['quote_id']?>" title="" class='approve'><img src="/images/icons/control/32/ok.png" alt="" /><span>Approve</span></a></li>
                  	<? }?>
                  	<li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/quote/print/id/".$this->quote['quote_id']."&name=Centura_Quote_".$this->quote['quote_id']?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Quote</span></a></li>
                    <? if($this->quote['approve_status'] == 10 ) {?>
                    <li><a href="/mail/quote/id/<?=$this->quote['quote_id']?>" title="mail"><img src="/images/icons/control/32/mail.png" alt="" /><span>Mail Quote</span></a></li>
                    <li><a href="/quote/approve/id/<?=$this->quote['quote_id']?>" title="" class='approve'><img src="/images/icons/control/32/ok.png" alt="" /><span>Edit And Approve</span></a></li>
                  	<? } ?>
                  	 <? if($this->quote['approve_status'] != -1 ) {?>
                    	<li><a href="/quote/disapprove/id/<?=$this->quote['quote_id']?>" title="" class='disapprove'><img src="/images/icons/control/32/no.png" alt="" /><span>Disapprove</span></a></li>
                    <? } ?>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    
    <div class="line"></div>
    
    <!-- Main content wrapper -->
    <div class="wrapper">
    
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
        <form  method='post' class="form" id="quote_content">
            <input type="hidden" name='project_id' value="<?=$project['project_id'] ?>" />
            <fieldset>
                <div class="widget" id="customer_info">
                    <div class="title"><img src="/images/icons/dark/user.png" alt="" class="titleIcon" /><h6>Customer Infomation</h6><a href="javascript:void(0)" title="" class="smallButton" style="margin: 2px;" id="add_new_mode"><span>New Customer</span></a></div>
                    <div class="formRow">
                        <label>Quote To:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="<?=$this->customer['name'] ?>" id='quote' name='name'/></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Address:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="<?=$this->customer['phys_address1'] ?>" id='address' name='phys_address1' readonly/></div>
                        <div class="clear"></div>
                    </div>
                    <div class="formRow">
                        <label>Tel:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" id='tel' name='phone' class="maskPhoneExt" value="<?=$this->customer['tel'] ?>" id='tel' name='tel' readonly/></div>
                        <div class="clear"></div>
                    </div>
                    <div class="formRow">
                        <label>Customer ID :<span class="req">*</span></label>
                        <div class="formRight"><input name='customer_id'  type="text" id='customer_id'  class="validate[custom[integer]]" value="<?=$this->customer['customer_id'] ?>" placeholder="Leave blank for add new customer" readonly/></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Contact:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" id='contact' name='fullname' value="<?=$this->customer['fullname'] ?>" class="validate[required]"  placeholder="Enter Customer Name to fetch existing customer" /></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Email:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="<?=$this->customer['email'] ?>" id='customer_email' name='Contacts_email' class="validate[custom[email]]" placeholder="Enter Customer Email to fetch existing customer"></div>
                        <div class="clear"></div>
                    </div>
              </div>
            </fieldset>
            <fieldset>
                <div class="widget">
                    <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
                      <h6>Quote Infomation</h6></div>
                     <div class="formRow"> 
                        <div class="formRight" style="width:98%">
                            <span class="oneFour"><span class="formNote">Quote Number</span><input type="text" value='<?=$this->quote['quote_id']?>' readonly /></span>
                            <span class="oneFour"><span class="formNote">Quote Date</span><input type="text" class="datepicker" value="<?=$this->quote['quote_date']->format('Y-m-d')?>" /></span>
                            <span class="oneFour"><span class="formNote">Quote Expire<span class="req">*</span></span><input type="text" class="datepicker validate[required]" name='expire_date' value="<? if($this->quote['expire_date'] == null || $this->quote['expire_date']->format('Y-m-d') < $this->quote['quote_date']->format('Y-m-d')) {echo date('Y-m-d', strtotime ( $this->quote['quote_date']->modify('+90 days')->format('Y-m-d') ) ); }else {echo $this->quote['expire_date']->format('Y-m-d');}?>"/></span>
                            <span class="oneFour"><span class="formNote">Quote Type</span>
                            		<select name="quote_type_id" id='quote_type' class="validate[required]" >
                                <option value="">Select Quote type</option>
                                <? foreach($this->type as $t) {?>
                                <option value="<?=$t['uid'] ?>" <? if($t['uid'] == $this->quote['quote_type_id']) echo 'selected';?>><?=$t['type'] ?></option>
                                <? } ?>
                            	</select>
                            </span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneFour"><span class="formNote">Project Name</span><input type="text" value="<?=$project['project_name']?>" readonly/></span>
                            <span class="oneFour"><span class="formNote">Project Location</span><input type="text" value="<?=$project['project_location_address']?>" readonly/></span>
                            <span class="oneFour"><span class="formNote">Sale Rep</span><input id='sale_rep' name='sale_rep' type="text" value="<?=$this->quote['sales_id'] ?>"readonly/></span>
                            <span class="oneFour"><span class="formNote">Arch Rep.<span class="req">*</span></span>
                            		<select id='arch'  class="validate[required]" >
                                <? foreach($this->arch as $a) {?>
                                <option value="<?=$a['id']?>" <? if($a['id'] == $this->quote['arch']) echo 'selected';?>><?=$a['name'].' - '.$a['default_company']?></option>
                             		 <? }?>
                            	</select>
                            </span>
                            <input type="hidden" name="sales_id" value="<?=$session->user['id'] ?>"" />
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	<span class="oneFour"><span class="formNote">Segment<span class="req">*</span></span><input type="text" class="validate[required]"  id='Segment' placeholder="123456-" name='quote_segment' value='<?=$this->quote['quote_segment']?>'/></span>
                        	 <span class="oneFour"><span class="formNote">Quote Approval<span class="req">*</span></span>
                            		<? if ($session->user['approve_id'] != null) {?>
                            		<select name="quote_approval" id="quote_approval" >
	                                <option value="">Select Approval</option>
	                                <? foreach($this->approval as $a) {?>
	                                <option value="<?=$a['uid']?>" <? if($a['uid'] == $this->quote['quote_approval']) echo 'selected';?>><?=$a['Name'].' - '.$a['Company_ID']?></option>
	                             		 <? }?>
                            		</select>
                            		<? } else {?>
                            		<select name="quote_approval" id="quote_approval" >
	                                <? foreach($this->approval as $a) {?>
	                                <? if($a['uid'] == $this->quote['quote_approval']) {?><option value="<?=$a['uid']?>"  selected ><?=$a['Name'].' - '.$a['Company_ID']?></option> <? }?>
	                             		 <? }?>
                            		</select>
                            		<?}?>
                            </span>
                            <span class="oneFour"><span class="formNote">Credit Terms<span class="req">*</span></span>
                            		<select name="credit_term" id="credit_term"  class="validate[required]">
	                                <option value="">Select Terms</option>
	                                <? foreach($this->terms as $a) {?>
	                                <option value="<?=$a['terms_desc']?>" <? if($this->userterm == $a['terms_desc'] && $this->quote['term'] == null) {echo 'selected';}  if($this->quote['term'] == $a['terms_desc']) {echo 'selected';}?>><?=$a['terms_desc']?></option>
	                             		 <? }?>
                            		</select>
                            </span>
                            <span class="oneFour"><span class="formNote">Lead Time<span class="req">*</span></span>
                            		<select name="lead_time" id="lead_time"  class="validate[required]">
	                                <option value="">Select Lead Time</option>
	                                <? foreach($this->leadtime as $a) {?>
	                                <option value="<?=$a['uid']?>" <? if($this->quote['lead_time'] == $a['uid']) {echo 'selected';}?>><?=$a['description']?></option>
	                             		 <? }?>
                            		</select>
                            </span>
                        </div>
                        <div class="clear"></div>
                    </div>
              </div>
            </fieldset>
             <div class="widget">
        <div class="title"><span class="titleIcon"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Items</h6><a href="#" title="" class="button greenB" style="margin: 5px;" id="opener"><span>Add new Item</span></a> </a></div>
        <div class="clear"></div>
          <table cellpadding="0" cellspacing="0" width="100%" class="sTable" id="items" style="text-align:center;">
              <thead>
                  <tr>
                      <td></td>
                      <td width="60%">Item ID - Description</td>
                      <td>Quality Quoted</td>
                      <td>Unit Price</td>
                      <td>Unit Of Measure</td>
                      <td>Price Quoted</td>
                      <td>Cost</td>
                      <td>Action</td>
                  </tr>
              </thead>
              <tbody id="item_body">
                 <? foreach ($this->items as $i) { ?>
                 		<tr name="item[<?=$i['product_id']?>]"><td><input type="checkbox" name="item[<?=$i['product_id']?>]"></td>
                 			<td><?=$i['product_id']?> - <?=$i['item_desc'] ?>
                 				<textarea rows="1" cols="" name="item[<?=$i['product_id']?>][note][]"><?=$i['note']?></textarea>
                 		  </td>
                 		  <td><?=$i['qty']?></td>
                 		  <td><?=$i['unit_price']?></td>
                 		  <td><?=$i['uom']?></td>
                 		  <td><?=$i['subtotal']?></td>
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][qty][]" value="<?=$i['qty']?>"><input type="hidden" name="item[<?=$i['product_id']?>][unit_price][]" value="<?=$i['unit_price']?>">
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][uom][]" value="<?=$i['uom']?>"><input type="hidden" name="item[<?=$i['product_id']?>][total_price][]" value="<?=$i['subtotal']?>">
	                 		   <input type="hidden" class='sorts' name="item[<?=$i['product_id']?>][sort][]" value="<?=$i['sort_id']?>">
	                 		<td class="<? if($i['unit_price'] < PRICE_LOW *$i['initprice']) echo 'low'?>"><?=round($i['initprice'],3)?></td>
                 		  <td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>
                 		</tr>
                 <? }?>
              </tbody>
          </table>
          </div>
           <div class="widget">
       <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
       <h6>Comment</h6></div>
        <div class="clear"></div>
        		<div class="formRow">
	            <label>Quote Note:</label>
	            <div class="formRight"><textarea rows="8" cols="" name="note" placeholder="Note Area"><?=$this->quote['note'] ?></textarea></div>
            <div class="clear"></div>
          </div>
      	</div>
        </div>
        </form>
            
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                   <? if($this->quote['approve_status'] != 10 ) {?>
                    	<li><a href="/quote/approve/id/<?=$this->quote['quote_id']?>" title="" class='approve'><img src="/images/icons/control/32/ok.png" alt="" /><span>Approve</span></a></li>
                  	<? }?>
                  	<li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/quote/print/id/".$this->quote['quote_id']."&name=Centura_Quote_".$this->quote['quote_id']?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Quote</span></a></li>
                    <? if($this->quote['approve_status'] == 10 ) {?>
                    <li><a href="/mail/quote/id/<?=$this->quote['quote_id']?>" title="mail"><img src="/images/icons/control/32/mail.png" alt="" /><span>Mail Quote</span></a></li>
                    <li><a href="/quote/approve/id/<?=$this->quote['quote_id']?>" title="" class='approve'><img src="/images/icons/control/32/ok.png" alt="" /><span>Edit And Approve</span></a></li>
                  	<? } ?>
                  	 <? if($this->quote['approve_status'] != -1 ) {?>
                    	<li><a href="/quote/disapprove/id/<?=$this->quote['quote_id']?>" title="" class='disapprove'><img src="/images/icons/control/32/no.png" alt="" /><span>Disapprove</span></a></li>
                    <? } ?>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    
    <div id="dialog-message" title="Add Item">
        <div class="uiForm">
            <form action="" class="dialog" id='item'>
            		<span class="formNote">Enter Item ID </span>
                <input type="text" name="item" id='item_input' class="validate[required]" />
                <input type="hidden" id="item_id"/>
                <span class="formNote">UOM</span>
                <select name="uom" id='uom' class="validate[required]" >
                      <option value=''>Select UOM</option>
                </select>
                <div class="clear"></div>
                <span class="formNote">Price ($)</span>
                <input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price"/>
                <span class="formNote">Qty</span>
                <input type="text" name="qty" id='qty' class="validate[required]"  />
                <input type="hidden" id="is_edit" value='0'/>
                <input type="hidden" id="note" value=''/>
                  <input type="hidden" id="sort" value=''/>
            </form>
        </div>
   </div>
   
   <script type="text/javascript" >
   		function resetForm($form) {
    $form.find('input:text, input:password, input:file, select, textarea').val('');
    $form.find('input:radio, input:checkbox')
         .removeAttr('checked').removeAttr('selected');
    $form.find('#sort').val(getmaxsort());
	}
	function getmaxsort()
		{
			var sorts = [];
			$( "#item_body .sorts" ).each(function(index ) {
			  sorts.push($(this).val());
			});
			
			console.log(sorts);
			if(sorts == null)
			{
				return 0;
			}
			else
			{
					return Math.max.apply( Math, sorts ) + 1;
			}
			
		}
	
	var current_edit_row = '';
   	$(function() {
	   		$( "#dialog-message" ).dialog({
				autoOpen: false,
				modal: true,
				buttons: {
					Ok: function() {
						if($("#item").validationEngine('validate') ==true)
						{
							if($('#is_edit').val() == 1)
							{
								edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val() ,$('#note').val(),$('#sort').val());
							}
							else
							{
								additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(),$('#sort').val() );
							}
							$( this ).dialog( "close" );
							resetForm($('#item'));
							 
						}
					}
				}
			});
			
				$('#opener').click(function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});	

		$(document).on("click", "a.edit",function() {
			$( "#dialog-message" ).dialog( "open" );
			current_edit_row =$(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});	
		
		function set_edit(row)
		{
			$( "#dialog-message" ).dialog( "option", "title", "Edit Item" );
			$('#is_edit').val(1);
			var item_id = $(row).attr('name').substr(5, ($(row).attr('name').length - 6));
			var item_name = jQuery.trim($(row).find('td').eq(1).clone().children().remove().end().text()).replace(item_id+' - ','');
			var note = $(row).find('textarea').eq(0).val();
			var qty = $(row).find('input:hidden').eq(0).val();
			var unit_price = $(row).find('input:hidden').eq(1).val();
			var uom = $(row).find('input:hidden').eq(2).val();
			var total_price = $(row).find('input:hidden').eq(3).val();
			var sort = $(row).find(':input:hidden').eq(4).val();
			
			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);

			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);
				$('#item #sort').val(sort);
			
			getoumedit(item_id,uom,unit_price);

		}
		
	function getoumedit(item_id,unit_number,price)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option[value='+unit_number+']').attr('selected','selected');
		     	$('#uniform-uom span').html(unit_number);
		     	$('#price').val(price);
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function edititem(item_id,item_desc,uom,price,qty,note,sort)
	{
		var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea rows="1" cols="" name="item['+item_id+'][note][]">'+note+'</textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'+'<td>'+'Not Avail'+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty][]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price][]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom][]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price][]" value="'+total_price+'"/>'
					+ '<input type="hidden" class="sorts" name="item['+item_id+'][sort][]" value="'+sort+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>';
		
		current_edit_row.replaceWith(str);
		
	}
	  
	  $( ".dialog #item_input" ).autocomplete({
	source: '/item/index/',
	minLength: 2,
	focus: function( event, ui ) {
				$( "#item_input" ).val( ui.item.item_desc );
				return false;
		},
	select: function( event, ui ) {
		$( "#item_input" ).val( ui.item.item_desc );
		$( "#item_id ").val( ui.item.item_id );
		getoum(ui.item.item_id );
		$('#uom').removeAttr('disabled');
		$('#uniform-uom').removeClass('disabled');
		 return false; 
		}
	}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>" + item.item_id + "<br>" + item.item_desc + "</a>" )
				.appendTo( ul );
	};
	function getoum(item_id)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option').eq(0).attr("selected", "selected"); 
		     	$('#uniform-uom span').html(uom[0].uom);
		     	getprice();
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function getprice()
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/price/id/'+$( "#item_id ").val()+'/uom/'+$( "#uom ").val(),
		  type: "get",
		  success: function(data) {
		  	 var price = jQuery.parseJSON(data);
		  		$('#price').val(price.price);
		  		$('.loading').hide();
		  }
		});
		
	}
	
	function additem(item_id,item_desc,uom,price,qty,sort)
	{
		var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea rows="1" cols="" name="item['+item_id+'][note][]"></textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'+'<td>'+'Not Avail'+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty][]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price][]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom][]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price][]" value="'+total_price+'"/>'
					+ '<input type="hidden" class="sorts" name="item['+item_id+'][sort][]" value="'+sort+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>';
		
		$('#item_body').append(str);
		
	}
	function getcustomerbyid(id)
	{
		$('.loading').show();
		$.ajax({
		  url: '/customer/fetchbyid/id/'+id,
		  type: "get",
		  success: function(data) {
		  	 var result = jQuery.parseJSON(data);
		  	 if(result != null)
		  	 {
		  		$('#quote').val(result.name);
		  		$('#customer_id').val(id);
		  		$('#address').val(result.phys_address1 + ' ' + result.phys_address2 + ' '+ result.phys_city + ' '+result.mail_state+ ' '+ result.phys_country+' ' + result.mail_postal_code);
		  		$('#tel').val(result.tel);
		  		$('#contact').val(result.first_name + ' ' + result.last_name);
		  		$('#customer_email').val(result.email);
		  		$('#sale_rep').val(result.sale_rep);
		  		
		  	}
		  	else
		  		{
		  			alert('Can\'t find customer');
		  			$('#customer_info input').val('');
		  		}
		  	$('.loading').hide();
		  }
		});
	}
	  $('#add_new_mode').click(function(){
        $('#quote, #address, #tel, #customer_id').removeAttr('readonly');
  	});
	
  	$("#uom,#uniform-uom").change(function(){
        getprice();
        return false;
  	});
  	$("#item_body .delete").live('click',function(e){
       $(this).parent().parent().remove();
       e.preventDefault();
  	});
  	
  	$( "#customer_email" ).autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>" + item.email + "<br>" + item.first_name+' ' + item.last_name + "</a>" )
				.appendTo( ul );
		};
		$( "#quote" ).autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
				.appendTo( ul );
		};
		$( "#contact" ).autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			},
			
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
				.appendTo( ul );
		};
		
		$('a.save_quote').click(function(e){
				e.preventDefault();
				if($("#quote_content").validationEngine('validate') ==true)
				{
					$('.loading').show();
	  			$('#quote_content').submit();
	  		}
  	});
  	
  
  	$('a.delete_quote').click(function(e){
  		if(confirm("Confirm delete This Quote?") == true)
  		{
  			
  		}
  		else
  		{
  					e.preventDefault();
  		}
  	});
  	
  	$('a.approve').click(function(e){
  			e.preventDefault();
  			if($("#quote_content").validationEngine('validate') ==true)
				{
					$('.loading').show();
					$.ajax({
					  url: "/quote/approve/id/<?=$this->quote['quote_id'] ?>",
					  type: "post",
					  data:$('#quote_content').serialize(),
					  success: function(data) {
					  	
					  	 window.location='/index/approval';
					  }
					});
					$('.loading').hide();
						
		  	}
		  	else
		  		{
		  			return false;
		  		}
  			
  	});
  	
  	$('a.disapprove').click(function(e){
  			e.preventDefault();
  			$('.loading').show();
				$.ajax({
				  url: "/quote/disapprove/id/<?=$this->quote['quote_id'] ?>",
				  type: "get",
				  success: function(data) {
				  	 window.location='/index/approval';
				  }
				});
				$('.loading').hide();
  	});
  	
  	
  	
  });
   	</script>
   	<style>
   		td.low {font-weight:bold;background:#B75D5D;color:white;}
   		</style>