<?php $session =  Zend_Registry::get('session');
//$project = $this->project; ?>
<!-- Title area -->
<main id="content" class="main-content">

  <div class="middleNav">
    <ul>
      <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
        <ul class="mSub1">
          <li><a href="#" title="">Share user</a></li>
          <li><a href="#" title="">Show Teamworks</a></li>
        </ul>
      </li>

      <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
        <ul class="mSub4">
          <li><a href="#" title="">Add</a></li>
          <li><a href="#" title="">Save</a></li>
          <li><a href="#" title="">Edit</a></li>
          <li><a href="#" title="">Delete</a></li>
        </ul>
      </li>
    </ul>
  </div>

  <div class="main-page-content">
    <header class="main-page-content-header">
      <h1>Add Project</h1>
    </header>
    <!-- Main content wrapper -->
    <section aria-labelledby="project-information" id="section1" data-nav="Project Information" class="active">
      <form action="/project/save" method="post" class="form" id='project_content'>
        <div class="widget-table">
        <h2>Project Information</h2>
          <div class="formRow">
            <div class="oneTwo required-field">
              <label for="project_name">Project Name</label>
              <input type="text" id='project_name' name='project_name' class="validate[required]" />
            </div>

            <div class="oneTwo">
              <label for="location">Centura Location</label>
              <select name="location" id="location">
                <?php foreach ($this->locations as $l) { ?>
                  <option value="<?= $l['location_id'] ?>" <?php if ($l['location_id'] == DEFAULT_COMPNAY_ID) echo 'selected' ?>><?= $l['name'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo">
              <label for="owner">Worksheet Owner</label>
              <input type="text" id="owner" value='<?= $session->user['name'] ?>' readonly />
            </div>
            <input type="hidden" name='owner' value='<?= $session->user['id'] ?>'>

            <div class="oneTwo">
              <label for="quote_no">Project ID</label>
              <input type="text" placeholder="Auto Generate" id='quote_no' name='quote_no' readonly />
            </div>
            <input name='create_date' type="hidden" value='<?= date('Y-m-d') ?>' readonly />

            <div class="oneTwo required-field">
              <label for='project_location_address'>Project Location</label>
              <input id='project_location_address' name='project_location_address' type="text" class="validate[required] tipN" original-title="Example: 53 Apex Road, Toronto, Ontario, M6A 2V6" />
            </div>

            <div class="oneTwo required-field">
              <label for="status">Status</label>
              <select name="status" id='status' class="validate[required]">
                <option value="">Select Status</option>
                <?php foreach ($this->status as $s) { ?>
                  <option value="<?= $s['uid'] ?>"><?= $s['Status'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo required-field">
              <label for="reed">REED ID</label>
              <input type="text" name='reed' original-title="REED Format" id='reed' class="validate[required] tipN" />
            </div>

            <div class="oneTwo">
              <label for="market_segment">Market Segment</label>
              <select name="market_segment" id='market_segment' class="validate[required]">
                <option value="">Choose Segment</option>
                <?php foreach ($this->seg as $s) { ?>
                  <option value="<?= $s['uid'] ?>"><?= $s['Market_Segment'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo required-field">
              <label for="architect_name">Project Architect/Owner</label>
              <input type='text' name="architect_name" id='architect_name' class="validate[required] tipN" original-title="Type 2 letter to start or add your own" />
              <input type="hidden" name='architect' id='architect' value="<?php // echo $project['architect'] ?>">
            </div>

            <div class="oneTwo">
              <label for="architect_loc">Architect Location</label>
              <select id="architect_loc" name="architect_loc">
                <?php foreach ($this->locations as $l) { ?>
                  <option value="<?= $l['company_id'] ?>" <?php if ($l['location_id'] == DEFAULT_COMPNAY_ID) echo 'selected' ?>><?= $l['name'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo required-field">
              <label for="specifiler_name">Specifier</label>
              <input type='text' id='specifiler_name' name="specifiler_name" value='<?= $this->spec_name ?>' class="validate[required] tipN">
              <input type="hidden" id='specifiler' name="specifiler" value="<?php //echo $project['specifiler'] ?>">
            </div>

            <div class="oneTwo">
              <label for="specifiler_loc">Specifier Location</label>
              <select id="specifiler_loc" name="specifiler_loc">
                <?php foreach ($this->locations as $l) { ?>
                  <option value="<?= $l['company_id'] ?>" <?php if ($l['location_id'] == DEFAULT_COMPNAY_ID) echo 'selected' ?>><?= $l['name'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo">
              <label for="due_date">Tender Due Date</label>
              <input type="text" id="due_date" name='due_date' class="datepicker" />
            </div>

            <div class="oneTwo">
              <label for="required_date">Material Required Date</label>
              <input type="text" id="required_date" name='required_date' class="datepicker" />
            </div>

            <div class="oneTwo">
              <label for="gerneral_contractor">General Contractor</label>
              <input id="gerneral_contractor" name="gerneral_contractor"type="text" class='tipN' original-title="Type Company Name" />
            </div>

            <div class="oneTwo">
              <label for="gerneral_contractor_loc">General Contractor Location</label>
              <select id="gerneral_contractor_loc" name="gerneral_contractor_loc">
                <?php foreach ($this->locations as $l) { ?>
                  <option value="<?= $l['company_id'] ?>" <?php if ($l['location_id'] == DEFAULT_COMPNAY_ID) echo 'selected' ?>><?= $l['name'] ?></option>
                <?php } ?>
              </select>
            </div>

            <div class="oneTwo">
              <label for="awarded_contractor">Awarded Contractor</label>
              <input id="awarded_contractor" name="awarded_contractor" type="text" class='tipN' original-title="Type Company Name" id="awarded_contractor" />
            </div>

            <div class="oneTwo">
              <label for="awarded_contractor_loc">Awarded Contractor Location</label>
              <select id="awarded_contractor_loc" name='awarded_contractor_loc'>
                <?php foreach ($this->locations as $l) { ?>
                  <option value="<?= $l['company_id'] ?>" <?php if ($l['location_id'] == DEFAULT_COMPNAY_ID) echo 'selected' ?>><?= $l['name'] ?></option>
                <?php } ?>
              </select>
                </div>
          </div>
        </div>
      </form>
    </section>
  </div>
</main>

<!-- Right panel -->
<div class="sidebar-container">
  <aside id="sidebar-quicklinks" class="sidebar">
    <nav aria-label="Actions" class="sidebar-inner">
      <div class="sidebar-inner-nav">
        <div class="quick-links">
          <ol>
            <li><a href="/project/" target="_blank" class='quick-link add_pro' title="Add new project">
                <span class='icon icon-add'></span>
								Add Project</a></li>
            <li><a href="#" class='quick-link save_pro' title="Save project">
                <span class='icon icon-save'></span>
                Save Project</span></a></li>
          </ol>
        </div>
      </div>
    </nav>
  </aside>
</div>


<script>

  function getcustomerbyid(id, obj) {
    $('.loading').show();
    $.ajax({
      url: '/customer/fetchbyid/id/' + id,
      type: "get",
      success: function(data) {
        var result = JSON.parse(data);
        if (result != null) {
          $(obj).val(result.name);
          $('input[name=' + $(obj).attr('id') + ']').val(result.customer_id);
        } else {
          alert('Can\'t find customer');
          $('#customer_info input').val('');
        }
        $('.loading').hide();
      }
    });
  }

  $("#awarded_contractor").autocomplete({
    source: function(request, response) {
      $.ajax({
        url: '/customer/fetchbynamecompany/',
        dataType: "json",
        data: {
          term: request.term,
          company: $('#awarded_contractor_loc').val()
        },
        success: function(data) {
          response(data);
        }
      });
    },
    minLength: 2,
    select: function(event, ul) {
      getcustomerbyid(ul.item.customer_id, $('#awarded_contractor'));
    },

  }).data("ui-autocomplete")._renderItem = function(ul, item) {
    return $("<li></li>")
      .data("item.autocomplete", item)
      .append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
      .appendTo(ul);
  };
  $("#gerneral_contractor").autocomplete({
    source: function(request, response) {
      $.ajax({
        url: '/customer/fetchbynamecompany/',
        dataType: "json",
        data: {
          term: request.term,
          company: $('#gerneral_contractor_loc').val()
        },
        success: function(data) {
          response(data);
        }
      });
    },
    minLength: 2,
    select: function(event, ul) {
      getcustomerbyid(ul.item.customer_id, $('#gerneral_contractor'));
    },

  }).data("ui-autocomplete")._renderItem = function(ul, item) {
    return $("<li></li>")
      .data("item.autocomplete", item)
      .append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
      .appendTo(ul);
  };
  $("#architect_name").autocomplete({
    source: function(request, response) {
      $('#architect').val('');
      $.ajax({
        url: '/sales/fetchspec/',
        dataType: "json",
        data: {
          term: request.term,
          loc: $('#architect_loc').val()
        },
        success: function(data) {
          response(data);
        }
      });
    },
    minLength: 2,
    select: function(event, ul) {
      $("#architect_name").val(ul.item.Specifier);
      $('#architect').val(ul.item.uid);
      return false;
    },

  }).data("ui-autocomplete")._renderItem = function(ul, item) {
    return $("<li></li>")
      .data("item.autocomplete", item)
      .append("<a>" + item.Specifier + "</a>")
      .appendTo(ul);
  };

  $("#specifiler_name").autocomplete({
    source: function(request, response) {
      $.ajax({
        url: '/sales/fetchspec/',
        dataType: "json",
        data: {
          term: request.term,
          loc: $('#specifiler_loc').val()
        },
        success: function(data) {
          response(data);
        }
      });
    },
    minLength: 2,
    select: function(event, ul) {
      $("#specifiler_name").val(ul.item.Specifier);
      $('#specifiler').val(ul.item.uid);
      return false;
    },

  }).data("ui-autocomplete")._renderItem = function(ul, item) {
    return $("<li></li>")
      .data("item.autocomplete", item)
      .append("<a>" + item.Specifier + "</a>")
      .appendTo(ul);
  };

  $('.save_pro').on("click", function(e) {
    e.preventDefault();
    if ($("#project_content").validationEngine('validate') == true) {
      $('.loading').show();
      $('#project_content').submit();
    }

  });
</script>