  <?php $session =  Zend_Registry::get('session'); ?>
    <?php $project = $this->project; ?>
  <!-- Title area -->
    <div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
                <h5>Project <?=$project['project_name'] ?> To Quote WorkSheet</h5>
                <?php if($project['status'] != 13) {?><span>Track project data and events critical to close of sales.</span><?php }?>
            </div>
        </div> 
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <?php if($project['status'] == 13) {?>
            <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>This Project hs been Closed!</p>
         	 </div>
            <?php }?>
        </div>
    
    <div class="line"></div>
    

 <!-- Main content wrapper -->
    <div class="wrapper">
     <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
            			<?php if($project['status'] != 13) {?>
                	<li><a href="/quote/index/project/<?=$project['project_id'] ?>" class='add_pro' title="add"><img src="/images/icons/control/32/plus.png" alt="" /><span>Make Quote</span></a></li> 
                	 <?php }?>
                	 <li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/project/print/id/".$project['project_id']."?company=".substr($project['quote_no'],0,3)."&name=Centura_Project_".preg_replace("![^a-z0-9]+!i", "_", $project['project_name']).'.pdf'?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
       
        <form  method="post" class="form" id='project_content'> 
        	<input type="hidden" id='project_id' value='<?=$project['project_id'] ?>' >
                <div class="widget">
                    <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
                      <h6>Project Information</h6></div>
                     <div class="formRow"> 
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Project Name</span><input type="text" placeholder="Project Name" name='project_name' value="<?=$project['project_name'] ?>" /></span>
                            <span class="oneFour"><span class="formNote">Centura Location</span><select name="location" id="location" style="width:300px;" disabled>
                            	<?php foreach ($this->locations as $l) {?>
                                <option value="<?=$l['location_id']?>" <?php if($l['location_id'] == $project['centura_location_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <?php } ?>
                            </select></span>
                            
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Worksheet Owner</span><input type="text"  value='<?=$project['owner_name'] ?>' readonly/></span>
                            <input type="hidden" name='owner' value='<?= $project['owner'] ?>' >
                            <span class="oneFour"><span class="formNote">Project#</span><input type="text" placeholder="123456" name='quote_no' value="<?=$project['quote_no'] ?>" readonly/></span>
                            <input name='create_date' type="hidden" value='<?=$project['create_date']->format('Y-m-d') ?>' />
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Project Location</span><input type="text" name='project_location_address' id="project_location_address" value='<?= $project['project_location_address'] ?>'/></span>
                            <span class="oneFour"><span class="formNote">Status:</span><select name="status" disabled>
                                <option >Select Status</option>
                                <?php foreach($this->status as $s) {?>
                                <option value="<?=$s['uid']?>" <?php if($s['uid'] == $project['status']) echo 'selected'?> ><?=$s['Status'] ?></option>
                                <?php }?>
                               
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">REED#</span><input type="text"  name='reed' placeholder="REED Format" value="<?= $project['reed'] ?>"/></span>
                            <span class="oneFour"><span class="formNote">Market Segment:</span><select name="market_segment" disabled>
                                <option >Choose Segment</option>
                                <?php foreach($this->seg as $s) {?>
                                <option value="<?=$s['uid']?>" <?php if($s['uid'] == $project['market_segment']) echo 'selected'?>><?=$s['Market_Segment'] ?></option>
                                <?php }?>
                               
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Project Architect/Owner<span class="req">*</span></span>
                            		<input type='text' name="architect_name" id='architect_name'  class="validate[required] tipN" original-title="Type 2 letter to start or add your own"   value='<?=$this->arch_name ?>' />
                                <input type="hidden" name='architect' id='architect' value="<?=$project['architect'] ?>">
                            </span>
                             <span class="oneFour"><span class="formNote">Architect Location</span><select id="architect_loc" >
                            	<?php foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <?php if($l['company_id'] == $this->architect['Company_ID']) echo 'selected'?> ><?=$l['name']?></option>
                               <?php } ?>
                            </select></span>
                           
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	 <span class="oneTwo"><span class="formNote">Specifier</span>
                        	 	<input type='text'  id='specifiler_name' name="specifiler_name" value='<?=$this->spec_name ?>' class="validate[required] tipN" original-title="Type 2 letter to start or add your own" > 
                            <input type="hidden" id='specifiler' name="specifiler" value="<?=$project['specifiler'] ?>"> 
                            </span>
                            <span class="oneFour"><span class="formNote">Specifier Location</span><select id="specifiler_loc" >
                            	<?php foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <?php if($l['company_id'] == $this->sepcloc['Company_ID']) echo 'selected'?> ><?=$l['name']?></option>
                               <?php } ?>
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Tender Due Date:</span><input type="text" name='due_date' class="datepicker" value='<?=$project['due_date']->format('Y-m-d') ?>' disabled/></span>
                            <span class="oneFour"><span class="formNote">Material Required Date:</span><input type="text" name='required_date'  class="datepicker" value='<?=$project['required_date']->format('Y-m-d') ?>' disabled/></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">General Contractor</span><input type="text"  placeholder="Type Name"  id="gerneral_contractor"  value='<?= $this->gerneral_contractor['name'].' - '.$this->gerneral_contractor['company_id']?>'/></span>
                            <span class="oneFour"><span class="formNote">General Contractor Location</span><select id="gerneral_contractor_loc"  style="width:300px;" disabled>
                            	<?php foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <?php if($l['company_id'] == $this->gerneral_contractor['company_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <?php } ?>
                            </select></span>
                            <input type="hidden" name='gerneral_contractor' value="<?= $project['general_contractor_id'] ?>">
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Awarded Sub Contractor:</span><input type="text" placeholder="Type Name" id="awarded_contractor" value='<?= $this->awarded_sub_contracotr['name'].' - '.$this->awarded_sub_contracotr['company_id']?>' /></span>
                            <span class="oneFour"><span class="formNote">Awarded Contractor Location</span><select id="awarded_contractor_loc" disabled>
                            	<?php foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <?php if($l['company_id'] == $this->awarded_sub_contracotr['company_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <?php } ?>
                            </select></span>
                            <input type="hidden" name='awarded_contractor' value="<?= $project['awarded_sub_contracotr_id'] ?>">
                        </div>
                        <div class="clear"></div>
              </div>
            
           
        </form>
         <form  method="post" class="form" id='project_log'> 
        <div class="widget">
        <div class="title"><span class="titleIcon"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Project Presented / For Quotation</h6><?php if($this->owner == 1) {?><a href="#" title="" class="button greenB" style="margin: 5px;" id="add_item"><span>Add New</span></a><a href="#" title="" class="button redB" style="margin: 5px;display:none" id="save_item" ><span>Save</span></a><?php }?></div>
        <div class="clear"></div>
           <table cellpadding="0" cellspacing="0" width="100%" class="sTable" id="items" style="text-align:center;">
              <thead>
                  <tr>
                      <td></td>
                      <td width="60%">Item ID - Description</td>
                      <td>Quality Quoted</td>
                      <td>Unit Price</td>
                      <td>Unit Of Measure</td>
                      <td>Price Quoted</td>
                      <td>Action</td>
                  </tr>
              </thead>
              <tbody id="item_body">
                 <?php foreach ($this->items as $i) { ?>
                 		<tr name="item[<?=$i['product_id']?>]"><td><input type="checkbox" name="item[<?=$i['product_id']?>]"></td>
                 			<td><?=$i['product_id']?> - <?=$i['item_desc'] ?>
                 				<textarea rows="1" cols="" name="item[<?=$i['product_id']?>][note]"><?=$i['note']?></textarea>
                 		  </td>
                 		  <td><?=$i['qty']?></td>
                 		  <td><?=$i['unit_price']?></td>
                 		  <td><?=$i['uom']?></td>
                 		  <td><?=$i['subtotal']?></td>
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][qty]" value="<?=$i['qty']?>"><input type="hidden" name="item[<?=$i['product_id']?>][unit_price]" value="<?=$i['unit_price']?>">
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][uom]" value="<?=$i['uom']?>"><input type="hidden" name="item[<?=$i['product_id']?>][total_price]" value="<?=$i['subtotal']?>">
	                 		  <td></a></td>
                 		  
                 		</tr>
                 <?php }?>
              </tbody>
          </table>
        </div>
			</form>
				 <div class="widget">
          <div class="title"><img src="/images/icons/dark/frames.png" alt="" class="titleIcon"><h6>Project Log</h6></div>
            <table cellpadding="0" cellspacing="0" width="100%" class="display" id='project_memo'>
                <thead>
                   <tr>
                        <td class="sortCol">Log Date</td>
                        <td class="sortCol" style='width:60%'>Action Items Completed</td>
                        <td class="sortCol">Follow Up Date</td>
                        <td class="sortCol">Next Action Required</td>
                        <td class="sortCol action"><div> </div></td>
                    </tr>
                </thead>
                <tbody>
                	 <?php foreach($this->memo as $l) {?>
                    <tr>
                        <td><?=$l['added']->format('Y-m-d'); ?></td>
                         <td><?=$l['title']; ?></td>
                        <td><?=$l['follow_up_date'] != null ? $l['follow_up_date']->format('Y-m-d') : ''; ?></td>
                        <td><?=$l['type']; ?></td>
                        <td><? if($this->owner == 1) {?><a href="/memo/delete/id/<?=$l['memo_id']; ?>" class='memo_delete'><img src="/images/icons/dark/close.png" alt="delete"></a><?php }?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>     
    </div>
 </div>
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
								<?php if($project['status'] != 13) {?>
                	<li><a href="/quote/index/project/<?=$project['project_id'] ?>" class='add_pro' title="add"><img src="/images/icons/control/32/plus.png" alt="" /><span>Make Quote</span></a></li> 
                	 <?php }?>
								  <li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/project/print/id/".$project['project_id']."?company=".substr($project['quote_no'],0,3)."&name=Centura_Project_".preg_replace("![^a-z0-9]+!i", "_", $project['project_name']).'.pdf'?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
   
   
   <style>
   	div.selector { width: 290px;}
div.selector select { width: 300px; }
div.selector span { width: 290px;  }
   	</style>
   	
<script type="text/javascript" >
	 $('input').attr('readonly','readonly');
	 $('.selector').attr('diabled','diabled');
  
  	

   		</script>