<?php
$session =  Zend_Registry::get('session');
$project = $this->project;
?>


<!-- Title area -->
<main id="content" class="main-content">

    <div class="main-page-content">
        <header class="main-page-content-header">
            <div class="options-menu">
                <button class="quick-link options-button" id="options-button" type="button">
                    <span class='icon icon-menu'></span>
                    Options
                </button>

                <!-- Right panel -->
                <div class="sidebar-container" id="options-menu-items">
                    <?php if ($project['status'] != 13) { ?>
                        <a class='button quick-link add_pro' href="/quote/index/project/<?= $project['project_id'] ?>" title="add">
                            <span class='icon icon-dollar'></span>
                            Make Quote</a>
                    <?php } ?>
                    <a class="button quick-link" href="<?= 'http://' . SITEURL . "/dompdf/print.php?url=" . 'http://' . SITEURL . "/project/print/id/" . $project['project_id'] . "?company=" . substr($project['quote_no'], 0, 3) . "&name=Centura_Project_" . preg_replace("![^a-z0-9]+!i", "_", $project['project_name']) . '.pdf' ?>" title="print">
                        <span class='icon icon-pdf'></span>
                        Print Project</a>
                    <a class="button quick-link" target="_blank" href="/project/edit/id/<?= $project['project_id'] ?>" title="Edit this project">
                        <span class='icon icon-external'></span>
                        Go to Edit</a>
                </div>
            </div>

            <h1>Project Information</h1>
        </header>

        <div class="widget-information">
            <div style="grid-row: 1/1" class="widget-table dashboard">
                <span class='svg icon icon-list'></span>
                <div class="project-information project-name">
                    <h2><?= $project['project_name'] ?></h2>
                    <p>by <b><?= $project['owner'] ?></b></p>
                </div>
            </div>

            <div class="widget-table dashboard">
                <span class='svg icon icon-calender'></span>
                <div class="project-information">
                    <p>Due date</p>
                    <h2><?= $project['due_date']->format('Y-m-d') ?></h2>
                </div>
            </div>

            <div class="widget-table dashboard">
                <div class="project-information">
                    <span class='svg icon icon-information-circle'></span>
                    <p>Project status</p>
                    <h2>
                        <?php if ($project['status'] != 13) {
                            echo $project['status_name'];
                        } else {
                            echo 'Closed';
                        } ?>
                    </h2>
                </div>
            </div>
        </div>

        <!-- Form -->
        <section aria-labelledby="project-information" id="section1" data-nav="Project information" class="active">
            <form method="post" class="form" id='project_content'>
                <input type="hidden" id='project_id' value='<?= $project['project_id'] ?>'>
                <div class="widget-table">
                    <h2>Project information</h2>
                    <div class="formRow">
                        <div class="oneTwo">
                            <label for="project_name">Project Name</label>
                            <input id="project_name" type="text" placeholder="Project Name" name='project_name' value="<?= $project['project_name'] ?>" />
                        </div>
                        <div class="oneTwo">
                            <label for="location">Centura Location</label>
                            <select name="location" id="location" disabled>
                                <?php foreach ($this->locations as $l) { ?>
                                    <option value="<?= $l['location_id'] ?>" <?php if ($l['location_id'] == $project['centura_location_id']) echo 'selected' ?>><?= $l['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="oneTwo">
                            <label for="owner">Worksheet Owner</label>
                            <input id="owner" type="text" value='<?= $project['owner_name'] ?>' readonly />
                            <input type="hidden" name='owner' value='<?= $project['owner'] ?>'>
                        </div>
                        <div class="oneTwo">
                            <label for="quote_no">Quote ID</label>
                            <input id="quote_no" type="text" placeholder="123456" name='quote_no' value="<?= $project['quote_no'] ?>" readonly />
                            <input name='create_date' type="hidden" value='<?= $project['create_date']->format('Y-m-d') ?>' />
                        </div>
                        <div class="oneTwo">
                            <label for="project_location_address">Project Location</label>
                            <input type="text" name='project_location_address' id="project_location_address" value='<?= $project['project_location_address'] ?>' />
                        </div>
                        <div class="oneTwo">
                            <label for="status">Status</label>
                            <select id="status" name="status" disabled>
                                <option>-- Select status --</option>
                                <?php foreach ($this->status as $s) { ?>
                                    <option value="<?= $s['uid'] ?>" <?php if ($s['uid'] == $project['status']) echo 'selected' ?>><?= $s['Status'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="oneTwo">
                            <label for="reed">REED ID</label>
                            <input id="reed" type="text" name='reed' placeholder="REED Format" value="<?= $project['reed'] ?>" />
                        </div>
                        <div class="oneTwo">
                            <label for="market_segment">Market Segment</label>
                            <select id="market_segment" name="market_segment" disabled>
                                <option>-- Choose segment --</option>
                                <?php foreach ($this->seg as $s) { ?>
                                    <option value="<?= $s['uid'] ?>" <?php if ($s['uid'] == $project['market_segment']) echo 'selected' ?>><?= $s['Market_Segment'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="oneTwo required-field">
                            <label for='architect_name'>Project Architect/Owner</label>
                            <input type='text' name="architect_name" id='architect_name' class="validate[required] tipN" original-title="Type 2 letter to start or add your own" value='<?= $this->arch_name ?>' />
                            <input type="hidden" name='architect' id='architect' value="<?= $project['architect'] ?>">
                        </div>
                        <div class="oneTwo">
                            <label for="architect_loc">Architect Location</label>
                            <select id="architect_loc" name="architect_loc">
                                <?php foreach ($this->locations as $l) { ?>
                                    <option value="<?= $l['company_id'] ?>" <?php if ($l['company_id'] == $this->architect['Company_ID']) echo 'selected' ?>><?= $l['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="oneTwo">
                            <label for='specifiler_name'>Specifier</label>
                            <input type='text' id='specifiler_name' name="specifiler_name" value='<?= $this->spec_name ?>' class="validate[required] tipN" original-title="Type 2 letter to start or add your own">
                            <input type="hidden" id='specifiler' name="specifiler" value="<?= $project['specifiler'] ?>">
                        </div>
                        <div class="oneTwo">
                            <label for="specifiler_loc">Specifier Location</label>
                            <select id="specifiler_loc" name="specifiler_loc">
                                <?php foreach ($this->locations as $l) { ?>
                                    <option value="<?= $l['company_id'] ?>" <?php if ($l['company_id'] == $this->sepcloc['Company_ID']) echo 'selected' ?>><?= $l['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="oneTwo">
                            <label for="due_date">Tender Due Date</label>
                            <input id="due_date" type="text" name='due_date' class="datepicker" value='<?= $project['due_date']->format('Y-m-d') ?>' disabled />
                        </div>
                        <div class="oneTwo">
                            <label for="required_date">Material Required Date</label>
                            <input id="required_date" type="text" name='required_date' class="datepicker" value='<?= $project['required_date']->format('Y-m-d') ?>' disabled />
                        </div>
                        <div class="oneTwo">
                            <label for="gerneral_contractor">General Contractor</label>
                            <input type="text" placeholder="Type Name" name="gerneral_contractor" id="gerneral_contractor" value='<?= ($this->gerneral_contractor['name'] ?? '') . ' - ' . ($this->gerneral_contractor['company_id'] ?? '') ?>' />
                            <input type="hidden" id="gerneral_contractor_id" name='gerneral_contractor_id' value="<?= $project['general_contractor_id'] ?>">
                        </div>
                        <div class="oneTwo">
                            <label for="gerneral_contractor_loc">General Contractor Location</label>
                            <input type="text" id="gerneral_contractor_loc" name='gerneral_contractor_loc' value="<?= $this->gerneral_contractor['company_id'] ?? '-' ?>">
                        </div>
                        <div class="oneTwo">
                            <label for="awarded_contractor">Awarded Sub Contractor</label>
                            <input type="text" id="awarded_contractor" name='awarded_contractor' placeholder="Type Name" value='<?= ($this->awarded_sub_contracotr['name'] ?? '') . ' - ' . ($this->awarded_sub_contracotr['company_id'] ?? '') ?>' />
                            <input type="hidden" id="awarded_contractor_id" name='awarded_contractor_id' value="<?= $project['awarded_sub_contracotr_id'] ?>">
                        </div>
                        <div class="oneTwo">
                            <label for="awarded_contractor_loc">Awarded Contractor Location</label>
                            <input type="text" id="gerneral_contractor_loc" name='gerneral_contractor_loc' value="<?= $this->awarded_sub_contracotr['company_id'] ?? '-' ?>">
                        </div>
                    </div>
                </div>
            </form>
        </section>

        <section aria-labelledby="quoted-items" id="section2" data-nav="Quoted items">
            <form method="post" class="form" id='project_log'>
                <div class="widget-table">
                    <h2>Quoted items</h2>
                    <div class="title">
                        <?php if ($this->owner == 1) { ?><a href="#" title="" class="button greenB" style="margin: 5px;" id="add_item"><span>Add New</span></a><a href="#" title="" class="button redB" style="margin: 5px;display:none" id="save_item"><span>Save</span></a><?php } ?>
                    </div>
                    <table width="100%" class="sTable display nowrap" id="items">
                        <thead>
                            <tr>
                                <th>Item</th>
                                <th>Quality Quoted</th>
                                <th>Unit Price</th>
                                <th>Unit Of Measure</th>
                                <th>Price Quoted</th>
                                <th>Note</th>
                            </tr>
                        </thead>
                        <tbody id="item_body">
                            <?php foreach ($this->items as $i) { ?>
                                <tr name="item[<?= $i['product_id'] ?>]">
                                    <td><input type="checkbox" name="item[<?= $i['product_id'] ?>]"></td>
                                    <td><b><?= $i['product_id'] ?> - <?= $i['item_desc'] ?></b>
                                        <?php if ($i['note'] != null) { ?>
                                            <textarea rows="1" cols="" name="item[<?= $i['product_id'] ?>][note]"><?= $i['note'] ?></textarea>
                                        <?php } ?>
                                    </td>
                                    <td><?= $i['qty'] ?></td>
                                    <td><?= $i['unit_price'] ?></td>
                                    <td><?= $i['uom'] ?></td>
                                    <td><?= $i['subtotal'] ?></td>
                                    <input type="hidden" name="item[<?= $i['product_id'] ?>][qty]" value="<?= $i['qty'] ?>"><input type="hidden" name="item[<?= $i['product_id'] ?>][unit_price]" value="<?= $i['unit_price'] ?>">
                                    <input type="hidden" name="item[<?= $i['product_id'] ?>][uom]" value="<?= $i['uom'] ?>"><input type="hidden" name="item[<?= $i['product_id'] ?>][total_price]" value="<?= $i['subtotal'] ?>">
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </form>
        </section>

        <section aria-labelledby="project-log" id="section3" data-nav="Project log">
            <div class="widget-table">
                <h2>Project log</h2>
                <table cellpadding="0" cellspacing="0" width="100%" class="display" id='project_memo'>
                    <thead>
                        <tr>
                            <th data-priority="1">Log Date</th>
                            <th>Action Items Completed</th>
                            <th data-priority="2">Follow Up Date</th>
                            <th data-priority="3">Next Action Required</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>
    </div>
</main>

<script type="text/javascript">
    $('#options-button').on("click", function() {
        $('#options-menu-items').slideToggle({
            start: function() {
                $(this).css('display', 'flex');
            }
        });
    })

    $("textarea").each(function() {
        this.setAttribute("style", "height:" + (this.scrollHeight) + "px;overflow-y:hidden;");
    }).on("input", function() {
        this.style.height = 0;
        this.style.height = (this.scrollHeight) + "px";
    });

    $('input').attr('readonly', 'readonly');
    $('.selector').attr('diabled', 'diabled');

    let itemTable = $("#items").DataTable({
        ajax: {
            url: "/project/item/id/" + $('#project_id').val(),
            dataSrc: ''
        },
        processing: true,
        columns: [{
                data: "product_id",
                render: function(data, type, row, meta) {
                    return '<b class="item-name">' + data + '</b>' + '<br>' + row.item_desc;
                }
            },
            {
                data: "qty"
            },
            {
                data: "unit_price"
            },
            {
                data: "uom"
            },
            {
                data: "subtotal"
            },
            {
                data: "note"
            }
        ],
        columnDefs: [{
                targets: [0, 1, 2, 3, 4],
                className: 'dt-body-center'
            },
            {
                targets: [0, 1, 2, 3, 4, 5],
                className: 'dt-head-center'
            },
        ],
        layout: {
            topStart: null,
            topEnd: null
        },
        order: {
            data: "added.date"
        },
        paging: false,
        scrollX: true,
        fixedColumns: {
            start: 1
        }
    });

    $('#project_memo').DataTable({
        ajax: {
            url: "/project/memo/id/" + $('#project_id').val(),
            dataSrc: ''
        },
        processing: true,
        columns: [{
                data: "added.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleString();
                }
            },
            {
                data: "title",
                render: function(data, type, row, meta) {
                    if (row.content == null) {
                        return '<p><b>' + data + '</b></p>';
                    } else {
                        return '<p><b>' + data + '</b></br>' + row.content + '</p>';
                    }
                }
            },
            {
                data: "follow_up_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "type"
            }
        ],
        columnDefs: [{
            targets: [0, 2],
            className: 'dt-body-center'
        }],
        order: [
            [0, "desc"]
        ]
    });
</script>