<a href="/project/new" target="_blank" class='button quick-link add_pro' title="Add new project">
    <span class='icon icon-add'></span>
    Add Project
</a>
<a class='button quick-link' href="/project/<?= $id ?>/export" title="print">
    <span class='icon icon-pdf'></span>
    Print Project
</a>
<a class='button quick-link make-quote' title="Make quote">
    <span class='icon icon-dollar'></span>
    Make Quote
</a>
<a href="#" class='button quick-link delete_pro' title="delete">
    <span class='icon icon-trash'></span>
    Close Project
</a>
