  <!-- Title area -->
    <div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
                <h5>My Projects</h5>
                <span>Sales Manager Landing Page.</span>
            </div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="line"></div>
    
 
 <!-- Main content wrapper -->
    <div class="wrapper">
    
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
        <div class="widget" style="margin:50px auto; padding:50px;">
       		<h1><?=$this->error ?></h1>
       </div>   
    </div>
     