  <? $session =  Zend_Registry::get('session'); ?>
  <!-- Title area -->
    <div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
                <h5>Project To Quote WorkSheet</h5>
                <span>Track project data and events critical to close of sale.</span>
            </div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="line"></div>
    
<? $project = $this->project; ?>
 <!-- Main content wrapper -->
    <div class="wrapper">
    
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<li><a href="/project/" class='add_pro' title="add"><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Project</span></a></li>
                    <!--<li><a href="#" class='edit_pro' title="edit"><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>-->
                    <!--<li><a href="#" class='update_pro' title="update"><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>-->
                    <li><a href="#" class='save_pro' title="save"><img src="/images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/project/print/id/".$project['project_id']."?company=".substr($project['quote_no'],0,3)."&name=Centura_Project_".preg_replace("![^a-z0-9]+!i", "_", $project['project_name']).'.pdf'?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Project</span></a></li>
                    <li><a href="#" class='delete_pro' title="delete"><img src="/images/icons/control/32/delete.png" alt="" /><span>Close Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
        <!-- Form -->

                <div class="widget">
                	<form  method="post" class="form" id='project_content'> 
        					<input type="hidden" id='project_id' value='<?=$project['project_id'] ?>' >
                    <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
                      <h6>Project Information</h6></div>
                     <div class="formRow"> 
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Project Name</span><input type="text" id='project_name' class="validate[required]" placeholder="Project Name" name='project_name' value="<?=$project['project_name'] ?>" /></span>
                            <span class="oneFour"><span class="formNote">Centura Location</span><select name="location" id="location" style="width:300px;" >
                            	<? foreach ($this->locations as $l) {?>
                                <option value="<?=$l['location_id']?>" <? if($l['location_id'] == $project['centura_location_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <? } ?>
                            </select></span>
                            
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Worksheet Owner</span><input type="text"  value='<?=$project['owner_name'] ?>' readonly/></span>
                            <input type="hidden" name='owner' value='<?= $project['owner'] ?>' >
                            <span class="oneFour"><span class="formNote">Project#</span><input type="text" placeholder="123456" name='quote_no' value="<?=$project['quote_no'] ?>" readonly/></span>
                            <input name='create_date' type="hidden" value='<?=$project['create_date']->format('Y-m-d') ?>' />
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Project Location</span><input type="text" name='project_location_address' id="project_location_address" class="validate[required]"  value='<?= $project['project_location_address'] ?>'/></span>
                            <span class="oneFour"><span class="formNote">Status:</span><select name="status" id='status'  class="validate[required]" >
                                <option value="" >Select Status</option>
                                <? foreach($this->status as $s) {?>
                                <option value="<?=$s['uid']?>" <? if($s['uid'] == $project['status']) echo 'selected'?> ><?=$s['Status'] ?></option>
                                <? }?>
                               
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">REED#</span><input type="text"  name='reed' id='reed' value="<?= $project['reed'] ?>"  class="validate[required]" /></span>
                            <span class="oneFour"><span class="formNote">Market Segment:</span><select name="market_segment" id='market_segment' class="validate[required]" >
                                <option value="">Choose Segment</option>
                                <? foreach($this->seg as $s) {?>
                                <option value="<?=$s['uid']?>" <? if($s['uid'] == $project['market_segment']) echo 'selected'?>><?=$s['Market_Segment'] ?></option>
                                <? }?>
                               
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Project Architect/Owner<span class="req">*</span></span>
                            		<input type='text' name="architect_name" id='architect_name'  class="validate[required] tipN" original-title="Type 2 letter to start or add your own"   value='<?=$this->arch_name ?>' />
                                <input type="hidden" name='architect' id='architect' value="<?=$project['architect'] ?>">
                            </span>
                             <span class="oneFour"><span class="formNote">Architect Location</span><select id="architect_loc" >
                            	<? foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <? if($l['company_id'] == $this->architect['Company_ID']) echo 'selected'?> ><?=$l['name']?></option>
                               <? } ?>
                            </select></span>
                           
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	 <span class="oneTwo"><span class="formNote">Specifier<span class="req">*</span></span>
                        	 	<input type='text'  id='specifiler_name' name="specifiler_name" value='<?=$this->spec_name ?>' class="validate[required] tipN" original-title="Type 2 letter to start or add your own" > 
                            <input type="hidden" id='specifiler' name="specifiler" value="<?=$project['specifiler'] ?>"> 
                            </span>
                            <span class="oneFour"><span class="formNote">Specifier Location</span><select id="specifiler_loc" >
                            	<? foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <? if($l['company_id'] == $this->sepcloc['Company_ID']) echo 'selected'?> ><?=$l['name']?></option>
                               <? } ?>
                            </select></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">Tender Due Date:</span><input type="text" name='due_date' class="datepicker" value='<?=$project['due_date']->format('Y-m-d') ?>'/></span>
                            <span class="oneFour"><span class="formNote">Required Date:</span><input type="text" name='required_date'  class="datepicker" value='<?=$project['required_date']->format('Y-m-d') ?>'/></span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneTwo"><span class="formNote">General Contractor</span><input type="text"  placeholder="Type Name"  id="gerneral_contractor"  value='<?= $this->gerneral_contractor['name'].' - '.$this->gerneral_contractor['company_id']?>'/></span>
                            <span class="oneFour"><span class="formNote">General Contractor Location</span><select id="gerneral_contractor_loc"  style="width:300px;">
                            	<? if($this->gerneral_contractor['company_id'] == null) $this->gerneral_contractor['company_id']=DEFAULT_COMPNAY; ?>
                            	<? foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <? if($l['company_id'] == $this->gerneral_contractor['company_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <? } ?>
                            </select></span>
                            <input type="hidden" name='gerneral_contractor' value="<?= $project['general_contractor_id'] ?>">
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	<span class="oneTwo"><span class="formNote">Awarded Sub Contractor:</span><input type="text" placeholder="Type Name" id="awarded_contractor" value='<?= $this->awarded_sub_contracotr['name'].' - '.$this->awarded_sub_contracotr['company_id']?>' /></span>
                            <span class="oneFour"><span class="formNote">Awarded Contractor Location</span><select id="awarded_contractor_loc" >
                            	<? if($this->awarded_sub_contracotr['company_id'] == null) $this->awarded_sub_contracotr['company_id']=DEFAULT_COMPNAY; ?>
                            	<? foreach ($this->locations as $l) {?>
                                <option value="<?=$l['company_id']?>" <? if($l['company_id'] == $this->awarded_sub_contracotr['company_id']) echo 'selected'?> ><?=$l['name']?></option>
                               <? } ?>
                            </select></span>
                            <input type="hidden" name='awarded_contractor' value="<?= $project['awarded_sub_contracotr_id'] ?>">
                        </div>
                        <div class="clear"></div>
              </div>
        </form> 
       <form  method="post" class="form" id='project_log'> 
        <div class="widget">
        <div class="title"><span class="titleIcon"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Product Presented / For Quotation</h6><? if($this->owner == 1) {?><a href="#" title="" class="button greenB" style="margin: 5px;" id="add_item"><span>Add New</span></a><a href="#" title="" class="button redB" style="margin: 5px;display:none" id="save_item" ><span>Save</span></a><? }?></div>
        <div class="clear"></div>
           <table cellpadding="0" cellspacing="0" width="100%" class="sTable" id="items" style="text-align:center;">
              <thead>
                  <tr>
                      <td></td>
                      <td width="60%">Item ID - Description</td>
                      <td>Quality Quoted</td>
                      <td>Unit Price</td>
                      <td>Unit Of Measure</td>
                      <td>Price Quoted</td>
                      <td>Action</td>
                  </tr>
              </thead>
              <tbody id="item_body">
                 <? foreach ($this->items as $i) { ?>
                 		<tr name="item[<?=$i['product_id']?>]"><td><input type="checkbox" name="item[<?=$i['product_id']?>]"></td>
                 			<td><?=$i['product_id']?> - <?=$i['item_desc'] ?>
                 				<textarea readonly rows="1" cols="" name="item[<?=$i['product_id']?>][note]"><?=$i['note']?></textarea>
                 		  </td>
                 		  <td><?=$i['qty']?></td>
                 		  <td><?=$i['unit_price']?></td>
                 		  <td><?=$i['uom']?></td>
                 		  <td><?=$i['subtotal']?></td>
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][qty]" value="<?=$i['qty']?>"><input type="hidden" name="item[<?=$i['product_id']?>][unit_price]" value="<?=$i['unit_price']?>">
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][uom]" value="<?=$i['uom']?>"><input type="hidden" name="item[<?=$i['product_id']?>][total_price]" value="<?=$i['subtotal']?>">
	                 		  <td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="item_delete" href="#" index='<?=$i['product_id']?>'><img src="/images/icons/dark/close.png" alt="delete"></a></td>
                 		  
                 		</tr>
                 <? }?>
              </tbody>
          </table>
        </div>
			</form>
        
        <div class="widget">
          <div class="title"><img src="/images/icons/dark/frames.png" alt="" class="titleIcon"><h6>Project Log</h6><? if($this->owner == 1) {?><a href="#" title="" class="button greenB" style="margin: 5px;" id="opener"><span>Add Action</span></a><? }?></div>
            <table cellpadding="0" cellspacing="0" width="100%" class="display" id='project_memo'>
                <thead>
                    <tr>
                        <td class="sortCol">Log Date</td>
                        <td class="sortCol" style='width:60%'>Action Items Completed</td>
                        <td class="sortCol">Follow Up Date</td>
                        <td class="sortCol">Next Action Required</td>
                        <td class="sortCol action"><div> </div></td>
                    </tr>
                </thead>
                <tbody>
                	 <? foreach($this->memo as $l) {?>
                    <tr>
                        <td><?=$l['added']->format('Y-m-d'); ?></td>
                         <td><?=$l['title']; ?></td>
                        <td><?=$l['follow_up_date'] != null ? $l['follow_up_date']->format('Y-m-d') : ''; ?></td>
                        <td><?=$l['type']; ?></td>
                        <td><? if($this->owner == 1) {?><a href="/memo/delete/id/<?=$l['memo_id']; ?>" class='memo_delete'><img src="/images/icons/dark/close.png" alt="delete"></a><?}?></td>
                    </tr>
                    <? } ?>
                </tbody>
            </table>
        </div>     
    </div>
 </div>
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<li><a href="/project/" class='add_pro' title="add"><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Project</span></a></li>
                    <!--<li><a href="#" class='edit_pro' title="edit"><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>-->
                    <!--<li><a href="#" class='update_pro' title="update"><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>-->
                    <li><a href="#" class='save_pro' title="save"><img src="/images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="<?='http://'.SITEURL."/dompdf/print.php?url=".'http://'.SITEURL."/project/print/id/".$project['project_id']."?company=".substr($project['quote_no'],0,3)."&name=Centura_Project_".preg_replace("![^a-z0-9]+!i", "_", $project['project_name']).'.pdf'?>" title="print"><img src="/images/icons/control/32/pdf.png" alt="" /><span>Print Project</span></a></li>
                    <li><a href="#" class='delete_pro' title="delete"><img src="/images/icons/control/32/delete.png" alt="" /><span>Close Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    
       
   <div id="dialog-message" title="Add log -- Auto Save" >
        <div class="uiForm">
            <form action="" class="dialog" id='memo'>
            		<p style='text-align:left'>Enter Action Items Completed </p>
                <input type="text" name='title' id='title' class="validate[required]">
                <p style='text-align:left'>Enter Next Action Required </p>
                <input type="text" name="type" id='type' class="validate[required]"  value=''  placeholder="Critical Updates Note">
                <div class="clear"></div>
                <p style='text-align:left'>Follow Up Date: </p>
                <input type="text" name='follow_up_date' id='follow_up_date' class="datepicker" value='<?=$project['due_date']->format('Y-m-d') ?>' style='margin-left:10px;'/>
            </form>
        </div>
   </div>
   
    <div id="dialog-item" title="Add Item">
        <div class="uiForm">
            <form action="" class="dialog" id='item'>
            		<span class="formNote">Enter Item ID </span>
                <input type="text" name="item" id='item_input' class="validate[required]" />
                <input type="hidden" id="item_id" name='item_id'/>
                <span class="formNote">UOM</span>
                <select name="uom" id='uom' class="validate[required]" >
                      <option value=''>Select UOM</option>
                </select>
                <div class="clear"></div>
                <span class="formNote">Price ($)</span>
                <input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price"/>
                <span class="formNote">Qty</span>
                <input type="text" name="qty" id='qty' class="validate[required,custom[number]]"  />
                <span class="formNote">Note</span>
                <textarea name='note' id='note' class="validate[maxSize[255]]" ></textarea>
                <input type="hidden" id="is_edit" value='0'/>
            </form>
        </div>
   </div>
   
   <style>
   	div.selector { width: 290px;}
div.selector select { width: 300px; }
div.selector span { width: 290px;  }
<? if($this->owner == 1) {?>
	
<? }?>
   	</style>
   	
<script type="text/javascript" >
		function resetForm($form) {
    $form.find('input:text, input:password, input:file, select, textarea').val('');
    $form.find('input:radio, input:checkbox')
         .removeAttr('checked').removeAttr('selected');
	}
	var item_dirty  = 0;
	var current_edit_row = '';
		$(function() {
	  function getcustomerbyid(id,obj)
		{
			$('.loading').show();
			$.ajax({
			  url: '/customer/fetchbyid/id/'+id,
			  type: "get",
			  success: function(data) {
			  	 var result = jQuery.parseJSON(data);
			  	 if(result != null)
			  	 {
			  		$(obj).val(result.name);
			  		$('input[name='+ $(obj).attr('id')+']').val(result.customer_id);			  		
			  	}
			  	else
			  		{
			  			alert('Can\'t find customer');
			  			$('#customer_info input').val('');
			  		}
			  	$('.loading').hide();
			  }
				});
			}
			
		$( "#awarded_contractor" ).autocomplete({
			source: function(request, response) {
          $.ajax({
            url: '/customer/fetchbynamecompany/',
            dataType: "json",
            data: {
              term : request.term,
              company : $('#awarded_contractor_loc').val()
            },
            success: function(data) {
              response(data);
            }
          });
      },
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id,$('#awarded_contractor'));
			},
			
			}).data( "autocomplete" )._renderItem = function( ul, item ) {
				return $( "<li></li>" )
					.data( "item.autocomplete", item )
					.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
					.appendTo( ul );
			};
		$( "#gerneral_contractor" ).autocomplete({
			source: function(request, response) {
          $.ajax({
            url: '/customer/fetchbynamecompany/',
            dataType: "json",
            data: {
              term : request.term,
              company : $('#gerneral_contractor_loc').val()
            },
            success: function(data) {
              response(data);
            }
          });
      },
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id,$('#gerneral_contractor'));
			},
			
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
				.appendTo( ul );
		};
		$('#architect_loc').change(function(){
			$('.loading').show();
			$.ajax({
			  url: '/sales/fetchbylocation/loc/'+$(this).val(),
			  type: "get",
			  success: function(data) {
			  	  var result = jQuery.parseJSON(data);
			  	  var list = '<option >Select Architect / Owner</option>';
		    		$.each(result, function(i, item) {
		     		  list = list + '<option value="'+item.id+'">'+item.name + ' - ' + item.default_company +'</option>';
		     		});
		     		$('#architect').html(list);
			  	 $('.loading').hide();
			 	 }
				});
        $('.loading').show();
  	});
  	$('#specifiler_loc').change(function(){
  		$('.loading').show();
  			$.ajax({
			  url: '/sales/fetchspecbylocation/loc/'+$(this).val(),
			  type: "get",
			  success: function(data) {
			  	  var result = jQuery.parseJSON(data);
			  	  var list = '<option >Choose Specifiler</option>';
			  	  if( result.length == 0)
			  	  {
			  	  	$('#specifiler').html(list);
			  	  }
			  	  else
			  	  {
			    		$.each(result, function(i, item) {
			     		  list = list + '<option value="'+item.uid+'">'+item.Specifier + ' - ' + item.Company_ID +'</option>';
			     		});
			     		$('#specifiler').html(list);
		     		}
			  	 $('.loading').hide();
			 	 }
				});
  	});
  	$( "#architect_name" ).autocomplete({
			source: function(request, response) {
					$('#architect').val('');
          $.ajax({
            url: '/sales/fetchspec/',
            dataType: "json",
            data: {
              term : request.term,
              loc : $('#architect_loc').val()
            },
            success: function(data) {
              response(data);
            }
          });
      },
			minLength: 2,
			select: function( event, ul ) {
  	  	$("#architect_name").val(ul.item.Specifier);
				$('#architect').val(ul.item.uid);
				return false;
			},
			
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>"  + item.Specifier+"</a>" )
				.appendTo( ul );
		};
		
		$( "#specifiler_name" ).autocomplete({
			source: function(request, response) {
          $.ajax({
            url: '/sales/fetchspec/',
            dataType: "json",
            data: {
              term : request.term,
              loc : $('#specifiler_loc').val()
            },
            success: function(data) {
              response(data);
            }
          });
      },
			minLength: 2,
			select: function( event, ul ) {
  	  	$("#specifiler_name").val(ul.item.Specifier);
				$('#specifiler').val(ul.item.uid);
				return false;
			},
			
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>"  + item.Specifier+"</a>" )
				.appendTo( ul );
		};
  	
  	$('.save_pro').click(function(e){
  			e.preventDefault();
				if($("#project_content").validationEngine('validate') ==true)
				{
					if($('#status').val() != 13)
  				{
						$('.loading').show();
		  			$('#project_content').submit();
	  			}
	  			else
	  				{
	  					 if(confirm("You are trying to close a project. Please add the reason to the log.") == true)
	  					 {
	  					 	$('.loading').show();
		  					$('#project_content').submit();
	  					}
	  				}
	  		}
  		
  	});
  	
  	$('.delete_pro').click(function(){
  		 if(confirm("You are trying to close a project. Please add the reason to the log.") == true)
	  	 {
  			$('.loading').show();
  			$.ajax({
			  url: '/project/delete/id/'+$('#project_id').val(),
			  type: "get",
			  success: function(data) {
			  	 $('.loading').hide();
			  	 
			  	 window.location='/';
			 	 }
				});
			}
  	});
  	
  $('#project_memo').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",
		"sDom": '<""l>t<"F"fp>',
		"aaSorting": [[ 0, "desc" ]]
	});
	
		
  $( "#dialog-message" ).dialog({
				autoOpen: false,
				modal: true,
				minWidth: 600,
				buttons: 
					[{
	        id:"btn-add",
	        text: "Add Log",
	        click: function() {
	           	if($("#memo").validationEngine('validate') ==true)
							{
								addmemo();
								$( this ).dialog( "close" );
							}
	        	}
			    }, 
			    {
			        id:"btn-cancel",
			        text: "Cancel",
			        click: function() {
			            $(this).dialog("close");
			        }
			    }]
					
				
		});
		$( "#add_item" ).click(function() {
		$( "#dialog-item" ).dialog( "open" );
		return false;
	});
		$( "#dialog-item" ).dialog({
				autoOpen: false,
				modal: true,
				minWidth: 500,
				buttons: 
					[{
	        id:"btn-add",
	        text: "Add",
	        click: function() {
	           	if($("#item").validationEngine('validate') ==true)
							{
								if($('#is_edit').val() == 1)
								{
									edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val() ,$('#note').val());
								}
								else
								{
									additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val() ,$('#note').val());
								}
								$( this ).dialog( "close" );
								resetForm($('#item'));
							}
	        	}
			    }, 
			    {
			        id:"btn-cancel",
			        text: "Cancel",
			        click: function() {
			            $(this).dialog("close");
			        }
			    }]
					
				
		});
		
			$('#add_item').click(function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});	

		$(document).on("click", "a.edit",function() {
			$( "#dialog-item" ).dialog( "open" );
			current_edit_row =$(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});	
		
		function set_edit(row)
		{
			$( "#dialog-item" ).dialog( "option", "title", "Edit Item" );
			$('#is_edit').val(1);
			var item_id = $(row).attr('name').substr(5, ($(row).attr('name').length - 6));
			var item_name = jQuery.trim($(row).find('td').eq(1).clone().children().remove().end().text()).replace(item_id+' - ','');
			var note = $(row).find('textarea').eq(0).val();
			var qty = $(row).find(':input:hidden').eq(0).val();
			var unit_price = $(row).find(':input:hidden').eq(1).val();
			var uom = $(row).find(':input:hidden').eq(2).val();
			var total_price = $(row).find(':input:hidden').eq(3).val();
			
			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);

			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);
			
			getoumedit(item_id,uom,unit_price);

		}
		
	function getoumedit(item_id,unit_number,price)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option[value='+unit_number+']').attr('selected','selected');
		     	$('#uniform-uom span').html(unit_number);
		     	$('#price').val(price);
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function edititem(item_id,item_desc,uom,price,qty,note)
	{
		var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea readonly rows="1" cols="" name="item['+item_id+'][note][]">'+note+'</textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty][]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price][]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom][]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price][]" value="'+total_price+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="item_delete" href="#" index="'+item_id+'"><img src="/images/icons/dark/close.png" alt="delete"></a></td>';
		ajaxedititem(item_id,uom,price,qty,note);
		current_edit_row.replaceWith(str);
		
	}
	
	function getolddata(row)
	{
			var item_id = $(row).attr('name').substr(5, ($(row).attr('name').length - 6));
			//var item_name = jQuery.trim($(row).find('td').eq(1).clone().children().remove().end().text()).replace(item_id+' - ','');
			var note = $(row).find('textarea').eq(0).val();
			var qty = $(row).find(':input:hidden').eq(0).val();
			var unit_price = $(row).find(':input:hidden').eq(1).val();
			var uom = $(row).find(':input:hidden').eq(2).val();
		//	var total_price = $(row).find(':input:hidden').eq(3).val();
		var data ={'old_item_id':item_id,'old_uom':uom,'old_price':unit_price,'old_qty':qty,'old_note':note};
		return data;
	}
	
	function ajaxedititem(item_id,uom,price,qty,note)
	{
		var olddata = getolddata(current_edit_row);
		var data ={'item_id':item_id,'uom':uom,'price':price,'qty':qty,'note':note,'old_item_id':olddata['old_item_id'],'old_uom':olddata['old_uom'],'old_price':olddata['old_price'],'old_qty':olddata['old_qty'],'old_note':olddata['old_note']};

		$('.loading').show();
  			$.ajax({
			  url: '/project/edititem/pro/'+$('#project_id').val(),
			  type: "post",
			  data: data,
			  success: function(data) {
			  	 $('.loading').hide();
			  	 	resetForm($('#item'));
					 }
				});
	}	
		 $( ".dialog #item_input" ).autocomplete({
				source: '/item/index/',
				minLength: 2,
				focus: function( event, ui ) {
							$( "#item_input" ).val( ui.item.item_desc );
							return false;
					},
				select: function( event, ui ) {
					$( "#item_input" ).val( ui.item.item_desc );
					$( "#item_id ").val( ui.item.item_id );
					getoum(ui.item.item_id );
					$('#uom').removeAttr('disabled');
					$('#uniform-uom').removeClass('disabled');
					 return false; 
					}
				}).data( "autocomplete" )._renderItem = function( ul, item ) {
						return $( "<li></li>" )
							.data( "item.autocomplete", item )
							.append( "<a>" + item.item_id + "<br>" + item.item_desc + "</a>" )
							.appendTo( ul );
	};
	 $(".dialog #item_input").bind('paste', function(e) {
            alert('paste');
       			 $( ".dialog #item_input" ).select();
 	 });
	function getoum(item_id)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option').eq(0).attr("selected", "selected"); 
		     	$('#uniform-uom span').html(uom[0].uom);
		     	getprice();
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function getprice()
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/price/id/'+$( "#item_id ").val()+'/uom/'+$( "#uom ").val(),
		  type: "get",
		  success: function(data) {
		  	 var price = jQuery.parseJSON(data);
		  		$('#price').val(price.price);
		  		$('.loading').hide();
		  }
		});
		
	}
	
	function additem(item_id,item_desc,uom,price,qty,note)
	{
		var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea rows="1" cols="" name="item['+item_id+'][note]" readonly>'+note+'</textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price]" value="'+total_price+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="item_delete" href="#" index="'+item_id+'"><img src="/images/icons/dark/close.png" alt="delete"></a>';
		saveitem();
		$('#item_body').append(str);
	}
	function saveitem()
	{
		$('.loading').show();
  			$.ajax({
			  url: '/project/additem/pro/'+$('#project_id').val(),
			  type: "post",
			  data: $("#item").serialize(),
			  success: function(data) {
			  	 $('.loading').hide();
			  	 	resetForm($('#item'));
					 }
				});
	}
	
	$("#uom,#uniform-uom").change(function(){
        getprice();
        return false;
  	});
  $("#item_body .item_delete").live('click',function(e){
  		e.preventDefault();
  		var data =getolddata($(this).closest('tr'));
       $(this).parent().parent().remove();
       $('.loading').show();
  			$.ajax({
			  url: '/project/deleteitem/pro/'+$('#project_id').val()+'/item/'+$(this).attr('index') +'/uom/'+data['old_uom']+'/price/'+data['old_price'] + '/qty/'+data['old_qty'],
			  type: "get",
			  success: function(data) {
			  	 $('.loading').hide();
					 }
				});
  });
		
		function addmemo()
		{
			$('.loading').show();
  			$.ajax({
			  url: '/memo/add/pro/'+$('#project_id').val(),
			  type: "post",
			  data: $("#memo").serialize(),
			  success: function(data) {
			  	 $('.loading').hide();
			  	 if(data > 0){
				  	 $('#project_memo').dataTable().fnAddData( [
						    '<?=date('Y-m-d')?>',
						    $("#memo #title").val(),
						    $("#memo #follow_up_date").val(),
						     '<span class="memo_type mono_type'  + '">' + $("#memo #type").val() + '</span>' ,
						    '<a href="/memo/delete/id/'+data +'" class="memo_delete"><img src="/images/icons/dark/close.png" alt="delete"></a>'
						  ] );
				 	 	}
				 	 	resetForm($('#memo'));
					 }
				});
		}
		$('.memo_delete').live('click',function(e){
			e.preventDefault();
			var obj = $(this);
  		if(confirm("Confirm delete This Log?") == true)
  		{
  			$('.loading').show();
  			$.ajax({
			  url: $(this).attr('href'),
			  type: "get",
			  success: function(data) {
			  	var index = $('#project_memo tbody tr').index(obj.parent().parent());
			  	if(index != -1)
			  	{
			 		 	$('#project_memo').dataTable().fnDeleteRow( index);
					}
			  	 $('.loading').hide();
			 	 }
				});
			}
  	});
  		});
		
	</script>
  <style>
  	#memo .ui-datepicker-append {display:none;}
  	</style>