<?php
$session =  Zend_Registry::get('session');
$project = $this->project;
$quote = $this->quote;
$quoteID = $quote['quote_id'];
$customer = $this->customer;

$approved = 10;
$waitingApprove = 1;
$disapproved = -1;
?>

<!-- Title area -->
<main id="content" class="main-content">
	<div class="main-page-content">
		<header class="main-page-content-header">
			<div class="options-menu">
				<button class="quick-link options-button" id="options-button" type="button">
					<span class='icon icon-menu'></span>
					Options
				</button>

				<!-- Right panel -->
				<div class="sidebar-container" id="options-menu-items">
					<a href="/quote/index/project/<?= $project['project_id'] ?>" class="button quick-link" title="">
						<span class='icon icon-add'></span>
						Add new quote</a>
					<!--<li><a href="#" title=""><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Current</span></a></li>
                    <li><a href="#" title=""><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Quote</span></a></li>-->
					<a class="button quick-link" href="<?= 'http://' . SITEURL . "/dompdf/print.php?url=" . 'http://' . SITEURL . "/quote/print/id/" . $quoteID . "?company=" . substr($quote['quote_no'], 0, 3) . "&name=Centura_Quote_" . $quoteID . '.pdf' ?>" title="Print this quote">
						<span class='icon icon-pdf'></span>
						Print Quote</a>
					<a class="button quick-link" target="_blank" href="/project/edit/id/<?= $project['project_id'] ?>" title="Go to project for this quote">
						<span class='icon icon-external'></span>
						Go to Project</a>
					<?php if ($session->user['approve_id'] != null and $quote['status'] != 0 and $quote['approve_status'] != 0) { ?>
						<a class='button quick-link' target="_blank" href="/approve/index/id/<?= $quoteID ?>" title="Go to this quote approval">
							<span class='icon icon-external'></span>
							Go to Approval</a>
						<?php }
					switch ($quote['approve_status']) {
						case $approved: ?>
							<a class="button quick-link" href="/mail/quote/id/<?= $quoteID ?>" title="mail">
								<span class='icon icon-mail'></span>
								Mail Quote</a>
							<a href="/quote/ready/id/<?= $quoteID ?>" title="" class='button quick-link quote-edit-again'>
								<span class='icon icon-edit'></span>
								Edit Again</a>
						<?php break;

						case $waitingApprove: ?>
							<a href="/quote/unsubmit/id/<?= $quoteID ?>" title="" class='button quick-link undo-submit'>
								<span class='icon icon-undo'></span>
								Undo Submit</a>
							<?php break;

						default:
							if ($quote['status'] != 0) { ?>
								<a href="/quote/ready/id/<?= $quoteID ?>" title="" class='button quick-link ready_quote'>
									<span class='icon icon-approval'></span>
									Submit Approval</a>
						<?php }
							break;
					}
					if ($quote['status'] != 0 and $quote['approve_status'] != $approved) { ?>
						<a href="" title="" class='button quick-link delete_quote'>
							<span class='icon icon-trash'></span>
							Delete Quote</a>
					<?php } ?>
				</div>
			</div>

			<h1>Edit Quote</h1>
		</header>

		<!-- Main content wrapper -->
		<div class="widget-information">
			<div class="widget-table dashboard">
				<div class="project-information project-name">
					<h2><?= $project['project_name'] ?? '' ?></h2>
					<p><?= ($project['project_location_address'] == 'N/A') ? '' : $project['project_location_address'] ?></p>
					</br>
					<p>by <b><?= $project['owner'] ?? '' ?></b></p>
					<?php if (($project['worksheet_assign']) != null) { ?>
						<p>shared with <b><?= $project['worksheet_assign'] ?></b></p>
					<?php } ?>
				</div>
				<span class='svg icon icon-list'></span>
			</div>

			<div class="widget-table dashboard">
				<div class="project-information">
					<p>Quote number</p>
					<h2><?= $project['quote_no'] ?? '' ?></h2>
				</div>
				<span class='svg icon icon-number'></span>
			</div>

			<div class="widget-table dashboard">
				<div class="project-information">
					<p>Project status</p>
					<h2><?= $project['status_name'] ?? '' ?></h2>
				</div>
				<span class='svg icon icon-money-1'></span>
			</div>

			<div class="widget-table dashboard">
				<div class="project-information">
					<p>Due date</p>
					<h2><?php if (!empty($project['due_date'])) {
							echo $project['due_date']->format('Y-m-d');
						} ?></h2>
				</div>
				<span class='svg icon icon-calender'></span>
			</div>

			<?php
			if ($quote['status'] != 0) {
				switch ($quote['approve_status']) {
					case $approved: ?>
						<div class="widget-table dashboard quote-status status-approved">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Approved</h2>
							</div>
							<span class='svg icon icon-checkmark-circle'></span>
						</div>
					<?php break;

					case $waitingApprove: ?>
						<div class="widget-table dashboard quote-status status-waiting">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Waiting for approval</h2>
							</div>
							<span class='svg icon icon-information-circle'></span>
						</div>
					<?php break;

					case $disapproved: ?>
						<div class="widget-table dashboard quote-status status-disapproved">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Disapproved</h2>
							</div>
							<span class='svg icon icon-cancel-circle'></span>
						</div>
					<?php break;

					default: ?>
						<div class="widget-table dashboard quote-status status-notsubmitted">
							<div class="project-information">
								<p>Quote status</p>
								<h2>Not submitted</h2>
							</div>
							<span class='svg icon icon-cancel-circle'></span>
						</div>
				<?php break;
				}
			} else {  ?>
				<div class="widget-table dashboard quote-status status-disapproved">
					<div class="project-information">
						<p>Quote status</p>
						<h2>Deleted</h2>
					</div>
					<span class='svg icon icon-cancel-circle'></span>
				</div>
			<?php } ?>
		</div>

		<!-- Form -->
		<form method='post' class="form" id="quote_content">
			<div class="widget-table" id="customer_info">
				<div class="widget-button">
					<?php if ($quote['approve_status'] != $approved) { ?>
						<button type="button" class="button action has-icon new-customer small" id="add_new_mode">
							<span class="button-wrap">
								<span class="icon icon-add"></span>
								New Customer
							</span>
						</button>
						<button type="button" class="button action has-icon discard-customer small basic" style='display:none;' id="discard_new_mode">
							<span class="button-wrap">
								<span class="icon icon-undo"></span>
								Discard Adding
							</span>
						</button>
					<?php } ?>
				</div>
				<h2>Customer infomation</h2>
				<div class="formRow">
					<div class="oneTwo required-field">
						<label for="quote">Quote To</label>
						<input readonly id='quote' name='name' type="text" value="<?= $customer['name'] ?>" />
					</div>

					<div class="oneTwo">
						<label for="customer_id">Customer ID</label>
						<input readonly type="text" name='customer_id' id='customer_id' class="validate[custom[integer]]" value="<?= $customer['customer_id'] ?>" placeholder="Leave blank to add new customer or contact" />
					</div>

					<div class="oneTwo">
						<label for="company_id">Company ID</label>
						<input readonly type="text" name='company_id' id='company_id' value="<?= $customer['company_id'] ?>" />
					</div>

					<div class="oneTwo">
						<label for="first_name">First Name</label>
						<input readonly id='first_name' name='first_name' type="text" value="<?= $customer['first_name'] ?>">
					</div>

					<div class="oneTwo">
						<label for="last_name">Last Name</label>
						<input readonly id='last_name' name='last_name' type="text" value="<?= $customer['last_name'] ?>">
					</div>

					<div class="oneTwo required-field">
						<label for="address">Address 1</label>
						<input readonly id='address' name='phys_address1' type="text" value="<?= $customer['phys_address1'] ?>" />
					</div>

					<div class="oneTwo">
						<label for="phys_address2">Address 2</label>
						<input readonly id='phys_address2' name='phys_address2' type="text" value="<?= $customer['phys_address2'] ?>">
					</div>

					<div class="oneTwo">
						<label for="phys_city">City</label>
						<input readonly id='phys_city' name='phys_city' type="text" value="<?= $customer['phys_city'] ?>">
					</div>

					<div class="oneTwo">
						<label for="mail_state">Province</label>
						<input readonly id='mail_state' name='mail_state' type="text" value="<?= $customer['mail_state'] ?>">
					</div>

					<div class="oneTwo">
						<label for="mail_postal_code">Postal Code</label>
						<input readonly id='mail_postal_code' name='mail_postal_code' type="text" value="<?= $customer['mail_postal_code'] ?>">
					</div>

					<div class="oneTwo">
						<label for="phys_country">Country</label>
						<input readonly id='phys_country' name='phys_country' type="text" value="<?= $customer['phys_country'] ?>">
					</div>

					<div class="oneTwo required-field">
						<label for="tel">Phone Number</label>
						<input readonly id='tel' name='phone' type="text" class="maskPhoneExt" value="<?= $customer['tel'] ?>" />
					</div>

					<div class="oneTwo required-field">
						<label for="contact">Contact</label>
						<input readonly type="text" id='contact' name='fullname' value="<?= $customer['fullname'] ?>" class="validate[required]" placeholder="Enter Customer Name to fetch existing customer" />
					</div>
					<div class="oneTwo required-field">
						<label for="customer_email">Email</label>
						<input readonly type="text" value="<?= $customer['email'] ?>" id='customer_email' name='Contacts_email' class="validate[custom[email]]" placeholder="Enter Customer Email to fetch existing customer">
					</div>

					<div class="oneTwo">
						<label for='sale_rep'>Sales Representative</label>
						<input id='sale_rep' name='sale_rep' type="text" value="<?= $customer['sale_rep'] ?>" readonly />
					</div>
				</div>

				<div class="line"></div>

				<h2>Quote infomation</h2>
				<div class="formRow">
					<input type="hidden" id='project_id' name='project_id' value="<?= $project['project_id'] ?>" />
					<input type="hidden" id='lead_time' name='lead_time' value="<?= $quote['lead_time'] ?>" />
					<input type="hidden" id='credit_term' name='credit_term' value="<?= $quote['term'] ?>" />
					<div class="oneTwo">
						<label for='quote_id'>Quote Number</label>
						<input id='quote_id' type="text" value='<?= $quoteID ?>' readonly />
					</div>
					<div class="oneTwo">
						<label for='quote_type'>Quote Type</label>
						<select name="quote_type_id" id='quote_type' class="validate[required]">
							<option value="">Select Quote type</option>
							<?php foreach ($this->type as $t) { ?>
								<option value="<?= $t['uid'] ?>" <?php if ($t['uid'] == $quote['quote_type_id']) echo 'selected'; ?>><?= $t['type'] ?></option>
							<?php } ?>
						</select>
					</div>

					<div class=" oneTwo required-field">
						<label for='Segment'>Quote Segment</label>

						<select name="quote_segment" id='Segment' class="validate[required]">
							<option value="">Choose Segment</option>
							<?php foreach ($this->seg as $s) { ?>
								<option value="<?= $s['uid'] ?>" <?php if ($s['uid'] == $quote['quote_segment']) echo 'selected' ?>><?= $s['Market_Segment'] ?></option>
							<?php } ?>
						</select>
					</div>

					<div class="oneTwo">
						<label for='ship_required_date'>Ship Required Date</label>
						<input id='ship_required_date' type="text" class="datepicker" name='ship_required_date' value="<?php if ($quote['ship_required_date'] != null && $quote['ship_required_date']->format('Y-d-m') > '2000-01-01') {
																															echo $quote['ship_required_date']->format('Y-m-d');
																														} ?>" />
					</div>
					<div class="oneTwo">
						<label for="quote_date">Quote Expire Date</label>
						<input id="expire_date" name="expire_date" type="text" class="datepicker" value='<?= $quote['expire_date']->format('Y-m-d') ?>' />
					</div>

					<div class="oneTwo required-field">
						<label for='arch'>Architectural Representative</label>
						<select id='arch' name='arch' class="validate[required]">
							<?php if ($session->user['approve_id'] != null) { ?>
								<?php foreach ($this->arch as $a) { ?>
									<option value="<?= $a['id'] ?>" <?php if ($a['id'] == $quote['arch']) echo 'selected'; ?>><?= $a['name'] . ' - ' . $a['default_company'] ?></option>
								<?php } ?>
							<?php } else { ?>
								<?php foreach ($this->arch as $a) { ?>
									<?php if ($a['id'] == $quote['arch']) { ?><option value="<?= $a['id'] ?>" selected><?= $a['name'] . ' - ' . $a['default_company'] ?></option> <?php } ?>
								<?php } ?>
							<?php } ?>
						</select>
					</div>

					<?php if ($quote['approve_status'] == $approved) { ?>
						<div class="oneTwo">
							<label for="quote_approval">Quote Approval</label>
							<select id="quote_approval" name="quote_approval">
								<?php foreach ($this->approval as $a) {
									if ($a['uid'] == $quote['quote_approval']) { ?>
										<option value="
											<?= $a['uid'] ?>" selected><?= $a['Name'] . ' - ' . $a['Company_ID'] ?>
										</option>
								<?php }
								} ?>
							</select>
						</div>
					<?php } else { ?>
						<input type="hidden" id='quote_approval' name='quote_approval' value="<?= $quote['quote_approval'] ?>" />
					<?php } ?>
				</div>

				<div class="line"></div>

				<h2>Comment</h2>
				<div class="formRow">
					<div class="oneTwo">
						<label for="quote-note">Quote Note</label>
						<textarea id="quote-note" rows="5" cols="" name="note" placeholder="Add quote note here..."><?= $quote['note'] ?></textarea>
					</div>
				</div>

				<?php if ($quote['approve_status'] != $approved) { ?>

					<div class="line"></div>

					<div class="widget-footer">
						<div class="widget-footer-button">
							<button disabled id="save_quote" type="button" title="Save quote information" class="button action save-quote-button small">
								<span class="button-wrap">
									Save
								</span>
							</button>
						</div>
					</div>
				<?php } ?>
			</div>
		</form>

		<section aria-labelledby="items" id="section4" data-nav="Items">
			<div class="widget-table">
				<div class="widget-button">
					<?php if ($quote['approve_status'] != $approved) { ?>
						<button type="button" title="Add new item" class="button action has-icon add-item-button small" id="opener">
							<span class="button-wrap">
								<span class="icon icon-add"></span>
								Add Item
							</span>
						</button>
					<?php } ?>
				</div>
				<h2>Items</h2>
				<table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap" id="items">
					<thead>
						<tr>
							<th>Item</th>
							<th>Quality Quoted</th>
							<th>Unit Price</th>
							<th>Unit Of Measure</th>
							<th>Price Quoted</th>
							<th>Note</th>
							<th>Options</th>
						</tr>
					</thead>
				</table>
			</div>
		</section>

		<div id="dialog-message" title="Add Item">
			<form action="" class="dialog" id='item'>
				<div class="dialog-form">
					<div class="oneTwo required-field">
						<label for="item_id">Item ID</label>
						<input type="hidden" name="item" id='item_input' />
						<input type="text" id="item_id" name='item_id' class="validate[required]" />
					</div>

					<div class="oneTwo required-field">
						<label for="uom">Unit of Measure</label>
						<select name="uom" id='uom' class="validate[required]">
							<option value=''>Select UOM</option>
						</select>
					</div>

					<div class="oneTwo required-field">
						<label for='price'>Price</label>
						<input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price" />
					</div>

					<div class="oneTwo required-field">
						<label for='qty'>Quantity</label>
						<input type="text" name="qty" id='qty' class="validate[required]" />
					</div>

					<div class="oneTwo dialog-note">
						<label for='note'>Note</label>
						<textarea rows="5" name='note' id='note' maxlength="255" class="validate[maxSize[255]]"></textarea>
						<input type="hidden" id="is_edit" value='0' />
					</div>
				</div>
			</form>
		</div>
	</div>
</main>

<script type="text/javascript">
	$("textarea").each(function() {
		this.setAttribute("style", "height:" + (this.scrollHeight) + "px;overflow-y:hidden;");
	}).on("input", function() {
		this.style.height = 0;
		this.style.height = (this.scrollHeight) + "px";
	});

	let itemTable = $("#items").DataTable({
		ajax: {
			url: "/quote/item/id/" + $('#quote_id').val(),
			dataSrc: ''
		},
		processing: true,
		columns: [{
				data: "product_id",
				render: function(data, type, row, meta) {
					return '<b class="item-name">' + data + '</b>' + '<br>' + row.item_desc;
				}
			},
			{
				data: "qty"
			},
			{
				data: "unit_price"
			},
			{
				data: "uom"
			},
			{
				data: "subtotal"
			},
			{
				data: "note",
				render: function(data) {
					let formattedText = data.replace(/(?:\r\n|\r|\n)/g, '<br>');
					return '<p>' + formattedText + '</p>';
				}
			},
			{
				data: "product_id",
				render: function(data, type, row, meta) {
					//var oldData = getolddata($(this).closest('tr'));
					<?php if ($quote['approve_status'] != 10) { ?>
						return '<div class="row-button">' +
							'<a title="Edit this item" class="edit" href="#">' +
							'<span class="button-wrap">' +
							'<span class="icon icon-edit"></span>' +
							'</span></a>' +
							'<a title="Delete this item" class="item_delete" href="/quote/deleteitem/id/' + row.quote_id + '/item/' + data + '/uom/' + row.uom + '/price/' + row.unit_price + '/qty/' + row.qty + '/sort/' + row.sort_id + '"' +
							'index="' + data + '">' +
							'<span class="button-wrap">' +
							'<span class="icon icon-delete"></span>' +
							'</span></a></div>';
					<?php } else { ?>
						return null;
					<?php } ?>
				}
			}
		],
		columnDefs: [{
				targets: [0, 1, 2, 3, 4],
				className: 'dt-body-center'
			},
			{
				targets: [0, 1, 2, 3, 4, 5, 6],
				className: 'dt-head-center'
			},
		],
		layout: {
			topStart: null,
			topEnd: null
		},
		order: {
			data: "added.date"
		},
		paging: false,
		scrollX: true,
		fixedColumns: {
			start: 1,
			end: 1
		}
	});

	function resetForm($form) {
		$form.find('input:text, input:password, input:file, select, textarea').val('');
		$form.find('input:radio, input:checkbox')
			.prop('checked', false)
			.prop('selected', false);
	}

	var current_edit_row = '';

	$(function() {

		$('#options-button').on("click", function() {
			$('#options-menu-items').slideToggle({
				start: function() {
					$(this).css('display', 'flex');
				}
			});
		})

		let currentRow = '';

		$('#items tbody').on('click', 'tr', function() {
			currentRow = itemTable.row(this).data();
		});

		function getolddata(row) {
			let item_id = currentRow['product_id'];
			let note = currentRow['note'];
			let qty = currentRow['qty'];
			let unit_price = currentRow['unit_price'];
			let uom = currentRow['uom'];
			let sort_id = currentRow['sort_id'];
			let data = {
				'old_item_id': item_id,
				'old_uom': uom,
				'old_price': unit_price,
				'old_qty': qty,
				'old_note': note,
				'sort_id': sort_id,
			};
			return data;
		}

		$("#dialog-message").dialog({
			autoOpen: false,
			modal: true,
			width: 800,
			minWidth: 800,
			open: function() { // fade in background
				$('.ui-widget-overlay').hide().fadeIn();
			},
			beforeClose: function() { //fade out background
				$('.ui-widget-overlay:first')
					.clone()
					.appendTo('body')
					.show()
					.fadeOut(400, function() {
						$(this).remove();
					});
			},
			dialogClass: 'add-item-dialog',
			buttons: [{
					id: "add-item-confirm-button",
					text: "Add",
					click: function() {
						if ($("#item").validationEngine('validate') == true) {
							if ($('#is_edit').val() == 1) {
								edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#note').val());
							} else {
								additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#note').val());
							}
							$(this).dialog("close");
							resetForm($('#item'));
						}
					}
				},
				{
					id: "add-item-cancel-button",
					text: "Cancel",
					click: function() {
						$(this).dialog("close");
					}
				}
			]
		});

		$('#opener').on("click", function() {
			resetForm($('#item'));
			$("#dialog-item").dialog("open");
			$('#is_edit').val(0);
			return false;
		});

		$(document).on("click", "a.edit", function() {
			$("#dialog-message").dialog("open");
			current_edit_row = $(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});

		$(document).on("click", ".item_delete", function(e) {
			e.preventDefault();
			if (confirm("Are you sure you want to delete this item?") == true) {
				$('.loading').show();
				$.ajax({
					url: $(this).attr('href'),
					type: "get",
					success: function(data) {
						itemTable.ajax.reload();
						$('.loading').hide();
					}
				});
			}
		});

		function set_edit(row) {
			$("#dialog-message").dialog("option", "title", "Edit Item");
			$('#is_edit').val(1);

			let item_id = currentRow['product_id'];
			let item_name = currentRow['item_desc']
			let note = currentRow['note'];
			let qty = currentRow['qty'];
			let unit_price = currentRow['unit_price'];
			let uom = currentRow['uom'];

			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);
			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);

			getoumedit(item_id, uom, unit_price);
		}

		function getoumedit(item_id, unit_number, price) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = JSON.parse(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option[value=' + unit_number + ']').attr('selected', 'selected');
					$('#uniform-uom span').html(unit_number);
					$('#price').val(price);
					$('.loading').hide();
				}
			});

		}

		function edititem(item_id, item_desc, uom, price, qty, note) {
			var olddata = getolddata(current_edit_row);
			var data = {
				'item_id': item_id,
				'uom': uom,
				'price': price,
				'qty': qty,
				'note': note,
				'sort_id': olddata['sort_id'],
				'old_item_id': olddata['old_item_id'],
				'old_uom': olddata['old_uom'],
				'old_price': olddata['old_price'],
				'old_qty': olddata['old_qty'],
				'old_note': olddata['old_note']
			};
			console.log(data);
			$.ajax({
				url: '/quote/edititem/id/' + $('#quote_id').val(),
				type: "post",
				data: data,
				success: function(data) {
					itemTable.ajax.reload();
				}
			});
		}

		function additem(item_id, item_desc, uom, price, qty, note) {
			$('.loading').show();
			$.ajax({
				url: '/quote/additem/id/' + $('#quote_id').val(),
				type: "post",
				data: $("#item").serialize(),
				success: function(data) {
					$('.loading').hide();
					itemTable.ajax.reload();
				}
			});
		}

		function getoum(item_id) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = JSON.parse(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option').eq(0).attr("selected", "selected");
					$('#uniform-uom span').html(uom[0].uom);
					getprice();
					$('.loading').hide();
				}
			});

		}

		function getprice() {
			$('.loading').show();
			$.ajax({
				url: '/item/price/id/' + $("#item_id ").val() + '/uom/' + $("#uom ").val(),
				type: "get",
				success: function(data) {
					var price = JSON.parse(data);
					$('#price').val(price.price);
				}
			});

		}

		$("#uom,#uniform-uom").on("change", function() {
			getprice();
			return false;
		});

		$(".dialog #item_id").autocomplete({
			source: '/item/index/',
			minLength: 2,
			select: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				$("#item_id ").val(ui.item.item_id);
				getoum(ui.item.item_id);
				$('#uom').prop('disabled', false);
				$('#uniform-uom').removeClass('disabled');
				return false;
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a><b>" + item.item_id + " - " + item.item_desc + "</b></a>")
				.appendTo(ul);
		};

		function getcustomerbyid(id) {
			$('.loading').show();
			$.ajax({
				url: '/customer/fetchbyid/id/' + id,
				type: "get",
				success: function(data) {
					var result = JSON.parse(data);
					if (result != null) {
						$('#quote').val(result.name);
						$('#customer_id').val(id);
						$('#first_name').val(result.first_name);
						$('#last_name').val(result.last_name);
						$('#address').val(result.phys_address1);
						$('#phys_address2').val(result.phys_address2);
						$('#phys_city').val(result.phys_city);
						$('#mail_state').val(result.mail_state);
						$('#mail_postal_code').val(result.mail_postal_code);
						$('#phys_country').val(result.phys_country);
						$('#tel').val(result.tel);
						$('#contact').val(result.fullname);
						$('#customer_email').val(result.email);
						$('#company_id').val(result.company_id);
						//$('#sale_rep').val(result.sale_rep);

					} else {
						alert('Can\'t find customer');
						$('#customer_info input').val('');
					}
					$('.loading').hide();
				}
			});
		};

		function getOldCustomer() {
			let quoteTo = $('#quote').val();
			let firstName = $('#first_name').val();
			let lastName = $('#last_name').val();
			let address1 = $('#address').val();
			let address2 = $('#phys_address2').val();
			let city = $('#phys_city').val();
			let province = $('#mail_state').val();
			let postalCode = $('#mail_postal_code').val();
			let country = $('#phys_country').val();
			let phoneNumber = $('#tel').val();
			let contact = $('#contact').val();
			let email = $('#customer_email').val();
			let companyId = $('#company_id').val();
			let customerId = $('#customer_id').val();
			let oldData = {
				'oldQuoteTo': quoteTo,
				'oldFirstName': firstName,
				'oldLastName': lastName,
				'oldAddress1': address1,
				'oldAddress2': address2,
				'oldCity': city,
				'oldProvince': province,
				'oldPostalCode': postalCode,
				'oldCountry': country,
				'oldPhoneNumber': phoneNumber,
				'oldContact': contact,
				'oldEmail': email,
				'oldCustomerId': customerId,
				'oldCompanyId': companyId
			};
			return oldData;
		}

		let oldCustomer = '';

		$('#add_new_mode').on("click", function() {
			oldCustomer = getOldCustomer();
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id').prop('readonly', false);
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id, #customer_id').val('');
			$('#quote, #address, #tel, #customer_email').addClass('validate[required]');
			$('#add_new_mode').hide();
			$('#discard_new_mode').show();
			//console.log(oldCustomer);
		});

		$('#discard_new_mode').on("click", function() {
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email').prop('readonly', true);
			$('#quote').val(oldCustomer['oldQuoteTo']);
			$('#first_name').val(oldCustomer['oldFirstName']);
			$('#last_name').val(oldCustomer['oldLastName']);
			$('#address').val(oldCustomer['oldAddress1']);
			$('#phys_address2').val(oldCustomer['oldAddress2']);
			$('#phys_city').val(oldCustomer['oldCity']);
			$('#mail_state').val(oldCustomer['oldProvince']);
			$('#mail_postal_code').val(oldCustomer['oldPostalCode']);
			$('#phys_country').val(oldCustomer['oldCountry']);
			$('#tel').val(oldCustomer['oldPhoneNumber']);
			$('#contact').val(oldCustomer['oldContact']);
			$('#customer_email').val(oldCustomer['oldEmail']);
			$('#customer_id').val(oldCustomer['oldCustomerId']);
			$('#company_id').val(oldCustomer['oldCompanyId']);

			$('#quote, #address, #tel,#customer_email').removeClass('validate[required]');
			$('#add_new_mode').show();
			$('#discard_new_mode').hide();
			oldCustomer = '';
		});

		$("#customer_email").autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.email + "<br>" + item.first_name + ' ' + item.last_name + "</a>")
				.appendTo(ul);
		};

		$("#quote").autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		$("#contact").autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		let unsave = false;

		$('#quote_content').on("change", function() {
			$('#save_quote').prop("disabled", false);
			unsave = true;
		});

		$('#save_quote').on("click", function(e) {
			e.preventDefault();
			if ($("#quote_content").validationEngine('validate') == true) {
				$('#quote_content').trigger("submit");
				unsave = false;
				//location.reload();
			}
		});

		window.onbeforeunload = function() {
			if (unsave) {
				$('#save_quote').trigger("focus");
				return "You have unsaved changes project information. Do you want to leave this page and discard your changes or stay on this page?";
			}
		}

		$('.delete_quote').on("click", function(e) {
			if (confirm("Are you sure you want to delete this quote?") == true) {
				$.ajax({
					url: '/quote/delete/id/' + $('#quote_id').val(),
					type: "get",
					success: function(data) {
						window.location = "/index";
					}
				});
			} else {
				e.preventDefault();
			}
		});

		$('a.ready_quote').on("click", function(e) {
			if (confirm("Click OK to submit quote.\nClick CANCEL to return to edit.") == true) {
				e.preventDefault();
				$('.loading').show();
				$.ajax({
					url: "/quote/ready/id/<?= $quoteID ?>",
					type: "get",
					success: function(data) {
						//$('#status').html('<div class="nNote nInformation hideit"><p><strong>INFORMATION: </strong>Your Quote is Waiting for Approval.</p></div>');
						//$('a.ready_quote').hide();
						<?php if ($session->user['approve_id'] != null) { ?>
							window.location.replace('<?= 'http://' . SITEURL . '/approve/index/id/' . $quoteID ?>');
						<?php } else { ?>
							window.scrollTo(0, 0);
							location.reload();
						<?php } ?>
					}
				});
			} else {
				e.preventDefault();
			}
		});


		$('a.quote-edit-again').on("click", function(e) {
			if (confirm("You need submit again after edit!") == true) {
				e.preventDefault();
				$('.loading').show();
				$.ajax({
					url: "/quote/ready/id/<?= $quoteID ?>",
					type: "get",
					success: function(data) {
						//$('#status').html('<div class="nNote nInformation hideit"><p><strong>INFORMATION: </strong>You Need submit again after edit</p></div>');
						location.reload();
					}
				});
				$('.loading').hide();
			} else {
				e.preventDefault();
			}
		});
	});
</script>