<?php
$session =  Zend_Registry::get('session');
$project = $this->project;
$projectCreateDate = DateTime::createFromFormat('Y-m-d h:i:s.v', $project['create_date']);
$projectDueDate = DateTime::createFromFormat('Y-m-d h:i:s.v', $project['due_date']);
$projectRequiredDate = DateTime::createFromFormat('Y-m-d h:i:s.v', $project['required_date']);
?>

<!-- Title area -->
<main id="content" class="main-content">
	<div class="main-page-content">
		<header class="main-page-content-header">
			<div class="options-menu">
				<button class="quick-link options-button" id="options-button" type="button">
					<span class='icon icon-menu'></span>
					Options
				</button>

				<!-- Right panel -->
				<div class="sidebar-container" id="options-menu-items">
					<a id="save_quote" class="button quick-link save_quote" href="#" title="">
						<span class='icon icon-save'></span>
						Save & make quote</a>
				</div>
			</div>

			<h1>Make quote</h1>
		</header>

		<div class="widget-information ">
			<div style="grid-row: 1/1" class="widget-table dashboard">
				<span class='svg icon icon-list'></span>
				<div class="project-information project-name">
					<h2><?= $project['project_name'] ?></h2>
					<p><?= ($project['project_location_address'] == 'N/A') ? '' : $project['project_location_address'] ?></p>
					</br>
					<p>by <b><?= $project['owner'] ?></b></p>
					<?php if (($project['worksheet_assign']) != null) { ?>
						<p>shared with <b><?= $project['worksheet_assign'] ?></b></p>
					<?php } ?>
				</div>
			</div>

			<div class="widget-table dashboard">
				<span class='svg icon icon-calender'></span>
				<div class="project-information">
					<p>Due date</p>
					<h2><?= $projectDueDate->format('Y-m-d') ?></h2>
				</div>
			</div>

			<div class="widget-table dashboard">
				<div class="project-information">
					<span class='svg icon icon-information-circle'></span>
					<p>Project status</p>
					<h2>
						<?php if ($project['status'] != 13) {
							echo $project['status_name'];
						} else {
							echo 'Closed';
						} ?>
					</h2>
				</div>
			</div>
		</div>

		<!-- Form -->
		<form action="/quote/save" method='post' class="form" id="quote_content">
			<input type="hidden" id="project_id" name='project_id' value="<?= $project['project_id'] ?>" />
			<div class="widget-table" id="customer_info">
				<div class="widget-button">
					<button type="button" class="button action has-icon new-customer small" id="add_new_mode">
						<span class="button-wrap">
							<span class="icon icon-add"></span>
							New Customer
						</span>
					</button>
					<button type="button" class="button action has-icon discard-customer small basic" style='display:none;' id="discard_new_mode">
						<span class="button-wrap">
							<span class="icon icon-undo"></span>
							Discard Adding
						</span>
					</button>
				</div>

				<h2>Customer Infomation</h2>
				<div class="formRow">
					<div class="oneTwo required-field">
						<label for="quote">Quote To</label>
						<input type="text" value="" id='quote' name='name' class='tipN validate[required]' />
					</div>

					<div class="oneTwo">
						<label for="customer_id">Customer ID</label>
						<input name='customer_id' type="text" id='customer_id' class="validate[custom[integer]] tipN" value="" original-title="Delete this if you want to add new customer or contact" />
					</div>

					<div class="oneTwo">
						<label for="company_id">Company ID</label>
						<input type="text" name='company_id' id='company_id' placeholder="Optional" />
					</div>

					<div class="oneTwo">
						<label for="first_name">First Name</label>
						<input id='first_name' name='first_name' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo">
						<label for="last_name">Last Name</label>
						<input id='last_name' name='last_name' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo required-field">
						<label for="address">Address 1</label>
						<input type="text" value="" id='address' name='phys_address1' />
					</div>

					<div class="oneTwo">
						<label for="phys_address2">Address 2</label>
						<input id='phys_address2' name='phys_address2' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo">
						<label for="phys_city">City</label>
						<input id='phys_city' name='phys_city' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo">
						<label for="mail_state">Province</label>
						<input id='mail_state' name='mail_state' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo">
						<label for="mail_postal_code">Postal Code</label>
						<input id='mail_postal_code' name='mail_postal_code' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo">
						<label for="phys_country">Country</label>
						<input id='phys_country' name='phys_country' type="text" placeholder="Optional">
					</div>

					<div class="oneTwo required-field">
						<label for="tel">Phone Number</label>
						<input type="text" id='tel' name='phone' class="maskPhoneExt" value="" id='tel' name='tel' />
					</div>

					<div class="oneTwo required-field">
						<label for="contact">Contact</label>
						<input type="text" id='contact' name='fullname' class="validate[required] tipN" value="" original-title="Enter Customer Name to fetch existing customer" />
					</div>
					<div class="oneTwo required-field">
						<label for="customer_email">Email</label>
						<input type="text" value="" id='customer_email' name='Contacts_email' class="validate[custom[email]] tipN" original-title="Enter Customer Email to fetch existing customer">
					</div>

					<div class="oneTwo">
						<label for="sale_rep">Sales Representative</label>
						<input id="sale_rep" type="text" value="<?= $session->user['id'] ?>" readonly />
					</div>
				</div>

				<div class="line"></div>

				<h2>Quote Infomation</h2>
				<div class="formRow">
					<div class="oneTwo">
						<label for="quote-number">Quote Number</label>
						<input id="quote-number" type="text" placeholder="Auto Generate" readonly />
					</div>
					<div class="oneTwo required-field">
						<label for="quote_type">Quote Type</label>
						<select name="quote_type_id" id="quote_type" class="validate[required]">
							<option value="">-- Select --</option>
							<?php foreach ($this->type as $t) { ?>
								<option value="<?= $t['uid'] ?>"><?= $t['type'] ?></option>
							<?php } ?>
						</select>
					</div>
					<div class="oneTwo required-field">
						<label for="Segment">Quote Segment</label>
						<select name="quote_segment" id='Segment' class="validate[required]">
							<option value="">-- Choose Segment --</option>
							<?php foreach ($this->seg as $s) { ?>
								<option value="<?= $s['uid'] ?>" <?php if ($s['uid'] == $project['market_segment']) echo 'selected' ?>><?= $s['Market_Segment'] ?></option>
							<?php } ?>
						</select>
					</div>

					<input type="hidden" class="datepicker" id='quote_date' name='quote_date' />

					<div class="oneTwo">
						<label for="ship-required-date">Shipment Required Date</label>
						<input id="ship-required-date" type="text" class="datepicker" name='ship_required_date' value="<?php if ($projectRequiredDate && $projectRequiredDate > new DateTime('2000-01-01')) {
																															echo $projectRequiredDate->format('Y-m-d');
																														} ?>" />
					</div>
					<div class="oneTwo">
						<label for="quote_date">Expire Date</label>
						<input id="expire_date" name="expire_date" type="text" class="datepicker" value='<?= date("Y-m-d", mktime(0, 0, 0, date("m"), date("d") + 60, date("Y"))) ?>' />
					</div>
					<div class="oneTwo">
						<label for="arch">Architectural Representative</label>
						<select id="arch" name='arch' class="validate[required]">
							<?php if ($session->user['approve_id'] != null) {
								foreach ($this->arch as $a) { ?>
									<option value="<?= $a['id'] ?>" <?php if ($a['id'] == $project['owner']) {
																		echo 'selected';
																	} ?>><?= ($a['name'] ?? '') . ' - ' . ($a['default_company'] ?? '') ?></option>
									<?php }
							} else {
								foreach ($this->arch as $a) {
									if (($a['id']) == ($project['owner']) or $a['id'] == (($project['worksheet_assign']))) { ?>
										<option value="<?= $a['id'] ?>" selected><?= ($a['name'] ?? '') . ' - ' . ($a['default_company'] ?? '') ?></option>
							<?php }
								}
							} ?>
						</select>
					</div>
					<input type="hidden" name="sales_id" value="<?= $session->user['id'] ?>" />

					<?php foreach ($this->seg as $s) { ?>
						<?php if ($s['uid'] == $project['market_segment']) $seg = $s['Market_Segment'] ?>
					<?php } ?>

				</div>

				<div class="line"></div>

				<h2>Comment</h2>
				<div class="formRow">
					<div class="oneTwo">
						<label for="quote-note">Quote Note</label>
						<textarea id="quote-note" rows="5" name="note" placeholder="Note area"></textarea>
					</div>
				</div>

			</div>
		</form>

		<section aria-labelledby="items" id="section4" data-nav="Items">
			<div class="widget-table">
				<div class="widget-button">
					<button type="button" title="Add new item" class="button action has-icon add-item-button small" id="opener">
						<span class="button-wrap">
							<span class="icon icon-add"></span>
							Add Item
						</span>
					</button>
				</div>
				<h2>Items</h2>
				<table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap" id="items">
					<thead>
						<tr>
							<td>Item</td>
							<td>Quality Quoted</td>
							<td>Unit Price</td>
							<td>Unit Of Measure</td>
							<td>Price Quoted</td>
							<td>Note</td>
							<td>Options</td>
						</tr>
					</thead>
				</table>
			</div>
		</section>

		<div id="dialog-message" title="Add Item">
			<form action="" class="dialog" id='item'>
				<div class="dialog-form">
					<div class="oneTwo required-field">
						<label for="item_id">Item ID</label>
						<input type="hidden" name="item" id='item_input' />
						<input type="text" id="item_id" name='item_id' class="validate[required]" />
					</div>

					<div class="oneTwo required-field">
						<label for='uom'>Unit Of Measure</label>
						<select name="uom" id='uom' class="validate[required]">
							<option value=''>-- Select UOM --</option>
						</select>
					</div>

					<div class="oneTwo required-field">
						<label class="formNote">Price ($)</label>
						<input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price" />
					</div>

					<div class="oneTwo required-field">
						<label for='qty'>Quantity</label>
						<input type="text" name="qty" id='qty' class="validate[required]" />
					</div>

					<div class="oneTwo dialog-note">
						<label for='note'>Note</label>
						<textarea rows="5" name='note' id="note" maxlength="255" class="validate[maxSize[255]]"></textarea>
						<input type="hidden" id="is_edit" value='0' />
					</div>
				</div>
			</form>
		</div>
	</div>
</main>

<script type="text/javascript">
	let itemTable = $("#items").DataTable({
		ajax: {
			url: "/project/item/id/" + $('#project_id').val(),
			dataSrc: ''
		},
		processing: true,
		columns: [{
				data: "product_id",
				render: function(data, type, row, meta) {
					return '<b class="item-name">' + data + '</b>' + '<br>' + row.item_desc;
				}
			},
			{
				data: "qty"
			},
			{
				data: "unit_price"
			},
			{
				data: "uom"
			},
			{
				data: "subtotal"
			},
			{
				data: "note"
			},
			{
				data: "product_id",
				render: function(data, type, row, meta) {
					//var oldData = getolddata($(this).closest('tr'));
					return '<div class="row-button">' +
						'<a title="Edit this item" class="edit" href="#">' +
						'<span class="button-wrap">' +
						'<span class="icon icon-edit"></span>' +
						'</span></a>' +
						'<a title="Delete this item" class="item_delete" href="/project/deleteitem/pro/' + row.project_id + '/item/' + data + '/uom/' + row.uom + '/price/' + row.unit_price + '/qty/' + row.qty + '"' +
						'index="' + data + '">' +
						'<span class="button-wrap">' +
						'<span class="icon icon-delete"></span>' +
						'</span></a></div>';
				}
			}
		],
		columnDefs: [{
			targets: '_all',
			className: 'dt-head-center'
		}, {
			targets: [0, 1, 2, 3, 4],
			className: 'dt-body-center'
		}],
		layout: {
			topStart: null,
			topEnd: null
		},
		order: {
			data: "added.date"
		},
		paging: false,
		scrollX: true,
		fixedColumns: {
			start: 1,
			end: 1
		}
	});

	function resetForm($form) {
		$form.find('input:text, input:password, input:file, select, textarea').val('');
		$form.find('input:radio, input:checkbox')
			.prop('checked', false).prop('selected', false);
	}

	var current_edit_row = '';

	$(function() {

		$('#options-button').on("click", function() {
			$('#options-menu-items').slideToggle({
				start: function() {
					$(this).css('display', 'flex');
				}
			});
		})

		let currentRow = '';

		$('#items tbody').on('click', 'tr', function() {
			currentRow = itemTable.row(this).data();
		});

		function getolddata(row) {
			let item_id = currentRow['product_id'];
			let note = currentRow['note'];
			let qty = currentRow['qty'];
			let unit_price = currentRow['unit_price'];
			let uom = currentRow['uom'];
			var data = {
				'old_item_id': item_id,
				'old_uom': uom,
				'old_price': unit_price,
				'old_qty': qty,
				'old_note': note
			};
			return data;
		}

		$("#dialog-message").dialog({
			autoOpen: false,
			modal: true,
			minWidth: 800,
			width: 800,
			open: function() { // fade in background
				$('.ui-widget-overlay').hide().fadeIn();
			},
			beforeClose: function() { //fade out background
				$('.ui-widget-overlay:first')
					.clone()
					.appendTo('body')
					.show()
					.fadeOut(400, function() {
						$(this).remove();
					});
			},
			dialogClass: 'add-item-dialog',
			buttons: [{
					id: "btn-add",
					text: "Add",
					click: function() {
						if ($("#item").validationEngine('validate') == true) {
							if ($('#is_edit').val() == 1) {
								edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#note').val());
							} else {
								additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#note').val());
							}
							$(this).dialog("close");
							resetForm($('#item'));
						}
					}
				},
				{
					id: "btn-cancel",
					text: "Cancel",
					click: function() {
						$(this).dialog("close");
					}
				}
			]
		});

		$('#opener').on("click", function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});

		$(document).on("click", "a.edit", function() {
			$("#dialog-message").dialog("open");
			current_edit_row = $(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});

		$(document).on('click', ".item_delete", function(e) {
			e.preventDefault();
			if (confirm("Are you sure you want to delete this item?") == true) {
				$('.loading').show();
				$.ajax({
					url: $(this).attr('href'),
					type: "get",
					success: function(data) {
						itemTable.ajax.reload();
						$('.loading').hide();
					}
				});
			}
		});

		function set_edit(row) {
			$("#dialog-message").dialog("option", "title", "Edit Item");
			$('#is_edit').val(1);

			let item_id = currentRow['product_id'];
			let item_name = currentRow['item_desc'];
			let note = currentRow['note'];
			let qty = currentRow['qty'];
			let unit_price = currentRow['unit_price'];
			let uom = currentRow['uom'];

			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);

			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);

			getoumedit(item_id, uom, unit_price);
		}

		function getoumedit(item_id, unit_number, price) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = JSON.parse(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option[value=' + unit_number + ']').attr('selected', 'selected');
					$('#uniform-uom span').html(unit_number);
					$('#price').val(price);
					$('.loading').hide();
				}
			});

		}

		function edititem(item_id, item_desc, uom, price, qty, note) {
			ajaxedititem(item_id, uom, price, qty, note);
		}

		function ajaxedititem(item_id, uom, price, qty, note) {
			var olddata = getolddata(current_edit_row);
			var data = {
				'item_id': item_id,
				'uom': uom,
				'price': price,
				'qty': qty,
				'note': note,
				'old_item_id': olddata['old_item_id'],
				'old_uom': olddata['old_uom'],
				'old_price': olddata['old_price'],
				'old_qty': olddata['old_qty'],
				'old_note': olddata['old_note']
			};
			$.ajax({
				url: '/project/edititem/pro/' + $('#project_id').val(),
				type: "post",
				data: data,
				success: function(data) {
					itemTable.ajax.reload();
				}
			});
		};

		$(".dialog #item_id").autocomplete({
			source: '/item/index/',
			minLength: 2,
			select: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				$("#item_id").val(ui.item.item_id);
				getoum(ui.item.item_id);
				$('#uom').prop('disabled', false);
				$('#uniform-uom').removeClass('disabled');
				return false;
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a><b>" + item.item_id + " - " + item.item_desc + "</b></a>")
				.appendTo(ul);
		};

		function getoum(item_id) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = jQuery.parseJSON(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option').eq(0).attr("selected", "selected");
					$('#uniform-uom span').html(uom[0].uom);
					getprice();
					$('.loading').hide();
				}
			});

		}

		function getprice() {
			$('.loading').show();
			$.ajax({
				url: '/item/price/id/' + $("#item_id ").val() + '/uom/' + $("#uom ").val(),
				type: "get",
				success: function(data) {
					var price = jQuery.parseJSON(data);
					$('#price').val(price.price);
					$('.loading').hide();
				}
			});

		}

		function additem(item_id, item_desc, uom, price, qty) {
			$.ajax({
				url: '/project/additem/pro/' + $('#project_id').val(),
				type: "post",
				data: $("#item").serialize(),
				success: function(data) {
					itemTable.ajax.reload();
				}
			});
		}

		function getcustomerbyid(id) {
			$('.loading').show();
			$.ajax({
				url: '/customer/fetchbyid/id/' + id,
				type: "get",
				success: function(data) {
					var result = JSON.parse(data);
					if (result != null) {
						$('#quote').val(result.name);
						$('#customer_id').val(id);
						$('#first_name').val(result.first_name);
						$('#last_name').val(result.last_name);
						$('#address').val(result.phys_address1);
						$('#phys_address2').val(result.phys_address2);
						$('#phys_city').val(result.phys_city);
						$('#mail_state').val(result.mail_state);
						$('#mail_postal_code').val(result.mail_postal_code);
						$('#phys_country').val(result.phys_country);
						$('#tel').val(result.tel);
						$('#contact').val(result.fullname);
						$('#customer_email').val(result.email);
						$('#company_id').val(result.company_id)
						$('#sale_rep').val(result.sale_rep);
					} else {
						alert('Can\'t find customer');
						$('#customer_info input').val('');
					}
				}
			});
		}

		function getOldCustomer() {
			let oldData = {
				'oldQuoteTo': $('#quote').val(),
				'oldFirstName': $('#first_name').val(),
				'oldLastName': $('#last_name').val(),
				'oldAddress1': $('#address').val(),
				'oldAddress2': $('#phys_address2').val(),
				'oldCity': $('#phys_city').val(),
				'oldProvince': $('#mail_state').val(),
				'oldPostalCode': $('#mail_postal_code').val(),
				'oldCountry': $('#phys_country').val(),
				'oldPhoneNumber': $('#tel').val(),
				'oldContact': $('#contact').val(),
				'oldEmail': $('#customer_email').val(),
				'oldCustomerId': $('#customer_id').val(),
				'oldCompanyId': $('#company_id').val(),
				'oldSaleRep': $('#sale_rep').val()
			};
			return oldData;
		}

		let oldCustomer = '';

		$('#add_new_mode').on("click", function() {
			oldCustomer = getOldCustomer();
			$('#quote, #first_name, #last_name, #address, #phys_address2, #phys_city, #mail_state, #mail_postal_code, #phys_country, #tel, #contact, #customer_email, #company_id, #customer_id, #sale_rep').val('');
			$('#quote, #address, #tel, #customer_email').addClass('validate[required]');
			$('#add_new_mode').hide();
			$('#discard_new_mode').show();
			//console.log(oldCustomer);
		});

		$('#discard_new_mode').on("click", function() {
			$('#quote').val(oldCustomer['oldQuoteTo']);
			$('#first_name').val(oldCustomer['oldFirstName']);
			$('#last_name').val(oldCustomer['oldLastName']);
			$('#address').val(oldCustomer['oldAddress1']);
			$('#phys_address2').val(oldCustomer['oldAddress2']);
			$('#phys_city').val(oldCustomer['oldCity']);
			$('#mail_state').val(oldCustomer['oldProvince']);
			$('#mail_postal_code').val(oldCustomer['oldPostalCode']);
			$('#phys_country').val(oldCustomer['oldCountry']);
			$('#tel').val(oldCustomer['oldPhoneNumber']);
			$('#contact').val(oldCustomer['oldContact']);
			$('#customer_email').val(oldCustomer['oldEmail']);
			$('#customer_id').val(oldCustomer['oldCustomerId']);
			$('#company_id').val(oldCustomer['oldCompanyId']);
			$('#sale_rep').val(oldCustomer['oldSaleRep']);

			$('#quote, #address, #tel,#customer_email').removeClass('validate[required]');
			$('#add_new_mode').show();
			$('#discard_new_mode').hide();

			oldCustomer = '';
		});

		$("#uom,#uniform-uom").on("change", function() {
			getprice();
			return false;
		});

		$("#customer_email").autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.email + "<br>" + item.first_name + ' ' + item.last_name + "</a>")
				.appendTo(ul);
		};

		$("#quote").autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		$("#contact").autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			},

		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		let unsave = false;

		$('#quote_content').on("change", function() {
			unsave = true;
		});

		$('a.save_quote').on("click", function(e) {
			e.preventDefault();
			if ($("#quote_content").validationEngine('validate') == true) {
				$('.loading').show();
				$('#quote_content').trigger("submit");
				unsave = false;
			}
		});

		window.onbeforeunload = function() {
			if (unsave) {
				return "You have unsaved changes project information. Do you want to leave this page and discard your changes or stay on this page?";
			}
		}
	});
</script>