   <?php $session =  Zend_Registry::get('session'); ?>

   <!-- Left panel -->
<div>
<div class="statsRow">
        	<div class="controlB">
            	<ul>
                	<!--<li><a href="#" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
                    <!--<li><a href="#" title=""><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Current</span></a></li>-->
                    <!--<li><a href="#" title=""><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Quote</span></a></li>-->
                    <li><a class="save_quote" href="#" title=""><img src="/images/icons/control/32/save.png" alt="" /><span>Save Quote</span></a></li>
                    <!--<li><a href="#" title=""><img src="/images/icons/control/32/mail.png" alt="" /><span>Email Quote</span></a></li>
                    <li><a href="#" title=""><img src="/images/icons/control/32/delete.png" alt="" /><span>Delete Quote</span></a></li>-->
                </ul>
            </div>
    </div>
</div>

 <!-- Title area -->
 <?php $project = $this->project;?>
 <main id="content" class="main-content">
 <div class="main-page-content">
    <div class="titleArea">
            <header>
                <h1>Price Quote</h1>
			</header>
			<div class="section-content">
			<span>Project Name: <b><?=$project['project_name'] ?></b></span> | <span>Project Quote No: <b><?=$project['quote_no'] ?></b></span>  | <span>Worksheet Owner: <b><?=$project['owner'] ?></b></span> | <span>Status: <b><?=$project['status_name'] ?></b></span>  | <span>Due Date: <b><?=$project['due_date']->format('Y-m-d')  ?></b></span>
			</div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
    </div>
    
 <!-- Page statistics area -->
    <!-- Main content wrapper --
    
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
        <form action="/quote/save" method='post' class="form" id="quote_content">
            <input type="hidden" name='project_id' value="<?=$project['project_id'] ?>" />
                <div class="widget-table" id="customer_info">
                    <div class="title">
						<img src="/images/icons/dark/user.png" alt="" class="titleIcon" />
						<h6>Customer Infomation</h6>
						<a href="javascript:void(0)" title="" class="button greenB" style="margin: 2px;" id="add_new_mode">
							<span>New Customer</span></a>
						<a href="javascript:void(0)" title="" class="button basic" style='display:none;' style="margin: 2px;" id="discard_new_mode">
							<span>Discard Adding</span>
						</a>
					</div>
                    <div class="formRow">
                        <label>Quote To:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="" id='quote' name='name' class='tipN validate[required]' /></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Address:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="" id='address' name='phys_address1' readonly/></div>
                        <div class="clear"></div>
                    </div>
                    <div class="formRow">
                        <label>Tel:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" id='tel' name='phone' class="maskPhoneExt"  value="" id='tel' name='tel' readonly/></div>
                        <div class="clear"></div>
                    </div>
                    <div class="formRow">
                        <label>Customer ID :<span class="req">*</span></label>
                        <div class="formRight"><input name='customer_id' type="text" id='customer_id' class="validate[custom[integer]] tipN"  value="" original-title="Leave blank for add new customer" readonly/></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Contact:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" id='contact' name='fullname' class="validate[required] tipN"  value=""  original-title="Enter Customer Name to fetch existing customer" /></div>
                        <div class="clear"></div>
                    </div>
                     <div class="formRow">
                        <label>Email:<span class="req">*</span></label>
                        <div class="formRight"><input type="text" value="" id='customer_email' name='Contacts_email' class="validate[custom[email]] tipN"  original-title="Enter Customer Email to fetch existing customer"></div>
                        <div class="clear"></div>
                    </div>
              </div>

                <div class="widget-table">
                    <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
                      <h6>Quote Infomation</h6></div>
                     <div class="formRow"> 
                        <div class="formRight" style="width:98%">
                            <span class="oneFour"><span class="formNote">Quote Number</span><input type="text" placeholder="Auto Generate" readonly /></span>
                            <span class="oneFour"><span class="formNote">Quote Date</span><input type="text" class="datepicker" id='quote_date' value='<?=date('Y-m-d')?>'/></span>
                            <span class="oneFour"><span class="formNote">Ship Required Date</span><input type="text" class="datepicker" name='ship_required_date' value="<?php if($project['required_date'] != null && $project['required_date']->format('Y-m-d') > '2000-01-01') echo $project['required_date']->format('Y-m-d'); ?>"/></span>
                            <span class="oneFour"><span class="formNote">Quote Type</span>
                            		<select name="quote_type_id" id='quote_type' class="validate[required]">
                                <option value="">Select Quote type</option>
                                <?php foreach($this->type as $t) {?>
                                <option value="<?=$t['uid'] ?>"><?=$t['type'] ?></option>
                                <?php } ?>
                            	</select>
                            </span>
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                            <span class="oneFour"><span class="formNote">Project Name</span><input type="text" value="<?=$project['project_name']?>" readonly/></span>
                            <span class="oneFour"><span class="formNote">Project Location</span><input type="text" value="<?=$project['project_location_address']?>" readonly/></span>
                            <span class="oneFour"><span class="formNote">Sale Rep</span><input id='sale_rep' type="text" value="<?=$session->user['name'] ?>"readonly/></span>
                            <span class="oneFour"><span class="formNote">Arch Rep.<span class="req">*</span></span>
                            		<select id='arch' name='arch' class="validate[required]" >
                              	 <?php if($session->user['approve_id'] != null  ) {?>
	                                <?php foreach($this->arch as $a) {?>
	                                <option value="<?=$a['id']?>" <?php if($a['id'] == $this->quote['arch']) echo 'selected';?>><?=$a['name'].' - '.$a['default_company']?></option>
	                             		 <?php }?>
                             		 <?php } else { ?>
	                             		 <?php foreach($this->arch as $a) {?>
		                                 <?php if($a['id'] == $project['owner']){?><option value="<?=$a['id']?>" selected ><?=$a['name'].' - '.$a['default_company']?></option> <?php }?>
		                             		<?php }?>
                             		 <?php }?>
                            	</select>
                            </span>
                            <input type="hidden" name="sales_id" value="<?=$session->user['id'] ?>"" />
                        </div>
                        <div class="clear"></div>
                        <div class="formRight" style="width:98%">
                        	 <?php foreach($this->seg as $s) {?>
                                 <?php if($s['uid'] == $project['market_segment']) $seg = $s['Market_Segment'] ?>
                            <?php }?>
                        	<span class="oneFour"><span class="formNote">Segment<span class="req">*</span></span><input type="text"  original-title="Segment Format" name='quote_segment' id='Segment' class='validate[required] tipN' value="<?=$seg ?>"/></span>
                        	 <span class="oneFour"><span class="formNote">Quote Approval<span class="req">*</span></span>
                            		<select id="quote_approval" >
                                <option value="">Only Approver Can Edit</option>
                                <!--<?php foreach($this->approval as $a) {?>
                                <option value="<?=$a['uid']?>"><?=$a['Name'].' - '.$a['Company_ID']?></option>
                             		 <?php }?>-->
                            	</select>
                            	
                            </span>
                        </div>
                        <div class="clear"></div>
                    </div>
              </div>

             <div class="widget-table">
        <div class="title"><span class="titleIcon"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Items</h6><a href="#" title="" class="button greenB" style="margin: 5px;" id="opener"><span>Add new Item</span></a> </a></div>
        <div class="clear"></div>
          <table cellpadding="0" cellspacing="0" width="100%" class="sTable" id="items" style="text-align:center;">
              <thead>
                  <tr>
                      <td></td>
                      <td width="60%">Item ID - Description</td>
                      <td>Quality Quoted</td>
                      <td>Unit Price</td>
                      <td>Unit Of Measure</td>
                      <td>Price Quoted</td>
                      <td>Action</td>
                  </tr>
              </thead>
              <tbody id="item_body">
                  <?php foreach ($this->items as $i) { ?>
                 		<tr name="item[<?=$i['product_id']?>]"><td><input type="checkbox" name="item[<?=$i['product_id']?>]"></td>
                 			<td><?=$i['product_id']?> - <?=$i['item_desc'] ?>
                 				<textarea rows="1" cols="" name="item[<?=$i['product_id']?>][note][]"><?=$i['note']?></textarea>
                 		  </td>
                 		  <td><?=$i['qty']?></td>
                 		  <td><?=$i['unit_price']?></td>
                 		  <td><?=$i['uom']?></td>
                 		  <td><?=$i['subtotal']?></td>
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][qty][]" value="<?=$i['qty']?>"><input type="hidden" name="item[<?=$i['product_id']?>][unit_price][]" value="<?=$i['unit_price']?>">
	                 		  <input type="hidden" name="item[<?=$i['product_id']?>][uom][]" value="<?=$i['uom']?>"><input type="hidden" name="item[<?=$i['product_id']?>][total_price][]" value="<?=$i['subtotal']?>">
	                 		   <input type="hidden" class='sorts' name="item[<?=$i['product_id']?>][sort][]" value="<?=$i['sort_id']?>">
	                 		  <td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>
                 		  
                 		</tr>
                 <?php }?>
              </tbody>
          </table>
          </div>
           <div class="widget-table">
       <div class="title"><img src="/images/icons/dark/pencil.png" alt="" class="titleIcon" />
       <h6>Comment</h6></div>
        <div class="clear"></div>
        		<div class="formRow">
	            <label>Quote Note:</label>
	            <div class="formRight"><textarea rows="8" cols="" name="note" placeholder="Note Area"></textarea></div>
            <div class="clear"></div>
          </div>
      	</div>
        </form>
            
   <div id="dialog-message" title="Add Item">
        <div class="uiForm">
            <form action="" class="dialog" id='item'>
            		<span class="formNote">Enter Item ID </span>
                <input type="text" name="item" id='item_input' class="validate[required]" />
                <input type="hidden" id="item_id"/>
                <span class="formNote">UOM</span>
                <select name="uom" id='uom' class="validate[required]" >
                      <option value=''>Select UOM</option>
                </select>
                <div class="clear"></div>
                <span class="formNote">Price ($)</span>
                <input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price"/>
                <span class="formNote">Qty</span>
                <input type="text" name="qty" id='qty' class="validate[required]"  />
                <input type="hidden" id="is_edit" value='0'/>
                <input type="hidden" id="note" value=''/>
                  <input type="hidden" id="sort" value=''/>
            </form>
        </div>
   </div>
</div>
</main>

   <script type="text/javascript" >
   	function resetForm($form) {
    $form.find('input:text, input:password, input:file, select, textarea').val('');
    $form.find('input:radio, input:checkbox')
         .removeAttr('checked').removeAttr('selected');
    $form.find('#sort').val(getmaxsort());
	}
	
		function getmaxsort()
		{
			var sorts = [];
			$( "#item_body .sorts" ).each(function(index ) {
			  sorts.push($(this).val());
			});
			
			console.log(sorts);
			if(sorts == null)
			{
				return 0;
			}
			else
			{
					return Math.max.apply( Math, sorts ) + 1;
			}
			
		}
	
	var current_edit_row = '';
   	$(function() {
	   		$( "#dialog-message" ).dialog({
				autoOpen: false,
				modal: true,
				buttons: {
					Ok: function() {
						if($("#item").validationEngine('validate') ==true)
						{
							if($('#is_edit').val() == 1)
							{
								edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val() ,$('#note').val(),$('#sort').val());
							}
							else
							{
								additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(),$('#sort').val() );
							}
							$( this ).dialog( "close" );
							resetForm($('#item'));
							 
						}
					}
				}
			});
			
				$('#opener').click(function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});	

		$(document).on("click", "a.edit",function() {
			$( "#dialog-message" ).dialog( "open" );
			current_edit_row =$(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});	
		
		function set_edit(row)
		{
			$( "#dialog-message" ).dialog( "option", "title", "Edit Item" );
			$('#is_edit').val(1);
			var item_id = $(row).attr('name').substr(5, ($(row).attr('name').length - 6));
			var item_name = jQuery.trim($(row).find('td').eq(1).clone().children().remove().end().text()).replace(item_id+' - ','');
			var note = $(row).find('textarea').eq(0).val();
			var qty = $(row).find(':input:hidden').eq(0).val();
			var unit_price = $(row).find(':input:hidden').eq(1).val();
			var uom = $(row).find(':input:hidden').eq(2).val();
			var total_price = $(row).find(':input:hidden').eq(3).val();
			var sort = $(row).find(':input:hidden').eq(4).val();
			
			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);

			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);
			$('#item #sort').val(sort);
				
			getoumedit(item_id,uom,unit_price);

		}
		
	function getoumedit(item_id,unit_number,price)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option[value='+unit_number+']').attr('selected','selected');
		     	$('#uniform-uom span').html(unit_number);
		     	$('#price').val(price);
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function edititem(item_id,item_desc,uom,price,qty,note,sort)
	{
		var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea rows="1" cols="" name="item['+item_id+'][note][]">'+note+'</textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty][]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price][]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom][]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price][]" value="'+total_price+'"/>'
					+ '<input type="hidden" class="sorts" name="item['+item_id+'][sort][]" value="'+sort+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a>';
		
		current_edit_row.replaceWith(str);
		
	}
	  
	  $( ".dialog #item_input" ).autocomplete({
	source: '/item/index/',
	minLength: 2,
	focus: function( event, ui ) {
				$( "#item_input" ).val( ui.item.item_desc );
				return false;
		},
	select: function( event, ui ) {
		$( "#item_input" ).val( ui.item.item_desc );
		$( "#item_id ").val( ui.item.item_id );
		getoum(ui.item.item_id );
		$('#uom').removeAttr('disabled');
		$('#uniform-uom').removeClass('disabled');
		 return false; 
		}
	}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>" + item.item_id + "<br>" + item.item_desc + "</a>" )
				.appendTo( ul );
	};
	function getoum(item_id)
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/uom/id/'+$( "#item_id ").val(),
		  type: "get",
		  success: function(data) {
		  	 var uom = jQuery.parseJSON(data);
		  	 var list = '';
		     $.each(uom, function(i, item) {
		     		list = list + '<option value="'+item.uom+'">'+item.uom+'</option>';
		     	});
		     	$('#uom').html(list);
		     	$('#uom option').eq(0).attr("selected", "selected"); 
		     	$('#uniform-uom span').html(uom[0].uom);
		     	getprice();
		     	$('.loading').hide();
		  }
		});
		
	}
	
	function getprice()
	{
		$('.loading').show();
		$.ajax({
		  url: '/item/price/id/'+$( "#item_id ").val()+'/uom/'+$( "#uom ").val(),
		  type: "get",
		  success: function(data) {
		  	 var price = jQuery.parseJSON(data);
		  		$('#price').val(price.price);
		  		$('.loading').hide();
		  }
		});
		
	}
	
	function additem(item_id,item_desc,uom,price,qty,sort)
	{
			var total_price = (price * qty).toFixed(2);
		var str = '<tr name="item['+item_id+']">'+'<td><input type="checkbox"'+ 'name="item['+item_id+']"/></td>' + '<td>'+item_id+'<br/>'+item_desc+'<br/><textarea rows="1" cols="" name="item['+item_id+'][note][]"></textarea></td>' + '<td>'+qty+'</td>' + '<td>'+price+'</td>' + '<td>'+uom+'</td>' + '<td>'+total_price+'</td>'
					+ '<input type="hidden" name="item['+item_id+'][qty][]" value="'+qty+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][unit_price][]" value="'+price+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][uom][]" value="'+uom+'"/>'
					+ '<input type="hidden" name="item['+item_id+'][total_price][]" value="'+total_price+'"/>'
					+ '<input type="hidden" class="sorts" name="item['+item_id+'][sort][]" value="'+sort+'"/>'
					+ '<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>';
		
		$('#item_body').append(str);
		
	}
	function getcustomerbyid(id)
	{
		$('.loading').show();
		$.ajax({
		  url: '/customer/fetchbyid/id/'+id,
		  type: "get",
		  success: function(data) {
		  	 var result = jQuery.parseJSON(data);
		  	 if(result != null)
		  	 {
		  		$('#quote').val(result.name);
		  		$('#customer_id').val(id);
		  		$('#address').val(result.phys_address1 + ' ' + result.phys_address2 + ' '+ result.phys_city + ' '+result.mail_state+ ' '+ result.phys_country+' ' + result.mail_postal_code);
		  		$('#tel').val(result.tel);
		  		$('#contact').val(result.fullname);
		  		$('#customer_email').val(result.email);
		  		$('#sale_rep').val(result.sale_rep);
		  		
		  	}
		  	else
		  		{
		  			alert('Can\'t find customer');
		  			$('#customer_info input').val('');
		  		}
		  	$('.loading').hide();
		  }
		});
	}
	  $('#add_new_mode').click(function(){
        $('#quote,#address, #tel').removeAttr('readonly').val('');
        $('#customer_id').attr('readonly','readonly').val('');
        $('#contact,#customer_email').val('');
        $('#quote, #address, #tel,#customer_email').addClass('validate[required]');
  			$('#add_new_mode').hide();
  			$('#discard_new_mode').show();
  	});
  	$('#discard_new_mode').click(function(){
        $('#address, #tel').attr('readonly','readonly').val('');
        $('#quote').val('');
        $('#customer_id').removeAttr('readonly').val('');
        $('#contact,#customer_email').val('');
        $('#quote, #address, #tel,#customer_email').removeClass('validate[required]');
  			$('#add_new_mode').show();
  			$('#discard_new_mode').hide();
  	});
	
  	$("#uom,#uniform-uom").change(function(){
        getprice();
        return false;
  	});
  	$("#item_body .delete").live('click',function(e){
       $(this).parent().parent().remove();
       e.preventDefault();
  	});
  	
  	$( "#customer_email" ).autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>" + item.email + "<br>" + item.first_name+' ' + item.last_name + "</a>" )
				.appendTo( ul );
		};
		
		$( "#quote" ).autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
				.appendTo( ul );
		};
		
		$( "#contact" ).autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function( event, ul ) {
				getcustomerbyid(ul.item.customer_id);
			},
			
		}).data( "autocomplete" )._renderItem = function( ul, item ) {
			return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( "<a>Company: "  + item.name +  "<br>" + item.fullname + ' ' + item.city+ ' '+ item.tel+"</a>" )
				.appendTo( ul );
		};
		
		$('a.save_quote').click(function(e){
			
				e.preventDefault();
				if($("#quote_content").validationEngine('validate') ==true)
				{
					$('.loading').show();
	  			$('#quote_content').submit();
	  		}
  		
  	});
  });
   	</script>

	<!-- Right panel -->
<div>
</div>