<?php
$session =  Zend_Registry::get('session');
$project = $this->project;
?>

<!-- Title area -->
<main id="content" class="main-content">
	<div class="middleNav">
		<ul>
			<li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
				<ul class="mSub1">
					<li><a href="#" title="">Share user</a></li>
					<li><a href="#" title="">Show Teamworks</a></li>
				</ul>
			</li>

			<li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
				<ul class="mSub4">
					<li><a href="#" title="">Add</a></li>
					<li><a href="#" title="">Save</a></li>
					<li><a href="#" title="">Edit</a></li>
					<li><a href="#" title="">Delete</a></li>
				</ul>
			</li>
		</ul>
	</div>

	<div class="main-page-content">
		<header class="main-page-content-header">
			<h1>Project to quote</h1>
		</header>

		<section aria-labelledby="project-information" id="section1" data-nav="Project information" class="active">
			<h2>Project information</h2>
			<div class="widget-information">
				<div class="widget-table">
					<div class="project-information">
						<p>Project Name: <b><?= $project['project_name'] ?></b><br>
							Project Quote No: <b><?= $project['quote_no'] ?></b><br>
							Worksheet Owner: <b><?= $project['owner'] ?></b><br>
							Status: <b><?= $project['status_name'] ?></b><br>
							Due Date: <b><?= $project['due_date']->format('Y-m-d') ?></b>
						</p>
					</div>
				</div>
			</div>
		</section>

		<!-- Page statistics area -->
		<!-- Main content wrapper --
    
        <!-- Note -->
		<!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->

		<!-- Form -->
		<form action="/quote/save" method='post' class="form" id="quote_content">
			<section aria-labelledby="customer-information" id="section2" data-nav="Customer information">
				<h2>Customer Infomation</h2>
				<input type="hidden" name='project_id' value="<?= $project['project_id'] ?>" />
				<div class="widget-table" id="customer_info">
					<div class="title">
						<a href="javascript:void(0)" title="" class="button greenB" style="margin: 2px;" id="add_new_mode">
							<span>New Customer</span></a>
						<a href="javascript:void(0)" title="" class="button basic" style='display:none;' style="margin: 2px;" id="discard_new_mode">
							<span>Discard Adding</span>
						</a>
					</div>
					<div class="formRow">
						<div class="oneTwo required-field">
							<label for="quote">Quote To</label>
							<input type="text" value="" id='quote' name='name' class='tipN validate[required]' />
						</div>
						<div class="oneTwo required-field">
							<label for="address">Address</label>
							<input type="text" value="" id='address' name='phys_address1' readonly />
						</div>
						<div class="oneTwo required-field">
							<label for="tel">Phone Number</label>
							<input type="text" id='tel' name='phone' class="maskPhoneExt" value="" id='tel' name='tel' readonly />
						</div>
						<div class="oneTwo required-field">
							<label for="customer_id">Customer ID</label>
							<input name='customer_id' type="text" id='customer_id' class="validate[custom[integer]] tipN" value="" original-title="Leave blank for add new customer" readonly />
						</div>
						<div class="oneTwo required-field">
							<label for="contact">Contact</label>
							<input type="text" id='contact' name='fullname' class="validate[required] tipN" value="" original-title="Enter Customer Name to fetch existing customer" />
						</div>
						<div class="oneTwo required-field">
							<label for="customer_email">Email</label>
							<input type="text" value="" id='customer_email' name='Contacts_email' class="validate[custom[email]] tipN" original-title="Enter Customer Email to fetch existing customer">
						</div>
					</div>

				</div>
			</section>

			<section aria-labelledby="quote-information" id="section3" data-nav="Quote information">
				<h2>Quote Infomation</h2>
				<div class="widget-table">
					<div class="formRow">

						<div class="oneTwo">
							<label for="quote-number">Quote Number</label>
							<input id="quote-number" type="text" placeholder="Auto Generate" readonly />
						</div>
						<div class="oneTwo">
							<label for="quote_date">Quote Date</label>
							<input type="text" class="datepicker" id='quote_date' value='<?= date('Y-m-d') ?>' />
						</div>
						<div class="oneTwo">
							<label for="ship-required-date">Shipment Required Date</label>
							<input id="ship-required-date" type="text" class="datepicker" name='ship_required_date' value="<?php if ($project['required_date'] != null && $project['required_date']->format('Y-m-d') > '2000-01-01') echo $project['required_date']->format('Y-m-d'); ?>" />
						</div>
						<div class="oneTwo required-field">
							<label for="quote_type">Quote Type</label>
							<select name="quote_type_id" id="quote_type" class="validate[required]">
								<option value="">-- Select --</option>
								<?php foreach ($this->type as $t) { ?>
									<option value="<?= $t['uid'] ?>"><?= $t['type'] ?></option>
								<?php } ?>
							</select>
						</div>
						<div class="oneTwo">
							<label for="project-name">Project Name</label>
							<input id="project-name" type="text" value="<?= $project['project_name'] ?>" readonly />
						</div>
						<div class="oneTwo">
							<label for="project-location">Project Location</label>
							<input id="project-location" type="text" value="<?= $project['project_location_address'] ?>" readonly />
						</div>
						<div class="oneTwo">
							<label for="sale_rep">Sales Representative</label>
							<input id="sale_rep" type="text" value="<?= $session->user['name'] ?>" readonly />
						</div>
						<div class="oneTwo required-field">
							<label for="arch">Architect's Representative</label>
							<select id="arch" name='arch' class="validate[required]">
								<?php if ($session->user['approve_id'] != null) { ?>
									<?php foreach ($this->arch as $a) { ?>
										<option value="<?= $a['id'] ?>" <?php if ($a['id'] == $this->quote['arch']) echo 'selected'; ?>><?= $a['name'] . ' - ' . $a['default_company'] ?></option>
									<?php } ?>
								<?php } else { ?>
									<?php foreach ($this->arch as $a) { ?>
										<?php if ($a['id'] == $project['owner']) { ?><option value="<?= $a['id'] ?>" selected><?= $a['name'] . ' - ' . $a['default_company'] ?></option> <?php } ?>
									<?php } ?>
								<?php } ?>
							</select>
						</div>
						<input type="hidden" name="sales_id" value="<?= $session->user['id'] ?>" />

						<?php foreach ($this->seg as $s) { ?>
							<?php if ($s['uid'] == $project['market_segment']) $seg = $s['Market_Segment'] ?>
						<?php } ?>
						<div class="oneTwo required-field">
							<label for="Segment">Segment</label>
							<input type="text" original-title="Segment Format" name='quote_segment' id='Segment' class='validate[required] tipN' value="<?= $seg ?>" />
						</div>
						<div class="oneTwo required-field">
							<label for="quote_approval">Quote Approval</label>
							<select id="quote_approval">
								<option value="">Only approver can edit</option>
								<!--<?php foreach ($this->approval as $a) { ?>
                                <option value="<?= $a['uid'] ?>"><?= $a['Name'] . ' - ' . $a['Company_ID'] ?></option>
                             		 <?php } ?>-->
							</select>
						</div>
					</div>
				</div>
			</section>

			<section aria-labelledby="items" id="section4" data-nav="Items">
				<h2>Items</h2>
				<div class="widget-table">
					<a href="#" title="" class="button greenB" style="margin: 5px;" id="opener"><span>Add new Item</span></a>
					<table cellpadding="0" cellspacing="0" width="100%" class="sTable" id="items" style="text-align:center;">
						<thead>
							<tr>
								<td></td>
								<td width="50%">Item ID - Description</td>
								<td>Quality Quoted</td>
								<td>Unit Price</td>
								<td>Unit Of Measure</td>
								<td>Price Quoted</td>
								<td>Action</td>
							</tr>
						</thead>
						<tbody id="item_body">
							<?php foreach ($this->items as $i) { ?>
								<tr name="item[<?= $i['product_id'] ?>]">
									<td><input type="checkbox" name="item[<?= $i['product_id'] ?>]"></td>
									<td><?= $i['product_id'] ?> - <?= $i['item_desc'] ?>
										<textarea name="item[<?= $i['product_id'] ?>][note][]"><?= $i['note'] ?></textarea>
									</td>
									<td><?= $i['qty'] ?></td>
									<td><?= $i['unit_price'] ?></td>
									<td><?= $i['uom'] ?></td>
									<td><?= $i['subtotal'] ?></td>
									<input type="hidden" name="item[<?= $i['product_id'] ?>][qty][]" value="<?= $i['qty'] ?>"><input type="hidden" name="item[<?= $i['product_id'] ?>][unit_price][]" value="<?= $i['unit_price'] ?>">
									<input type="hidden" name="item[<?= $i['product_id'] ?>][uom][]" value="<?= $i['uom'] ?>"><input type="hidden" name="item[<?= $i['product_id'] ?>][total_price][]" value="<?= $i['subtotal'] ?>">
									<input type="hidden" class='sorts' name="item[<?= $i['product_id'] ?>][sort][]" value="<?= $i['sort_id'] ?>">
									<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>

								</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</section>

			<section aria-labelledby="comment" id="section5" data-nav="Comment">
				<h2>Comment</h2>
				<div class="widget-table">
					<div class="formRow">
						<div class="oneTwo">
							<label for="quote-note">Quote Note</label>
							<textarea id="quote-note" name="note" placeholder="Note area"></textarea>
						</div>
					</div>
				</div>
			</section>
		</form>

		<div id="dialog-message" title="Add Item">
			<div class="uiForm">
				<form action="" class="dialog" id='item'>
					<span class="formNote">Enter Item ID </span>
					<input type="text" name="item" id='item_input' class="validate[required]" />
					<input type="hidden" id="item_id" />
					<span class="formNote">UOM</span>
					<select name="uom" id='uom' class="validate[required]">
						<option value=''>Select UOM</option>
					</select>
					<div class="clear"></div>
					<span class="formNote">Price ($)</span>
					<input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="You can override the price" />
					<span class="formNote">Qty</span>
					<input type="text" name="qty" id='qty' class="validate[required]" />
					<input type="hidden" id="is_edit" value='0' />
					<input type="hidden" id="note" value='' />
					<input type="hidden" id="sort" value='' />
				</form>
			</div>
		</div>
	</div>
</main>

<!-- Right panel -->
<div class="sidebar-container">
	<aside id="sidebar-quicklinks" class="sidebar">
		<nav aria-label="Actions" class="sidebar-inner">
			<div class="sidebar-inner-nav">
				<div class="quick-links">
					<ol>
						<!--<li><a href="#" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
						<!--<li><a href="#" title=""><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Current</span></a></li>-->
						<!--<li><a href="#" title=""><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Quote</span></a></li>-->
						<li><a class="quick-link save_quote" href="#" title="">
								<svg width="40" height="40" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
									<path d="M17 20.75H7C6.27065 20.75 5.57118 20.4603 5.05546 19.9445C4.53973 19.4288 4.25 18.7293 4.25 18V6C4.25 5.27065 4.53973 4.57118 5.05546 4.05546C5.57118 3.53973 6.27065 3.25 7 3.25H14.5C14.6988 3.25018 14.8895 3.32931 15.03 3.47L19.53 8C19.6707 8.14052 19.7498 8.33115 19.75 8.53V18C19.75 18.7293 19.4603 19.4288 18.9445 19.9445C18.4288 20.4603 17.7293 20.75 17 20.75ZM7 4.75C6.66848 4.75 6.35054 4.8817 6.11612 5.11612C5.8817 5.35054 5.75 5.66848 5.75 6V18C5.75 18.3315 5.8817 18.6495 6.11612 18.8839C6.35054 19.1183 6.66848 19.25 7 19.25H17C17.3315 19.25 17.6495 19.1183 17.8839 18.8839C18.1183 18.6495 18.25 18.3315 18.25 18V8.81L14.19 4.75H7Z" />
									<path d="M16.75 20H15.25V13.75H8.75V20H7.25V13.5C7.25 13.1685 7.3817 12.8505 7.61612 12.6161C7.85054 12.3817 8.16848 12.25 8.5 12.25H15.5C15.8315 12.25 16.1495 12.3817 16.3839 12.6161C16.6183 12.8505 16.75 13.1685 16.75 13.5V20Z" />
									<path d="M12.47 8.75H8.53001C8.3606 8.74869 8.19311 8.71403 8.0371 8.64799C7.88109 8.58195 7.73962 8.48582 7.62076 8.36511C7.5019 8.24439 7.40798 8.10144 7.34437 7.94443C7.28075 7.78741 7.24869 7.61941 7.25001 7.45V4H8.75001V7.25H12.25V4H13.75V7.45C13.7513 7.61941 13.7193 7.78741 13.6557 7.94443C13.592 8.10144 13.4981 8.24439 13.3793 8.36511C13.2604 8.48582 13.1189 8.58195 12.9629 8.64799C12.8069 8.71403 12.6394 8.74869 12.47 8.75Z" />
								</svg>
							Save Quote</a></li>
						<!--<li><a href="#" title=""><img src="/images/icons/control/32/mail.png" alt="" /><span>Email Quote</span></a></li>
                    <li><a href="#" title=""><img src="/images/icons/control/32/delete.png" alt="" /><span>Delete Quote</span></a></li>-->
					</ol>
				</div>
			</div>
		</nav>
	</aside>
</div>

<script type="text/javascript">

	function resetForm($form) {
		$form.find('input:text, input:password, input:file, select, textarea').val('');
		$form.find('input:radio, input:checkbox')
			.prop('checked', false).prop('selected', false);
		$form.find('#sort').val(getmaxsort());
	}

	function getmaxsort() {
		var sorts = [];
		$("#item_body .sorts").each(function(index) {
			sorts.push($(this).val());
		});

		console.log(sorts);
		if (sorts == null) {
			return 0;
		} else {
			return Math.max.apply(Math, sorts) + 1;
		}

	}

	var current_edit_row = '';
	$(function() {
		$("#dialog-message").dialog({
			autoOpen: false,
			modal: true,
			buttons: {
				Ok: function() {
					if ($("#item").validationEngine('validate') == true) {
						if ($('#is_edit').val() == 1) {
							edititem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#note').val(), $('#sort').val());
						} else {
							additem($('#item_id').val(), $('#item_input').val(), $('#uom').val(), $('#price').val(), $('#qty').val(), $('#sort').val());
						}
						$(this).dialog("close");
						resetForm($('#item'));

					}
				}
			}
		});

		$('#opener').on("click", function() {
			resetForm($('#item'));
			$('#is_edit').val(0);
			return false;
		});

		$(document).on("click", "a.edit", function() {
			$("#dialog-message").dialog("open");
			current_edit_row = $(this).closest('tr');
			set_edit(current_edit_row);
			return false;
		});

		function set_edit(row) {
			$("#dialog-message").dialog("option", "title", "Edit Item");
			$('#is_edit').val(1);
			var item_id = $(row).attr('name').substr(5, ($(row).attr('name').length - 6));
			var item_name = jQuery.trim($(row).find('td').eq(1).clone().children().remove().end().text()).replace(item_id + ' - ', '');
			var note = $(row).find('textarea').eq(0).val();
			var qty = $(row).find(':input:hidden').eq(0).val();
			var unit_price = $(row).find(':input:hidden').eq(1).val();
			var uom = $(row).find(':input:hidden').eq(2).val();
			var total_price = $(row).find(':input:hidden').eq(3).val();
			var sort = $(row).find(':input:hidden').eq(4).val();

			$('#item #item_input').val(item_name);
			$('#item #item_id').val(item_id);

			$('#item #price').val(unit_price);
			$('#item #qty').val(qty);
			$('#item #note').val(note);
			$('#item #sort').val(sort);

			getoumedit(item_id, uom, unit_price);

		}

		function getoumedit(item_id, unit_number, price) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = jQuery.parseJSON(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option[value=' + unit_number + ']').attr('selected', 'selected');
					$('#uniform-uom span').html(unit_number);
					$('#price').val(price);
					$('.loading').hide();
				}
			});

		}

		function edititem(item_id, item_desc, uom, price, qty, note, sort) {
			var total_price = (price * qty).toFixed(2);
			var str = '<tr name="item[' + item_id + ']">' + '<td><input type="checkbox"' + 'name="item[' + item_id + ']"/></td>' + '<td>' + item_id + '<br/>' + item_desc + '<br/><textarea rows="1" cols="" name="item[' + item_id + '][note][]">' + note + '</textarea></td>' + '<td>' + qty + '</td>' + '<td>' + price + '</td>' + '<td>' + uom + '</td>' + '<td>' + total_price + '</td>' +
				'<input type="hidden" name="item[' + item_id + '][qty][]" value="' + qty + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][unit_price][]" value="' + price + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][uom][]" value="' + uom + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][total_price][]" value="' + total_price + '"/>' +
				'<input type="hidden" class="sorts" name="item[' + item_id + '][sort][]" value="' + sort + '"/>' +
				'<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a>';

			current_edit_row.replaceWith(str);

		}

		$(".dialog #item_input").autocomplete({
			source: '/item/index/',
			minLength: 2,
			focus: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				return false;
			},
			select: function(event, ui) {
				$("#item_input").val(ui.item.item_desc);
				$("#item_id ").val(ui.item.item_id);
				getoum(ui.item.item_id);
				$('#uom').prop('disabled', false);
				$('#uniform-uom').removeClass('disabled');
				return false;
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.item_id + "<br>" + item.item_desc + "</a>")
				.appendTo(ul);
		};

		function getoum(item_id) {
			$('.loading').show();
			$.ajax({
				url: '/item/uom/id/' + $("#item_id ").val(),
				type: "get",
				success: function(data) {
					var uom = jQuery.parseJSON(data);
					var list = '';
					$.each(uom, function(i, item) {
						list = list + '<option value="' + item.uom + '">' + item.uom + '</option>';
					});
					$('#uom').html(list);
					$('#uom option').eq(0).attr("selected", "selected");
					$('#uniform-uom span').html(uom[0].uom);
					getprice();
					$('.loading').hide();
				}
			});

		}

		function getprice() {
			$('.loading').show();
			$.ajax({
				url: '/item/price/id/' + $("#item_id ").val() + '/uom/' + $("#uom ").val(),
				type: "get",
				success: function(data) {
					var price = jQuery.parseJSON(data);
					$('#price').val(price.price);
					$('.loading').hide();
				}
			});

		}

		function additem(item_id, item_desc, uom, price, qty, sort) {
			var total_price = (price * qty).toFixed(2);
			var str = '<tr name="item[' + item_id + ']">' + '<td><input type="checkbox"' + 'name="item[' + item_id + ']"/></td>' + '<td>' + item_id + '<br/>' + item_desc + '<br/><textarea rows="1" cols="" name="item[' + item_id + '][note][]"></textarea></td>' + '<td>' + qty + '</td>' + '<td>' + price + '</td>' + '<td>' + uom + '</td>' + '<td>' + total_price + '</td>' +
				'<input type="hidden" name="item[' + item_id + '][qty][]" value="' + qty + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][unit_price][]" value="' + price + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][uom][]" value="' + uom + '"/>' +
				'<input type="hidden" name="item[' + item_id + '][total_price][]" value="' + total_price + '"/>' +
				'<input type="hidden" class="sorts" name="item[' + item_id + '][sort][]" value="' + sort + '"/>' +
				'<td><a class="edit" href="#"><img src="/images/icons/dark/pencil.png" alt="edit"></a><a class="delete" href="#"><img src="/images/icons/dark/close.png" alt="delete"></a></td>';

			$('#item_body').append(str);

		}

		function getcustomerbyid(id) {
			$('.loading').show();
			$.ajax({
				url: '/customer/fetchbyid/id/' + id,
				type: "get",
				success: function(data) {
					var result = jQuery.parseJSON(data);
					if (result != null) {
						$('#quote').val(result.name);
						$('#customer_id').val(id);
						$('#address').val(result.phys_address1 + ' ' + result.phys_address2 + ' ' + result.phys_city + ' ' + result.mail_state + ' ' + result.phys_country + ' ' + result.mail_postal_code);
						$('#tel').val(result.tel);
						$('#contact').val(result.fullname);
						$('#customer_email').val(result.email);
						$('#sale_rep').val(result.sale_rep);

					} else {
						alert('Can\'t find customer');
						$('#customer_info input').val('');
					}
					$('.loading').hide();
				}
			});
		}
		$('#add_new_mode').on("click", function() {
			$('#quote,#address, #tel').prop('readonly', false).val('');
			$('#customer_id').attr('readonly', 'readonly').val('');
			$('#contact,#customer_email').val('');
			$('#quote, #address, #tel,#customer_email').addClass('validate[required]');
			$('#add_new_mode').hide();
			$('#discard_new_mode').show();
		});
		$('#discard_new_mode').on("click", function() {
			$('#address, #tel').attr('readonly', 'readonly').val('');
			$('#quote').val('');
			$('#customer_id').prop('readonly', false).val('');
			$('#contact,#customer_email').val('');
			$('#quote, #address, #tel,#customer_email').removeClass('validate[required]');
			$('#add_new_mode').show();
			$('#discard_new_mode').hide();
		});

		$("#uom,#uniform-uom").on("change", function() {
			getprice();
			return false;
		});

		$(document).on("click", "#item_body .delete", function(e) {
			$(this).parent().parent().remove();
			e.preventDefault();
		});

		$("#customer_email").autocomplete({
			source: "/customer/email/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.email + "<br>" + item.first_name + ' ' + item.last_name + "</a>")
				.appendTo(ul);
		};

		$("#quote").autocomplete({
			source: "/customer/quote/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			}
		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		$("#contact").autocomplete({
			source: "/customer/name/",
			minLength: 2,
			select: function(event, ul) {
				getcustomerbyid(ul.item.customer_id);
			},

		}).data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>Company: " + item.name + "<br>" + item.fullname + ' ' + item.city + ' ' + item.tel + "</a>")
				.appendTo(ul);
		};

		$('a.save_quote').on("click", function(e) {

			e.preventDefault();
			if ($("#quote_content").validationEngine('validate') == true) {
				$('.loading').show();
				$('#quote_content').submit();
			}

		});
	});
</script>