<script type="text/php">
if ( isset($pdf) ) {

	//header and footer
  $obj = $pdf->open_object();

 	$w = $pdf->get_width();
  $h = $pdf->get_height();
  $font = $fontMetrics->getFont("helvetica", "bold");
  $size = 8;
  $y1 = $pdf->get_height() - 36;
  $x = 15 ;
  $pageText1 = 'TORONTO | VANCOUVER | CALGARY | EDMONTON | LONDON | WINDSOR | HAMILTON | PETERBOROUGH';
  $w1 = $fontMetrics->get_text_width($pageText1, $font, $size);
  $pdf->page_text(($w -$w1) / 2, $y1, $pageText1, $font,  $size);
  
  $y2 = $pdf->get_height() - 24;
  $pageText2 = 'OTTWA | MONTREAL | QUEBEC CITY | HALIFAX | MONCTON';
  $w2 = $fontMetrics->get_text_width($pageText2, $font, $size);
  $pdf->page_text(($w -$w2) / 2, $y2, $pageText2, $font,  $size);
  $pdf->page_text($w - 48, $y2, "{PAGE_NUM} of {PAGE_COUNT}", $font, $size, array(0,0,0));
  
   // Add a logo
  $image = 'http://newstatic.centura.local/'.'/images/printlogo.png';
$img_w = 54; // 2 inches, in points
  $img_h = 9; // 1 inch, in points -- change these as required
  $pdf->image($image, "png", null, null, $img_w, $img_h);
  
   // add text top 1
  $top1_y = 4;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = '950 LAWRENCE AVENUE WEST';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
  // add text top 2
  $top1_y = 12;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'TORONTO, ONTARIO, CANADA M6A 1C4';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
   // add text top 2
  $top1_y = 20;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'ORDER DESK: 416-785-5151';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
   
   // add text 
  $top1_y = 28;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'OFFICE: 416-785-5165';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
    
   // add text 
  $top1_y = 36;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'WATTS: 1-800-263-9400';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
    // add text 
  $top1_y = 44;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'FAX: 416-783-0636';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
    // add text 
  $top1_y = 52;
  $top_size = 6;
  $top_font = $fontMetrics->getFont("helvetica", "normal");
  $top_text1 = 'www.centura.ca';
  $top_text1_width = $fontMetrics->get_text_width($top_text1, $top_font, $top_size);
  $pdf->page_text($w -$top_text1_width -  4, $top1_y, $top_text1, $top_font,  $top_size);
  
  
  // Close the object (stop capture)
  $pdf->close_object();
  $pdf->add_object($obj, 'all');


}
</script>

<style media='print' type="text/css">
	@page :even{
  margin-top: 6em;
  margin-bottom: 3em;
}
@page :first{
  margin-top: 4em;
  margin-bottom: 3em;
}
@page :odd{
  margin-top: 6em;
  margin-bottom: 3em;
}

#hiderow, .hiderow, .delete {
  display: none;
}
.break {padding-left:1em;}
 div.footer {
            position: fixed;
            bottom: 0;
        }
body{padding-bottom:20px;}
	#header {font-size:18px;height:30px;line-height:26px; font-family:Arial;font-weight:bold;}
	#info,#items {border:1px solid grey; margin:10px 0px;}
	#items th,#items td{border:1px solid grey; text-align:center}
	#info th,#info td{border:1px solid grey;}
	#info .th { background: #eee; font-weight:bold; }
	#items th { background: #eee; font-weight:bold; }
	.bot_note{font-weight:bold;}
#total th,#total td{border:none;}
#footer th,#footer td{border:none;}
ul li {list-style-type: square;margin-left:12px;}
</style>
<?php $quote = $this->quote; $project=$this->project;$customer = $this->customer; $type=$this->type?> 
<?php $this->headTitle('Quote For '.$project['project_name'].' - Centura','SET')?>
<div id="page-wrap">
<div id="hiderow" style='text-align:center'>
	<span style='font-size:12px;font-weight:bold;'>Notice:  Please Use IE or FireFox to Print.</span><br/>
			<a href='javascript:print()'>Print Quote</a>   <a href='/quote/edit/id/<?=$quote['quote_id']?>'>Back Quote</a> <a href='/'>Back Dashboard</a><br/>
	</div>

<div id='header'>PRICE QUOTE</div>
   <table id="meta">
   	<tbody>
          <tr>
              <td class="meta-head" width='20%' ><strong>Quote To:</strong></td>
              <td style='font-weight:normal'><?=$customer['name']?></td>
          </tr>
        	<tr>
              <td class="meta-head" width='20%'></td>
              <td><?=$customer['phys_address1']?> <?=$customer['phys_address2']?><br/>
              	<?=$customer['phys_city']?>, <?=$customer['mail_state']?> <?=$customer['mail_postal_code']?><br/>
              	<?=$customer['phys_country']?>
              </td>
          </tr>
          <tr >
              <td class="meta-head" width='20%'></td>
              <td><textarea id="date" ><?=$customer['tel']?></textarea></td>
          </tr>
          <tr >
              <td class="meta-head" width='20%' ><strong>Contact</strong></td>
              <td ><?=$customer['fullname']?></td>
          </tr>
          <tr>
              <td class="meta-head" width='20%'><strong>Email</strong></td>
              <td ><?=$customer['email']?></td>
          </tr>
          <tr>
              <td class="meta-head bold" width='20%' ><strong>Customer ID:</strong></td>
              <td><?=$customer['customer_id']?></td>
          </tr>

     </tbody>   
   </table>
		<table id="info" width="100%">
		  <tr>
		      <th width="15%">Quote Number</th>
		      <th width="15%">Quote Date</th>
		      <th width="20%">Quote Expiry</th>
		      <th width="20%">Ship Required Date</th>
		      <th width="17.5%">Specifier</th>
		      <th width="12.5%">Page</th>
		  </tr>
		  <tr>
		  	<td><?=$quote['quote_id']?></td>
		  	<td><?=$quote['quote_date']->format('Y-m-d')?></td>
		  	<td><?=$quote['expire_date']->format('Y-m-d')?></td>
		  	<td><?php if($quote['ship_required_date']!= null && $quote['ship_required_date']->format('Y-m-d') > '2000-01-01' ) {echo $quote['ship_required_date']->format('Y-m-d');}?></td>
		 
		  	<td><?=$this->spec_name ?></td>
		  	<td class='counter'><?=1 + ceil((count($this->items) - 8) / 14)?></td>
		  </tr>
		  <tr>
		  	<td class='th' colspan="2">Project Name</td>
		  	<td class='th' colspan="1">Project Location</td>
		  	<td class='th'>Quote Approval by</td>
		  	<td class='th'>Sales Rep</td>
		  	<td class='th'>Arch Rep</td>
		  </tr>
		  <tr>
		  	<td colspan="2"><?=$project['project_name']?></td>
		  	<td colspan="1">
		  		<?php foreach($this->locations as $l) {?>
                   <?php if($l['location_id'] == $project['centura_location_id']) echo $l['name'] ;?>
            <?php } ?>
        </td>
		  	<td> <?php foreach($this->approval as $a) {?>
              <?php if($a['uid'] == $quote['quote_approval']) echo $a['Name'].' - '.$a['Company_ID'];?>
             <?php }?>
        </td>
		  	<td><?=$customer['sale_rep']?>
        </td>
		  	<td>  <?php foreach($this->arch as $a) {?>
            <?php if($a['id'] == $quote['arch']) echo $a['name'].' - '.$a['default_company'];?><?php }?>
        </td>
		  </tr>
		</table>
		
		<table id="items" width='100%'>
		  <thead>
		  		<tr>
		      <th style="text-align:left" width="60%">Item ID<br/><span class='break'>Item Description</span><br/><span class='break'>Quote Line Note</span></th>
		      <th style="text-align:center" width="13%">Quantity Quoted</th>
		      <th style="text-align:center"  width="13%">Unit Price</th>
		      <th style="text-align:center"  width="13%">Unit of Measure</th>
		      <th style="text-align:center"  width="13%">Price Quoted</th>
		   	 </tr>
		  </thead>
		  <tbody>
       <?php $subtotal =0; foreach ($this->items as $i) { ?>
     		<tr>
     			<td style="text-align:left"><?=$i['product_id']?><br/><span class='break'><?=$i['item_desc'] ?></span><br/><span class='break'>
     		<?=' '.$i['note']?></span>
     		  </td>
     		  <td><?=$i['qty']?></td>
     		  <td><?='$'.$i['unit_price']?></td>
     		  <td><?=$i['uom']?></td>
     		  <td><?='$'.$i['subtotal']?></td>
     		</tr>
      <?php $subtotal += $i['subtotal'] == null ? 0 : $i['subtotal'] ;}?>
      <tr>
     			<td colspan='4' style='text-align:right'><strong>Sub-Total: </strong></td>
     			<td><?='$'.number_format($subtotal,2) ?></td>
     	</tr>
   </tbody>
		</table>
	<div class='total_line'>Total Lines: <?=count($this->items)?></div>
	<table id="total" width='100%'>
	<tr>
		<td>
			<div id="terms" style='text-align:left'>
			<div class='bot_note'>Note to Quote:</div>
			<div  style='font-weight:normal'>Credit Terms: <?=$quote['term']?></div>
			<div  style='font-weight:normal'>Lead Time:  <?php foreach($this->leadtime as $a) {?>
				                                <?php if($this->quote['lead_time'] == $a['uid']) {echo $a['description'];}?>
				                             		 <?php }?></div>
		  <div  style='font-weight:normal'><?=$quote['note']?></div>
		</div>
		</td>
	</tr>
</table>

<table id="footer" width='100%'>
			<tr>
				<td>
			 <ul>
			 	<li>TO ENSURE CORRECT PROJECT PRICING PLEASE INCLUDE THE QUOTE NUMBER ON YOUR P.O. AND WHEN PLACING YOUR ORDER.</li>
				<li>PRODUCT FOB CENTURA TORONTO UNLESS OTHERWISE NOTED.</li>
				<li>ALL SIZES ARE NOMINAL AND ARE SUBJECT TO MINOR VARIANCES ACCORDING TO MANUFACTURING PROCESS.</li>
				<li>PLEASE NOTE THIS QUOTATION WILL EXPIRE ON DECEMBER 31ST OF THE CURRENT YEAR UNLESS OTHERWISE SPECIFIED.</li>
			</ul>
			<div style="font-size:16px;font-weight:bold;">Visit us at: www.centura.ca</div>
			</td>
			</tr>
</table>
</div>
	