<?php $session = Zend_Registry::get('session');
//$b = $this->ownproject;
?>
<!-- Left panel -->
<div class="sidebar-container">
    <div class="toc-container">
        <aside class="toc">
            <nav>
                <div class="document-toc-container">
                    <section class="document-toc">
                        <header>
                            <h2 class="document-toc-heading">On this page</h2>
                        </header>
                        <ul id="document-toc-list" class="document-toc-list">
                            <!--<li class="document-toc-item">
                            <a class="document-toc-link" href="#all_quotes">All quotes</a>
                        </li>
                        <li class="document-toc-item">
                            <a class="document-toc-link" href="#all_projects">All projects</a>
                        </li>-->
                        </ul>
                    </section>
                </div>
            </nav>
        </aside>
        <section class="place side"></section>
    </div>
</div>
<!-- Title area -->
<main id="content" class="main-content">

    <div class="middleNav">
        <ul>
            <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                <ul class="mSub1">
                    <li><a href="#" title="">Share user</a></li>
                    <li><a href="#" title="">Show Teamworks</a></li>
                </ul>
            </li>

            <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                <ul class="mSub4">
                    <li><a href="#" title="">Add</a></li>
                    <li><a href="#" title="">Save</a></li>
                    <li><a href="#" title="">Edit</a></li>
                    <li><a href="#" title="">Delete</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="main-page-content">
        <header class="main-page-content-header">
            <h1>All Quotes and Projects</h1>
        </header>
        <div class="section-content">
            <p>IT Administrator landing page.</p>
        </div>

        <!-- Form -->
        <section aria-labelledby="all_quotes" id="section1" data-nav="All Quotes" class="active">
            <h2>All Quotes</h2>
            <div class="widget-table">
                <table width="100%" class="display nowrap" id='quote_table'>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Project Name</th>
                            <th>Quote Seg</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Project Status</th>
                            <th>Approval Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>
        <section aria-labelledby="all_projects" id="section2" data-nav="All Projects">
            <h2>All Projects</h2>
            <div class="widget-table">
                <table width="100%" class="display nowrap" id="project_table">
                    <thead>
                        <tr>
                            <th>Project #</th>
                            <th>Quote #</th>
                            <th>Project Name</th>
                            <th>Project Owner</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Specifier</th>
                            <th>Market Segment</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>



        <!--<div class="line"></div>-->



        <!--
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<!--<li><a href="/quote" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
        <!-- <li><a href="#" title=""><img src="images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/delete.png" alt="" /><span>Delete Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>

    </div>
    -->
    </div>
</main>

<!-- Right panel -->
<div class="sidebar-container">
    <aside id="sidebar-quicklinks" class="sidebar">
        <nav aria-label="Actions" class="sidebar-inner">
            <div class="sidebar-inner-nav">
                <div class="quick-links">
                    <ol>
                        <li><a href="/project/" class='quick-link add-project' title="Add new project">
                                <svg class="icon-action" width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M4 12H20M12 4V20" stroke="#2D75C3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                Add Project</a></li>
                        <li><a href="#" class='quick-link edit-project' title="Edit project">
                                <svg class="icon-action" width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M14.4443 5.68747L5.44587 14.6859C4.78722 15.3446 4.26719 16.1441 4.10888 17.062C3.94903 17.9888 3.89583 19.139 4.44432 19.6875C4.99281 20.236 6.14299 20.1828 7.0698 20.0229C7.98772 19.8646 8.78722 19.3446 9.44587 18.6859L18.4443 9.68747M14.4443 5.68747C14.4443 5.68747 17.4443 2.68747 19.4443 4.68747C21.4443 6.68747 18.4443 9.68747 18.4443 9.68747M14.4443 5.68747L18.4443 9.68747" stroke="#2D75C3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                Edit Project
                            </a></li>
                        <li><a href="#" class='quick-link update-project' title="Update project">
                                <svg class="icon-action" width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M3 3V9M3 9H9M3 9C5.32744 6.91141 7.48287 4.54676 10.7453 4.08779C12.6777 3.81593 14.6461 4.17941 16.3539 5.12343C18.0617 6.06746 19.4164 7.54091 20.2139 9.32177M21 21V15M21 15H15M21 15C18.6725 17.0886 16.5171 19.4532 13.2547 19.9122C11.3223 20.1841 9.35391 19.8206 7.6461 18.8766C5.93829 17.9325 4.58356 16.4591 3.78604 14.6782" stroke="#2D75C3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                Update Project</a></li>
                        <li><a href="#" class='quick-link save-project' title="Save project">
                                <svg class="icon-action" width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M15 19.8935C17.1722 19.7353 18.799 19.4232 19.1111 19.1111C19.5556 18.6667 20 15.5556 20 12C20 11.3687 19.9621 10.4239 19.9316 9.76377C19.9088 9.27176 19.7009 8.80741 19.3526 8.45914L15.5409 4.6474C15.1926 4.29913 14.7282 4.09124 14.2362 4.06844C13.5761 4.03786 12.6313 4 12 4C8.44444 4 5.33333 4.44444 4.88889 4.88889C4.44444 5.33333 4 8.44444 4 12C4 15.5556 4.44444 18.6667 4.88889 19.1111C5.20096 19.4232 6.82776 19.7353 9 19.8935M15 19.8935C14.0786 19.9606 13.059 20 12 20C10.941 20 9.92143 19.9606 9 19.8935M15 19.8935V18C15 18 15 15 12 15C9 15 9 18 9 18V19.8935" stroke="#2D75C3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                Save Project</a></li>
                        <li><a href="#" class='quick-link delete-project' title="Delete project">
                                <svg class="icon-action" width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.99999 6C5.99999 11.8587 4.63107 20 12 20C19.3689 20 18 11.8587 18 6M4 6H20M15 6V5C15 3.22496 13.3627 3 12 3C10.6373 3 9 3.22496 9 5V6" stroke="#2D75C3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                Delete Project</a></li>
                    </ol>
                </div>
            </div>
        </nav>
    </aside>
</div>

<script type="text/javascript">
    const items = ["All Quotes", "All Projects"];
    createTocList(items);

    let sessionUser = "<?php echo $session->user['id']?>";

    oTable = $('#project_table,#asso_table').dataTable({
        "ajax": {
            "url": "/index/project",
            "dataSrc": ''
        },
        "columns": [
            {"data": "project_id", "createdCell": function(cell, cellData, rowData, rowIndex, colIndex) {
                if(rowData.owner == sessionUser) { $(cell).html("<a target='_blank' href='/project/edit/id/"+rowData.project_id+"'>"+rowData.project_id+"</a>");}
                else { $(cell).html("<a target='_blank' href='/project/view/id/"+rowData.project_id+"'>"+rowData.project_id+"</a>");}
            } },
            {"data": "quote_no"},
            {"data": "project_name"},
            {"data": "owner"},
            {"data": "create_date.date"},
            {"data": "due_date.date", "createdCell": function(cell, cellData, rowData, rowIndex, colIndex) {
                let d = new Date(cellData);
                let today = new Date(); 
                if (d <= today) {$(cell).addClass("red");}
            }},
            {"data": "Specifier_name"},
            {"data": "segment"},
            {"data": "status_name"},
            {"data": "project_id"},
        ],
        "columnDefs": [
        {
            "targets": [4, 5],
            "render": function (data) {
                let d = new Date(data);
                return d.toLocaleDateString('en-US');
            }
        }
        ],
        "processing": true,
        //"responsive": true,
        "order": [
            [0, "desc"]
        ],
        "fixedColumns": {
            "start": 1,
            "end": 2
        },
        "scrollX": true
    });

    $('#quote_table').dataTable({
        "ajax": {
            "url": "/index/quote",
            "dataSrc": ''
        },
        "processing": true,
        //"serverSide": true,
        "columns": [
            {"data": "quote_id", "createdCell": function(cell, cellData, rowData, rowIndex, colIndex) {
                $(cell).html("<a target='_blank' href='/quote/edit/id/"+rowData.quote_id+"'>"+rowData.quote_id+"</a>");
            } },
            {"data": "project_name"},
            {"data": "quote_segment"},
            {"data": "quote_date.date" },
            {"data": "expire_date.date", "createdCell": function(cell, cellData, rowData, rowIndex, colIndex) {
                let d = new Date(cellData);
                let today = new Date(); 
                if (d <= today) {$(cell).addClass("red");}
            }},
            {"data": "ship_required_date.date"},
            {"data": "status_name"},
            {"data": "approve_status", "createdCell": function(cell, cellData, rowData, rowIndex, colIndex) {
                if (cellData == -1) {$(cell).addClass("disapproved orange"); $(cell).html("Disapproved");}
                else if (cellData == 10) {$(cell).addClass("approved green"); $(cell).html("Approved");}
                else if (cellData == 1) {$(cell).addClass("waiting red"); $(cell).html("Waiting Approval");}
                else {$(cell).addClass("init"); $(cell).html("Not Submitted");}
            }}
        ],
        "columnDefs": [
        {
            "targets": [3, 4, 5],
            "render": function (data) {
                let d = new Date(data);
                return d.toLocaleDateString('en-US');
            }
        }
        ],
        "order": [[0, "desc"]],
        "fixedColumns": {
            "start": 1,
            "end": 1
        },
        "scrollX": true
    });
</script>