<?php $session = Zend_Registry::get('session');
    $b = $this->ownproject;
    $key_quote_id = array('quote_id');
    $quote_no = array_fill_keys($key_quote_id,array_column($b, 'quote_id'));
    $project_name = array_column($b, 'project_name');
        //$quote_segment = $p['quote_segment'];
    $quote_date = array_column($b, 'quote_date');
        //$expire_date = $p['expire_date']->format('Y-m-d');
        //$ship_required_date = $p['ship_required_date']->format('Y-m-d');
        //$status_name = $p['status_name'];
        //$approve_status = $p['approve_status'];
    $merge = $quote_no;
    $json = Zend_Json::encode($merge);
    //echo Zend_Json::prettyPrint($json, array("indent" => " "));
?>
<!-- Left panel -->
<div class="sidebar-container">
<div class="toc-container">
    <aside class="toc">
        <nav>
            <div class="document-toc-container">
                <section class="document-toc">
                    <header>
                        <h2 class="document-toc-heading">On this page</h2>
                    </header>
                    <ul id="document-toc-list" class="document-toc-list">
                        <!--<li class="document-toc-item">
                            <a class="document-toc-link" href="#all_quotes">All quotes</a>
                        </li>
                        <li class="document-toc-item">
                            <a class="document-toc-link" href="#all_projects">All projects</a>
                        </li>-->
                    </ul>
                </section>
            </div>
        </nav>
    </aside>
    <section class="place side"></section>
</div>
</div>
<!-- Title area -->
<main id="content" class="main-content">

    <div class="middleNav">
        <ul>
            <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                <ul class="mSub1">
                    <li><a href="#" title="">Share user</a></li>
                    <li><a href="#" title="">Show Teamworks</a></li>
                </ul>
            </li>
                   
            <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                <ul class="mSub4">
                    <li><a href="#" title="">Add</a></li>
                    <li><a href="#" title="">Save</a></li>
                    <li><a href="#" title="">Edit</a></li>
                    <li><a href="#" title="">Delete</a></li>
                </ul>
             </li>
        </ul>
    </div>

    <div class="main-page-content">
        <header class="main-page-content-header">
            <h1>All Quotes and Projects</h1>
        </header>
        <div class="section-content">
            <p>IT Administrator landing page.</p>
        </div>

    <!-- Form -->
    <section aria-labelledby="all_quotes" id="section1" data-nav="All Quotes" class="active">
        <h2>All Quotes: <?= count($this->ownproject)?></h2>
        <div class="widget-table">
            <table width="100%" class="display nowrap" id='quote_table'>
                <thead>
                    <tr>
                  	    <th data-priority="1">#</th>
                        <th data-priority="2">Project Name</th>
                        <th>Quote Seg</th>
                        <th data-priority="4">Quote Date</th>
                        <th data-priority="4">Expire Date</th>
                        <th data-priority="4">Ship Required Date</th>
                        <th data-priority="3">Project Status</th>
                        <th data-priority="3">Approval Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i = 0;
                    foreach($b as $p) {?>
                    <tr>
                        <!--
                        <td><!<a href="#"><img src="images/icons/dark/close.png" alt="delete"></a>--<a target='_blank' href="/quote/edit/id/<?//=$p['quote_id']?>"><img src="/images/icons/dark/pencil.png" alt="edit" style="margin:0px 4px"></a></td>
                        -->
                        <td><a target='_blank' href="/quote/edit/id/<?=$p['quote_id']?>"><?=$p['quote_id']?></a></td>
                        <td><?=$p['project_name']?></td>
                        <td><?=$p['quote_segment']?></td>
                        <td><?=$p['quote_date']->format('Y-m-d')?></td>
                        <td><span class='<?php if($p['expire_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['expire_date']->format('Y-m-d')?></span></td>
                        <td><span> <?php if($p['ship_required_date']!= null && $p['ship_required_date']->format('Y-m-d') > '2000-01-01' ) {echo $p['ship_required_date']->format('Y-m-d');}?></span></td>
                        <td ><?=$p['status_name']?></td>
                        <?php if($p['approve_status'] == -1) {?>
                            <td class='disapproved orange'>Disapproved</td>
                        <?php } else if($p['approve_status'] == 10){?>
                            <td class='approved green'>Approved</td>
                        <?php }else if($p['approve_status'] == 1){?>
                            <td class='waiting red'>Waiting Approval</td>
                        <?php } else {?>
                            <td class='init'>Not Submitted</td>
                        <?php }
                        $i++;
                        if ($i >= 50) {break;}
                        ?>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </section>
    <section aria-labelledby="all_projects" id="section2" data-nav="All Projects">
        <h2>All Projects: <?= count($this->projects ) ?></h2>
        <div class="widget-table"> 
            <table width="100%" class="display nowrap" id="project_table">
                <thead>
                    <tr>
                        <th data-priority="1">Project #</th> 
                        <th data-priority="1">Project Name</th>               
                        <th>Specifier</th>
                        <th>Market Segment</th>
                        <th data-priority="5">Create Date</th>
                        <th data-priority="3">Due Date</th>
                        <th data-priority="4">Status</th>
                        <th data-priority="2">Make Quote</th>
                        <th>Project Owner</th>
                        <th>Location</th>
                    </tr>
                </thead>
                <tbody>
              	    <?php 
                        $j = 0;
                        foreach($this->projects as $p) {
                    ?>
                    <tr>
                        <td><?=$p['quote_no']?></td>
                            <?php if($p['owner'] == $session->user['id']) {?>
                        <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/edit/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                            <?php } else { ?>
                        <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/view/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                            <?php } ?>
                        <td><?=$p['Specifier_name']?></td>
                        <td><?=$p['segment']?></td>
                        <td><?=$p['create_date']->format('Y-m-d')?></td>
                        <td><span class='<?php if($p['due_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['due_date']->format('Y-m-d')?></span></td>
                        <td class='stauts_<?=$p['status']?>'><?=$p['status_name']?></td>
                        <td><a target='_blank' href="/quote/index/project/<?=$p['project_id']?>" alt='quote'><img src="/images/icons/dark/money.png" alt="edit" style="margin:0px 4px"></a></td>
                        <td><?=$p['owner']?></td>
                        <td><?=$p['company_id']?></td>
                        <?php $j++;
                            if ($j >= 50) {break;} ?>

                    </tr>
                    <?php } ?> 
                </tbody>
            </table>
        </div>
    </section>
       

 
    <!--<div class="line"></div>-->
    
 
 
    <!--
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<!--<li><a href="/quote" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
                   <!-- <li><a href="#" title=""><img src="images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/delete.png" alt="" /><span>Delete Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>

    </div>
    -->
        </div>
    </main>
 
<!-- Right panel -->
<div class="sidebar-container">
    <aside id="sidebar-quicklinks" class="sidebar">
        <nav aria-label="Actions" class="sidebar-inner">
            <div class="sidebar-inner-nav">
                <div class="statsRow">
                    <ol>
                    <li><a href="/project/" class='add_pro' title="Add new project"><img src="/images/icons/control/32/plus.png" alt="" />Add Project</a></li>
                    <li><a href="#" class='edit_pro' title="Edit project"><img src="/images/icons/control/32/doc_edit.png" alt="" />Edit Project</a></li>
                    <li><a href="#" class='update_pro' title="Update project"><img src="/images/icons/control/32/refresh.png" alt="" />Update Project</a></li>
                    <li><a href="#" class='save_pro' title="Save project"><img src="/images/icons/control/32/save.png" alt="" />Save Project</a></li>
                    <li><a href="#" class='delete_pro' title="Delete project"><img src="/images/icons/control/32/delete.png" alt="" />Delete Project</a></li>
                    </ol>
                </div>
            </div>
        </nav>
    </aside>
</div>

<script>
    oTable = $('#project_table,#asso_table').dataTable({
        //"jQueryUI": true,
        "responsive": true,
	    //"dom": '<""l>t<"F"fp>',
	    "order": [[ 0, "desc" ]]
    });
    $('#quote_table').dataTable({
	    //"jQueryUI": true,
        "responsive": true,
	    //"dom": '<"wrapper"flipt>',
        "order": [[ 0, "desc" ]],
        
    });

    const navList = document.getElementById("document-toc-list");
    const items = ["All Quotes", "All Projects"];
    
    //Build the nav
    items.forEach((item, i) => {
        const el = document.createElement("a");
        el.innerText = item;
        el.classList.add("document-toc-link");
        el.setAttribute("id", `menu-${i + 1}`);
        el.href = `#section${i + 1}`;

        const li = document.createElement("li");
        li.classList.add("document-toc-item");
        li.appendChild(el);
        li.setAttribute("id", `${i + 1}`);
        li.appendChild(el);

        // Append the list item to the list
        navList.appendChild(li);
    });

    //Make Nav Active when Clicked and scrolls down to section
    navList.addEventListener("click", function(event) {
        const targetItem = event.target.closest(".document-toc-item");
        if (targetItem) {
        const activeItem = navList.querySelector(".active");
        if (activeItem) {
            activeItem.classList.remove("active");
        }
        targetItem.classList.add("active");
        window.location.href = `#${targetItem.id}`;
    }
    });

    const topMenu = document.getElementById("document-toc-list");
    const topMenuHeight = topMenu.offsetTop + 1;
    const menuItems = document.querySelectorAll(".document-toc-link");
    const scrollItems = document.querySelectorAll("section");

    // Bind to scroll
    window.addEventListener("scroll", function() {
        // Get container scroll position
        const mainHeroHeight = document.querySelector(".main-page-content-header").offsetTop;
        let fromTop = window.pageYOffset + topMenuHeight + mainHeroHeight;
        
        // Get id of current scroll item
        let id = "";

        [...scrollItems].forEach(item => {
            if (item.offsetTop < fromTop) {
                id = item.id;
            }
        });

        let lastId;

        if (lastId !== id) {
            lastId = id;

            // Loop through menuItems and update aria-current accordingly
            menuItems.forEach(item => {
            const shouldBeCurrent = item.getAttribute("href") === `#${id}`;

            // Update aria-current attribute
            item.setAttribute("aria-current", shouldBeCurrent ? "true" : "false");
            });
        }
    });
</script>