<? $session = Zend_Registry::get('session');
    $b = $this->ownproject;
   ?>
  <!-- Title area -->
    <div class="titleArea">
            <div class="pageTitle">
                <h1>All Quotes and Projects</h1>
                <p>IT Administrator landing page.</p>
            </div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>

        <!-- Main content wrapper -->
    <div class="wrapper">
        <!-- Note -->
        <!-- <div class="nNote nInformation hideit">
        <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
        <form action="" class="form">
            <div class="widget-table">
                <div class="title"><img src="/images/icons/dark/full2.png" alt="" class="titleIcon" /><h6>All Quotes : <?= count($b) ?></h6></div>
                <table class="display" id='quote_table'>
                <thead>
                    <tr>
                  	    <!-- <td class="sortCol action"><div>Edit<span></span></div></td> -->
                  	    <td>#</td>
                        <td>Project Name</td>
                        <td>Quote Seg</td>
                        <td>Quote Date</td>
                        <td>Expire Date</td>
                        <td>Ship Required Date</td>
                        <td>Project Status</td>
                        <td>Approval Status</td>
                    </tr>
                </thead> 

                <tbody>
                <?
                $i = 0;
                foreach($b as $p) {?>
                    <tr>
                        <!--
                        <td><!--<a href="#"><img src="images/icons/dark/close.png" alt="delete"></a>--<a target='_blank' href="/quote/edit/id/<?=$p['quote_id']?>"><img src="/images/icons/dark/pencil.png" alt="edit" style="margin:0px 4px"></a></td>
                        -->
                        <td><a target='_blank' href="/quote/edit/id/<?=$p['quote_id']?>"><?=$p['quote_id']?></a></td>
                        <td><?=$p['project_name']?></td>
                        <td><?=$p['quote_segment']?></td>
                        <td><?=$p['quote_date']->format('Y-m-d')?></td>
                        <td><span class='<? if($p['expire_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['expire_date']->format('Y-m-d')?></span></td>
                        <td><span> <?php if($p['ship_required_date']!= null && $p['ship_required_date']->format('Y-m-d') > '2000-01-01' ) {echo $p['ship_required_date']->format('Y-m-d');}?></span></td>
                        <td ><?=$p['status_name']?></td>
                        <? if($p['approve_status'] == -1) {?>
                            <td class='disapproved orange'>Disapproved</td>
                        <?} else if($p['approve_status'] == 10){?>
                            <td class='approved green'>Approved</td>
                        <?}else if($p['approve_status'] == 1){?>
                            <td class='waiting red'>Waiting Approval</td>
                        <?} else {?>
                            <td class='init'>Not Submitted</td>
                        <?}
                        $i++;
                        if ($i >= 100) {break;}
                        ?>
                    </tr>
                <? } ?>
                </tbody>
            </table>
        </div>

        <div class="widget-table">
            <div class="title"><img src="/images/icons/dark/full2.png" alt="" class="titleIcon" /><h6>All Projects: <?= count($this->projects ) ?></h6></div>  
                 <table cellpadding="0" cellspacing="0" width="100%" class="display"  style="text-align:center;" id="project_table">
                     <thead>
                        <tr>
                  	        <td>Make Quote</td>
                            <td>Project Name</td>
                            <td>Project Owner</td>
                            <td>Location</td>
                            <td>Specifier</td>
                            <td>Project#</td>
                            <td>Market Segment</td>
                            <td>Create Date</td>
                            <td>Due Date</td>
                            <td>Status</td>
                        </tr>
                      </thead>
                      <tbody>
              	       <? 
                        $j = 0;
                        foreach($this->projects as $p) {?>
                        <tr>
                  	        <td><a target='_blank' href="/quote/index/project/<?=$p['project_id']?>" alt='quote'><img src="/images/icons/dark/money.png" alt="edit" style="margin:0px 4px"></a></td>
                            <? if($p['owner'] == $session->user['id']) {?>
                             <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/edit/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                            <? } else { ?>
                            <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/view/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                            <? } ?>
                            <td><?=$p['owner']?></td>
                            <td><?=$p['company_id']?></td>
                            <td><?=$p['Specifier_name']?></td>
                            <td><?=$p['quote_no']?></td>
                            <td><?=$p['segment']?></td>
                            <td><?=$p['create_date']->format('Y-m-d')?></td>
                            <td><span class='<? if($p['due_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['due_date']->format('Y-m-d')?></span></td>
                            <td class='stauts_<?=$p['status']?>'><?=$p['status_name']?></td>
                            <? $j++;
                            if ($j >= 100) {break;} ?>
                        </tr>
                        <? } ?> 
                      </tbody>
                 </table>
            </div>
       
        </form>
 
    <!--<div class="line"></div>-->
    
 
 
    <!--
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<!--<li><a href="/quote" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
                   <!-- <li><a href="#" title=""><img src="images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/delete.png" alt="" /><span>Delete Project</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>

    </div>
    -->
        </div>
    </div>
 

<script>
    oTable = $('#project_table,#asso_table').dataTable({
        //"jQueryUI": true,
	    "pagingType": "numbers",
	    //"dom": '<""l>t<"F"fp>',
	    "order": [[ 6, "desc" ]]
    });
    $('#quote_table').dataTable({
	    //"jQueryUI": true,
        "processing": true,
        //"serverSide": true,
        
	    "pagingType": "numbers",
	    "order": [[ 0, "desc" ]],
        "columnDefs": [
            {"width": "2rem", "targets": 0},
            {"width": "26rem", "targets": 1},
            {"width": "5rem", "targets": 2},
            {"width": "6rem", "targets": 3},
            {"width": "6rem", "targets": 4},
            {"width": "6rem", "targets": 5},
            {"width": "6rem", "targets": 6},
            {"width": "4rem", "targets": 7}
        ]
    });
</script>