<?php $session = Zend_Registry::get('session');

$maintainenceMode = 0;

if ($maintainenceMode != 0 and $session->user['sale_role'] != 'admin') {
?>
	<main id="content" class="main-content">
		<div class="main-page-content">
			<header class="main-page-content-header">
				<h1>This page is currently in maintainence mode. Please check back later. Sorry for the inconvenience!</h1>
			</header>
		</div>
	</main>
<?php } else { ?>

<!-- Main page -->
<main id="content" class="main-content">
    <div class="main-page-content">
        <header class="main-page-content-header">
            <div class="options-menu">
                <button class="quick-link options-button" id="options-button" type="button">
                    <span class='icon icon-menu'></span>
                    Options
                </button>

                <!-- Right panel -->
                <div class="sidebar-container" id="options-menu-items">
                    <a href="/project/" target="_blank" class='button quick-link add-project' title="Add new project">
                        <span class='icon icon-add'></span>
                        Add Project</a>
                </div>
            </div>
            
            <h1>Welcome Back, <span style="font-weight: 300;"><?php echo $session->user['name'] ?></span></h1>
            <p>Here's the quick summary of quotes</p>
        </header>

        <div class="widget-table">
            <table width="100%" class="sTable display nowrap" id='waiting'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Arch Rep</th>
                        <th>Customer</th>
                        <th>Taker</th>
                        <th>Segment</th>
                        <th>Date</td>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
            </table>
        </div>

        <div class="widget-table">
            <table width="100%" class="sTable display nowrap" id='approved'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Arch Rep</th>
                        <th>Customer</th>
                        <th>Taker</th>
                        <th>Segment</th>
                        <th>Quote Date</th>
                        <th>Expire Date</th>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                        <th>P21 OE #</th>
                    </tr>
                </thead>
            </table>
        </div>

        <div class="widget-table">
            <table width="100%" class="sTable display nowrap" id='disapproved'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Arch Rep</th>
                        <th>Customer</th>
                        <th>Taker</th>
                        <th>Segment</th>
                        <th>Quote Date</th>
                        <th>Expire Date</th>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                        <th>Edit</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</main>

<?php }
?>

<script>
    $('#waiting').DataTable({
        ajax: {
            url: "/index/approvalwaiting",
            dataSrc: ''
        },
        processing: true,
        //serverSide: true,
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "architect_name"
            },
            {
                data: "customer_name"
            },
            {
                data: "owner_name"
            },
            {
                data: "market_segment_desc"
            },
            {
                data: "quote_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "ship_required_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "quote_status"
            }
        ],
        columnDefs: [{
                targets: '_all',
                className: 'dt-head-center'
                }, {
            targets: [0, 2, 3, 4, 5, 6, 7, 8],
            className: 'dt-body-center'
        }],
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 1
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Waiting for Approval</h2><p><?= count($this->waiting) ?> quotes waiting for approval</p>';
                return info;
            },
            bottomStart: 'pageLength'
        }
    });

    $('#approved').DataTable({
        ajax: {
            url: "/index/approvalapproved",
            dataSrc: ''
        },
        processing: true,
        //serverSide: true,
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "architect_name"
            },
            {
                data: "customer_name"
            },
            {
                data: "owner_name"
            },
            {
                data: "market_segment_desc"
            },
            {
                data: "quote_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "expire_date",
                render: function(data) {
                    let date = new Date(data);
                    let today = new Date();
                    if (date <= today) {
                        return '<span class="red">' + date.toLocaleDateString() + '</span>';
                    } else {
                        return date.toLocaleDateString();
                    }
                }
            },
            {
                data: "ship_required_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "quote_status"
            },
            {
                data: "order_no"
            }
        ],
        columnDefs: [{
                targets: '_all',
                className: 'dt-head-center'
                }, {
            targets: [0, 2, 4, 5, 6, 7, 8, 9, 10],
            className: 'dt-body-center'
        }],
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 1
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Approved</h2><p><?= count($this->approved) ?> approved quotes';
                return info;
            },
            bottomStart: 'pageLength'
        }
    });

    $('#disapproved').DataTable({
        ajax: {
            url: "/index/approvaldisapproved",
            dataSrc: ''
        },
        processing: true,
        //serverSide: true,
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "architect_name"
            },
            {
                data: "customer_name"
            },
            {
                data: "owner_name"
            },
            {
                data: "market_segment_desc"
            },
            {
                data: "quote_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "expire_date",
                render: function(data) {
                    let date = new Date(data);
                    let today = new Date();
                    if (date <= today) {
                        return '<span class="red">' + date.toLocaleDateString() + '</span>';
                    } else {
                        return date.toLocaleDateString();
                    }
                }
            },
            {
                data: "ship_required_date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "quote_status"
            },
            {
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/quote/edit/id/" + row.quote_id + "'><span class='button-wrap'><span class='icon icon-edit'></span></span></a>";
                }
            }
        ],
        columnDefs: [{
                targets: '_all',
                className: 'dt-head-center'
                }, {
            targets: [0, 2, 4, 5, 6, 7, 8, 9, 10],
            className: 'dt-body-center'
        }],
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 1
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Disapproved</h2><p><?= count($this->disapproved) ?> disapproved quotes';
                return info;
            },
            bottomStart: 'pageLength'
        }
    });
</script>