<?php $session = Zend_Registry::get('session'); ?>

<!-- Main page -->
<main id="content" class="main-content">
    <div class="main-page-content">
        <header class="main-page-content-header">
            <div class="options-menu">
                <button class="quick-link options-button" id="options-button" type="button">
                    <span class='icon icon-menu'></span>
                    Options
                </button>

                <!-- Right panel -->
                <div class="sidebar-container" id="options-menu-items">
                    <a href="/project/" target="_blank" class='button quick-link add-project' title="Add new project">
                        <span class='icon icon-add'></span>
                        Add Project</a>
                </div>
            </div>
            
            <h1>Welcome Back, <span style="font-weight: 300;"><?php echo $session->user['name'] ?></span></h1>
            <p>Here's the quick summary of quotes</p>
        </header>

        <div class="widget-table">
            <table width="100%" class="display nowrap" id='waiting'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Sales Rep.</th>
                        <th>Contractor</th>
                        <th>Arch. Sales Rep.</th>
                        <th>Segment</th>
                        <th>Date</td>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
            </table>
        </div>

        <div class="widget-table">
            <table width="100%" class="display nowrap" id='approved'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Sales Rep.</th>
                        <th>Contractor/Company</th>
                        <th>Arch. Sale Rep.</th>
                        <th>Segment</th>
                        <th>Quote Date</th>
                        <th>Expire Date</th>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
            </table>
        </div>

        <div class="widget-table">
            <table width="100%" class="display nowrap" id='disapproved'>
                <thead>
                    <tr>
                        <th>Quote ID</th>
                        <th>Project Name</th>
                        <th>Sales Rep.</th>
                        <th>Contractor/Company</th>
                        <th>Arch. Sale Rep.</th>
                        <th>Segment</th>
                        <th>Quote Date</th>
                        <th>Expire Date</th>
                        <th>Ship Required Date</th>
                        <th>Status</th>
                        <th>Edit</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</main>

<script>
    $('#options-button').on("click", function() {
        $('#options-menu-items').slideToggle({
            start: function() {
                $(this).css('display', 'flex');
            }
        });
    })

    $('#waiting').DataTable({
        ajax: {
            url: "/index/approvalwaiting",
            dataSrc: ''
        },
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "sale_name"
            },
            {
                data: "customer"
            },
            {
                data: "arch_name"
            },
            {
                data: "segment"
            },
            {
                data: "quote_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "ship_required_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "status_name"
            }
        ],
        columnDefs: [{
            targets: [0, 2, 3, 4, 5, 6, 7, 8],
            className: 'dt-body-center'
        }],
        processing: true,
        //serverSide: true,
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 1
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Waiting for Approval</h2><p><?= count($this->waiting) ?> quotes waiting for approval</p>';
                return info;
            }
        }
    });

    $('#approved').DataTable({
        ajax: {
            url: "/index/approvalapproved",
            dataSrc: ''
        },
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "sale_name"
            },
            {
                data: "customer"
            },
            {
                data: "arch_name"
            },
            {
                data: "segment"
            },
            {
                data: "quote_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "expire_date.date",
                render: function(data) {
                    let date = new Date(data);
                    let today = new Date();
                    if (date <= today) {
                        return '<span class="red">' + date.toLocaleDateString() + '</span>';
                    } else {
                        return date.toLocaleDateString();
                    }
                }
            },
            {
                data: "ship_required_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "status_name"
            }
        ],
        columnDefs: [{
            targets: [0, 2, 4, 5, 6, 7, 8, 9],
            className: 'dt-body-center'
        }],
        processing: true,
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 1
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Approved</h2><p><?= count($this->approved) ?> approved quotes';
                return info;
            }
        }
    });

    $('#disapproved').DataTable({
        ajax: {
            url: "/index/approvaldisapproved",
            dataSrc: ''
        },
        columns: [{
                data: "quote_id",
                render: function(data, type, row, meta) {
                    return "<a target='_blank' href='/approve/index/id/" + row.quote_id + "'>" + row.quote_id + "</a>";
                }
            },
            {
                data: "project_name"
            },
            {
                data: "sale_name"
            },
            {
                data: "customer"
            },
            {
                data: "arch_name"
            },
            {
                data: "segment"
            },
            {
                data: "quote_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "expire_date.date",
                render: function(data) {
                    let date = new Date(data);
                    let today = new Date();
                    if (date <= today) {
                        return '<span class="red">' + date.toLocaleDateString() + '</span>';
                    } else {
                        return date.toLocaleDateString();
                    }
                }
            },
            {
                data: "ship_required_date.date",
                render: function(data) {
                    let date = new Date(data);
                    return date.toLocaleDateString();
                }
            },
            {
                data: "status_name"
            },
            {
                data: "quote_id",
                redner: function(data, type, row, meta) {
                    return "<a target='_blank' href='/quote/edit/id/" + row.quote_id + "'><span class='button-wrap'><span class='icon icon-edit'></span></span></a>";
                }
            }
        ],
        columnDefs: [{
            targets: [0, 2, 4, 5, 6, 7, 8, 9, 10],
            className: 'dt-body-center'
        }],
        processing: true,
        order: [
            [0, "desc"]
        ],
        fixedColumns: {
            start: 1,
            end: 2
        },
        scrollX: true,
        layout: {
            topStart: function() {
                let info = document.createElement('div');
                info.innerHTML = '<h2>Disapproved</h2><p><?= count($this->disapproved) ?> disapproved quotes';
                return info;
            }
        }
    });
</script>