<?php $session = Zend_Registry::get('session'); ?>

<!-- Title area -->
<main id="content" class="main-content">

    <div class="middleNav">
        <ul>
            <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                <ul class="mSub1">
                    <li><a href="#" title="">Share user</a></li>
                    <li><a href="#" title="">Show Teamworks</a></li>
                </ul>
            </li>

            <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                <ul class="mSub4">
                    <li><a href="#" title="">Add</a></li>
                    <li><a href="#" title="">Save</a></li>
                    <li><a href="#" title="">Edit</a></li>
                    <li><a href="#" title="">Delete</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="main-page-content">
        <header class="main-page-content-header">
            <h1>Welcome Back, <span style="font-weight: 300;"><?php echo $session->user['name'] ?></span></h1>
            <p>Here's the quick summary your projects and quotes</p>
        </header>

        <section aria-labelledby="my_projects" id="section1" data-nav="My Projects" class="active">
            <div class="widget-table">
                <table width="100%" class="display nowrap" id='project_table'>
                    <thead>
                        <tr>
                            <th>Project ID</th>
                            <th>Quote ID</th>
                            <th>Project Name</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Specifier</th>
                            <th>Market Segment</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>

        <?php if ($session->user['approve_id'] != null) { ?>
            <section aria-labelledby="other_projects" id="section2" data-nav="Other Projects">
                <div class="widget-table">
                    <table width="100%" class="display nowrap" id='other_project_table'>
                        <thead>
                            <tr>
                                <th>Project ID</th>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Create Date</th>
                                <th>Due Date</th>
                                <th>Specifier</th>
                                <th>Worksheet Owner</th>
                                <th>Market Segment</th>
                                <th class="action">Make Quote</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>
        <?php } ?>

        <section aria-labelledby="my_quotes" <?php if ($session->user['approve_id'] != null) { ?> id="section3" <?php } else { ?> id="section2" <?php } ?> data-nav="My Quotes">
            <div class="widget-table">
                <table width="100%" class="display nowrap" id='quote_table'>
                    <thead>
                        <tr>
                            <th>Quote #</th>
                            <th>Project Name</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Company Name</th>
                            <th>Project Status</th>
                            <th>Approval Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>

        <section aria-labelledby="follow_up_logs" <?php if ($session->user['approve_id'] != null) { ?> id="section4" <?php } else { ?> id="section3" <?php } ?> data-nav="Follow Up Logs">
            <div class="widget-table">
                <table width="100%" class="display nowrap" id='project_log'>
                    <thead>
                        <tr>
                            <th>Log Time</th>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Critical Updates Required</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>
</main>
<script>

    $(document).ready(function() {
        $('#project_table').DataTable({
            //select: true,
            ajax: {
                url: "/index/projectsalesrep",
                dataSrc: ''
            },
            columns: [{
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        {
                            $(cell).html("<a target='_blank' href='/project/edit/id/" + rowData.project_id + "'>" + rowData.project_id + "</a>");
                        }
                    }
                },
                {
                    data: "quote_no"
                },
                {
                    data: "project_name"
                },
                {
                    data: "create_date.date"
                },
                {
                    data: "due_date.date",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        let d = new Date(cellData);
                        let today = new Date();
                        if (d <= today) {
                            $(cell).addClass("red");
                        }
                    }
                },
                {
                    data: "Specifier_name"
                },
                {
                    data: "segment"
                },
                {
                    data: "status_name"
                },
                {
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        $(cell).html("<a target='_blank' href='/quote/index/project/" + rowData.project_id + "'><span class='button-wrap'><span class='icon icon-money'></span></span></a>")
                    }
                },
            ],
            columnDefs: [{
                    targets: [3, 4],
                    render: function(data) {
                        let DateTime = luxon.DateTime;
                        let d = DateTime.fromSQL(data).setLocale('en').toFormat('D');
                        return d;
                    }
                },
                {
                    targets: [8],
                    className: 'dt-body-center'
                }
            ],
            processing: true,
            order: [
                [0, "desc"]
            ],
            fixedColumns: {
                start: 1,
                end: 2
            },
            scrollX: true,
            layout: { topStart: function() {
                let info= document.createElement('div');
                info.innerHTML = '<h2>My Projects</h2><p><?= count($this->ownproject) ?> projects';
                return info;
            } }
        });

        $('#other_project_table').DataTable({
            ajax: {
                url: "/index/otherprojects",
                dataSrc: ''
            },
            columns: [{
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        $(cell).html("<a target='_blank' href='/project/edit/id/" + rowData.project_id + "'>" + rowData.project_id + "</a>");
                    }
                },
                {
                    data: "quote_no"
                },
                {
                    data: "project_name"
                },
                {
                    data: "create_date.date"
                },
                {
                    data: "due_date.date",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        let d = new Date(cellData);
                        let today = new Date();
                        if (d <= today) {
                            $(cell).addClass("red");
                        }
                    }
                },
                {
                    data: "Specifier_name"
                },
                {
                    data: "owner"
                },
                {
                    data: "segment"
                },
                {
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        $(cell).html("<a target='_blank' href='/quote/index/project/" + rowData.project_id + "'><span class='button-wrap'><span class='icon icon-money'></span></span></a>")
                    }
                },
            ],
            columnDefs: [{
                    targets: [3, 4],
                    render: function(data) {
                        let DateTime = luxon.DateTime;
                        let d = DateTime.fromSQL(data).setLocale('en').toFormat('D');
                        return d;
                    }
                },
                {
                    targets: [8],
                    className: 'dt-body-center'
                }
            ],
            processing: true,
            order: [
                [0, "desc"]
            ],
            fixedColumns: {
                start: 1,
                end: 1
            },
            scrollX: true,
            layout: { topStart: function() {
                let info= document.createElement('div');
                info.innerHTML = '<h2>Other Projects At <?= $session->user['company'] ?></h2><p> <?= count($this->otherprojects) ?> projects at <?= $session->user['company'] ?>';
                return info;
            } }
        });

        $('#quote_table').DataTable({
            ajax: {
                url: "/index/quotesalesrep",
                dataSrc: ''
            },
            processing: true,
            //"serverSide": true,
            columns: [{
                    data: "quote_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        $(cell).html("<a target='_blank' href='/quote/edit/id/" + rowData.quote_id + "'>" + rowData.quote_id + "</a>");
                    }
                },
                {
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        $(cell).html("<a target='_blank' href='/project/edit/id/" + rowData.quote_id + "'>" + rowData.project_name + "</a>");
                    }
                },
                {
                    data: "quote_date.date"
                },
                {
                    data: "expire_date.date",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        let d = new Date(cellData);
                        let today = new Date();
                        if (d <= today) {
                            $(cell).addClass("red");
                        }
                    }
                },
                {
                    data: "ship_required_date.date"
                },
                {
                    data: "customer"
                },
                {
                    data: "status_name"
                },
                {
                    data: "approve_status",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        if (cellData == -1) {
                            $(cell).addClass("disapproved orange");
                            $(cell).html("Disapproved");
                        } else if (cellData == 10) {
                            $(cell).addClass("approved green");
                            $(cell).html("Approved");
                        } else if (cellData == 1) {
                            $(cell).addClass("waiting red");
                            $(cell).html("Waiting Approval");
                        } else {
                            $(cell).addClass("init");
                            $(cell).html("Not Submitted");
                        }
                    }
                }
            ],
            columnDefs: [{
                targets: [2, 3, 4],
                render: function(data) {
                    let DateTime = luxon.DateTime;
                    let d = DateTime.fromSQL(data).setLocale('en').toFormat('f');
                    return d;
                }
            }],
            order: [
                [0, "desc"]
            ],
            fixedColumns: {
                start: 2,
                end: 2
            },
            scrollX: true,
            layout: { topStart: function() {
                let info= document.createElement('div');
                info.innerHTML = '<h2>My Quotes</h2><p> <?= count($this->ownquotes) ?> quotes';
                return info;
            } }
        });

        $('#project_log').DataTable({
            ajax: {
                url: "/index/memo",
                dataSrc: ''
            },
            processing: true,
            columns: [{
                    data: "added.date"
                },
                {
                    data: "project_id",
                    createdCell: function(cell, cellData, rowData, rowIndex, colIndex) {
                        {
                            $(cell).html("<a target='_blank' href='/project/edit/id/" + rowData.project_id + "'>" + rowData.project_id + "</a>");
                        }
                    }
                },
                {
                    data: "project_name"
                },
                {
                    data: "type"
                },
            ],
            columnDefs: [{
                targets: [0],
                render: function(data) {
                    let DateTime = luxon.DateTime;
                    let d = DateTime.fromSQL(data).setLocale('en').toFormat('f');
                    return d;
                }
            }, {
                targets: [1],
                className: 'dt-body-center'
            }],
            fixedColumns: {
                start: 3
            },
            order: [],
            scrollX: true,
            layout: { topStart: function() {
                let info= document.createElement('div');
                info.innerHTML = '<h2>Follow Up Logs</h2><p> <?= count($this->memo) ?> logs';
                return info;
            } }
        });
    })
</script>

<!-- Right panel -->
<div class="sidebar-container">
    <aside id="sidebar-quicklinks" class="sidebar">
        <nav aria-label="Actions" class="sidebar-inner">
            <div class="sidebar-inner-nav">
                <div class="quick-links">
                    <ol>
                        <li>
                            <a href="/project/" target="_blank" class='quick-link add_pro' title="Add new project">
                                <svg width="40" height="40" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M12.75 11.25V5C12.75 4.80109 12.671 4.61032 12.5303 4.46967C12.3897 4.32902 12.1989 4.25 12 4.25C11.8011 4.25 11.6103 4.32902 11.4697 4.46967C11.329 4.61032 11.25 4.80109 11.25 5V11.25H5C4.80109 11.25 4.61032 11.329 4.46967 11.4697C4.32902 11.6103 4.25 11.8011 4.25 12C4.25 12.1989 4.32902 12.3897 4.46967 12.5303C4.61032 12.671 4.80109 12.75 5 12.75H11.25V19C11.2526 19.1981 11.3324 19.3874 11.4725 19.5275C11.6126 19.6676 11.8019 19.7474 12 19.75C12.1989 19.75 12.3897 19.671 12.5303 19.5303C12.671 19.3897 12.75 19.1989 12.75 19V12.75H19C19.1989 12.75 19.3897 12.671 19.5303 12.5303C19.671 12.3897 19.75 12.1989 19.75 12C19.7474 11.8019 19.6676 11.6126 19.5275 11.4725C19.3874 11.3324 19.1981 11.2526 19 11.25H12.75Z" />
                                </svg>
                                Add Project
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </nav>
    </aside>
</div>