<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
<link href="/css/main.css" rel="stylesheet" type="text/css" />
<?php echo $this->headLink(); ?>
<script type="text/javascript" src="/js/jquery.min.js"></script>

<script type="text/javascript" src="/js/plugins/spinner/ui.spinner.js"></script>
<script type="text/javascript" src="/js/plugins/spinner/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/plugins/charts/excanvas.min.js"></script>
<script type="text/javascript" src="/js/plugins/charts/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/uniform.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.cleditor.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/autogrowtextarea.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.dualListBox.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.inputlimiter.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/chosen.jquery.min.js"></script>

<script type="text/javascript" src="/js/plugins/wizard/jquery.form.js"></script>
<script type="text/javascript" src="/js/plugins/wizard/jquery.validate.min.js"></script>
<script type="text/javascript" src="/js/plugins/wizard/jquery.form.wizard.js"></script>

<script type="text/javascript" src="/js/plugins/uploader/plupload.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/plupload.html5.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/plupload.html4.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/jquery.plupload.queue.js"></script>

<script type="text/javascript" src="/js/plugins/tables/datatable.js"></script>
<script type="text/javascript" src="/js/plugins/tables/tablesort.min.js"></script>
<script type="text/javascript" src="/js/plugins/tables/resizable.min.js"></script>

<script type="text/javascript" src="/js/plugins/ui/jquery.tipsy.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.collapsible.min.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.progress.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.timeentry.min.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.colorpicker.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.jgrowl.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.breadcrumbs.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.sourcerer.js"></script>

<script type="text/javascript" src="/js/plugins/calendar.min.js"></script>
<script type="text/javascript" src="/js/plugins/elfinder.min.js"></script>

<script type="text/javascript" src="/js/custom.js"></script>
<?php echo $this->headScript(); ?> 
<style>
	.loading (z-index:1003; width:100%; height:100%; background: url(../images/loaders/loader4.gif) #AAA center center no-repeat;)
</style>
</head>
<body>

 <?php echo $this->render('header.phtml') ?>
 <div id="rightSide">
 	 <!-- Top fixed navigation -->
    <div class="topNav">
        <div class="wrapper">
            <div class="welcome"><a href="#" title=""><img src="/images/userPic.png" alt="" /></a><span>Log in As <?php echo $_SERVER['REMOTE_USER'] ?></span></div>
            <div class="userNav">
                <ul>
                    <li><a href="#" title=""><img src="/images/icons/topnav/profile.png" alt="" /><span>Profile</span></a></li>
                    <li><a href="#" title=""><img src="/images/icons/topnav/tasks.png" alt="" /><span>Tasks</span></a></li>
                    <li class="dd"><a title=""><img src="/images/icons/topnav/messages.png" alt="" /><span>Messages</span><span class="numberTop">8</span></a>
                        <ul class="userDropdown">
                            <li><a href="#" title="" class="sAdd">new message</a></li>
                            <li><a href="#" title="" class="sInbox">inbox</a></li>
                            <li><a href="#" title="" class="sOutbox">outbox</a></li>
                            <li><a href="#" title="" class="sTrash">trash</a></li>
                        </ul>
                    </li>
                    <li><a href="#" title=""><img src="/images/icons/topnav/settings.png" alt="" /><span>Settings</span></a></li>
                    <li id='nav_logout'><a href="/logout" title=""><img src="/images/icons/topnav/logout.png" alt="" /><span>Logout</span></a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>

<?php echo $this->layout()->content ?>
 <?php echo $this->render('footer.phtml') ?>
</div>

<div class="clear"></div>
<div class="loading" style="z-index:1003; top:0;left:0; width:100%; height:100%; background: url(/images/loaders/loader4.gif) #AAA center center no-repeat;position:absolute;display:none;opacity: .30;filter: Alpha(Opacity=30);"> </div>
</body>
</html>
