<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="light">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico.png">
    <link href="/css/main.css" rel="stylesheet" type="text/css">
    <?php echo $this->headLink(); ?>

<!-- jQuery CDN -->
<script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"></script>

<!-- jMigrate CDN -->
<script src="https://code.jquery.com/jquery-migrate-3.4.1.js"></script>

<!-- jQuery UI CDN -->
<script
  src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"
  integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0="
  crossorigin="anonymous"></script>

<!-- DataTables CDN -->
<link href="https://cdn.datatables.net/v/dt/dt-1.13.8/r-2.5.0/datatables.min.css" rel="stylesheet">

<script src="https://cdn.datatables.net/v/dt/dt-1.13.8/r-2.5.0/datatables.min.js"></script>

<!-- Hamburger menu -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<script type="text/javascript" src="/js/plugins/ui/jquery.ui.widget.js"></script>        
<script type="text/javascript" src="/js/plugins/ui/jquery.ui.mouse.js"></script>          
<script type="text/javascript" src="/js/plugins/ui/jquery.ui.resizable.js"></script>
-->

<script type="text/javascript" src="/js/plugins/spinner/ui.spinner.js"></script>
<script type="text/javascript" src="/js/plugins/spinner/jquery.mousewheel.js"></script>
 
<script type="text/javascript" src="/js/plugins/charts/excanvas.min.js"></script>
<script type="text/javascript" src="/js/plugins/charts/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/uniform.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.cleditor.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.validationEngine.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/autogrowtextarea.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.dualListBox.js"></script>
<script type="text/javascript" src="/js/plugins/forms/jquery.inputlimiter.min.js"></script>
<script type="text/javascript" src="/js/plugins/forms/chosen.jquery.min.js"></script>

<script type="text/javascript" src="/js/plugins/wizard/jquery.form.js"></script>
<script type="text/javascript" src="/js/plugins/wizard/jquery.validate.min.js"></script>
<script type="text/javascript" src="/js/plugins/wizard/jquery.form.wizard.js"></script>

<script type="text/javascript" src="/js/plugins/uploader/plupload.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/plupload.html5.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/plupload.html4.js"></script>
<script type="text/javascript" src="/js/plugins/uploader/jquery.plupload.queue.js"></script>

<!--<script type="text/javascript" src="/js/plugins/tables/tablesort.min.js"></script>
<script type="text/javascript" src="/js/plugins/tables/resizable.min.js"></script>-->

<script type="text/javascript" src="/js/plugins/ui/jquery.tipsy.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.collapsible.min.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.progress.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.timeentry.min.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.colorpicker.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.jgrowl.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.breadcrumbs.js"></script>
<script type="text/javascript" src="/js/plugins/ui/jquery.sourcerer.js"></script>

<script type="text/javascript" src="/js/plugins/calendar.min.js"></script>
<script type="text/javascript" src="/js/plugins/elfinder.min.js"></script>

<script type="text/javascript" src="/js/custom.js"></script>

<?php echo $this->headScript(); ?> 
<style>
	.loading {z-index:1003; width:100%; height:100%; background: url(../images/loaders/loader4.gif) #AAA center center no-repeat;}
</style>
</head>

<body>
    <div id = "root">
        <div class = "page-wrapper category-html document-page">

        <!-- Header -->
        <?php echo $this->render('header.phtml') ?>
            <!--<div class="userNav">
                <ul>
                    <li><a href="#" title=""><img src="/images/icons/topnav/profile.png" alt="" /><span>Profile</span></a></li>
                    <li><a href="#" title=""><img src="/images/icons/topnav/tasks.png" alt="" /><span>Tasks</span></a></li>
                    <li class="dd"><a title=""><img src="/images/icons/topnav/messages.png" alt="" /><span>Messages</span><span class="numberTop">8</span></a>
                        <ul class="userDropdown">
                            <li><a href="#" title="" class="sAdd">new message</a></li>
                            <li><a href="#" title="" class="sInbox">inbox</a></li>
                            <li><a href="#" title="" class="sOutbox">outbox</a></li>
                            <li><a href="#" title="" class="sTrash">trash</a></li>
                        </ul>
                    </li>
                    <li><a href="#" title=""><img src="/images/icons/topnav/settings.png" alt="" /><span>Settings</span></a></li>
                    <li id='nav_logout'><a href="/logout" title=""><img src="/images/icons/topnav/logout.png" alt="" /><span>Logout</span></a></li>
                </ul>
            </div>-->
                <!--<div class="clear"></div>-->
                    

            <!-- Main -->
            <div class="main-wrapper">
                <?php echo $this->layout()->content ?>
            </div>
        <!--
        <div class="loading" style="z-index:1003; top:0;left:0; width:100%; height:100%; background: url(/images/loaders/loader4.gif) #AAA center center no-repeat;position:absolute;display:none;opacity: .30;"> </div>
        -->
        </div>
    </div>
</body>

<!-- Footer -->
<footer class="footer">
    <?php echo $this->render('footer.phtml') ?>
</footer>
</html>