   <?php $session =  Zend_Registry::get('session'); ?>
<div class="top-navigation-main">

    <nav class="main-nav" id="leftSide">
        <ul id="menu" class="nav">
        <?php if($session->user['sale_role'] == 'admin') {?>
        <li class="forms">
          <a href="/index/admin" title="admin" class="top-level-entry">All Quotes</a>
        </li>
        <li class="forms">
          <a href="/index/approval" title="approve" class="top-level-entry">Approval Manager</a>
        </li>
      	<?php }?>
    	    <?php if($session->user['approve_id'] != null || $session->user['sale_role'] == 'admin') {?>
    	    <li class="forms">
             <a href="/index/index/normal/1/" class="top-level-entry">Project Manager</a>
             </li>
            <?php } else {?>
      	    <li class="forms"><a href="/" class="top-level-entry">Project Manager</a>
            </li>
        <?php }?>
         <!-- <li class="forms"><a href="/index/sales" title="" ><span>Quote Manager</span></a>
        </li>-->
        <?php if($session->user['approve_id'] != null) {?>
        <li class="forms">
          
          <a href="/index/approval" title="approve" class="top-level-entry">Approval Manager</a>
        </li>
      	<?php }?>
        <li class="forms"><a target='_blank' href="/project" class="top-level-entry">Add New Project</a>
        </li>
        

        </ul>
    </nav>

    <div class="theme-switcher-menu">
      <button type="button" class="button" onclick="toggleTheme()">
        <span class="button-wrap">
          <span class="icon"></span>
          Theme
        </span>
      </button>
    </div>

    <div class="welcome">
        <img src="/images/userPic.png" alt="" /><span>Welcome, <?php echo $_SERVER['REMOTE_USER'] ?>!</span>
    </div>
</div>