<?php
$user = $this->user;
$locations = $this->locations;
$projectStatus = $this->projectStatus;
$marketSegment = $this->marketSegment;
$architect = $this->architect;
$architectID = $architect['architect_id'];
$this->headTitle('Edit Architect: ' . $architectID . ' - ' . $architect['architect_name']);
echo $this->headTitle();
$address = $this->address;
$specifier = $this->specifier;
$company = $this->company;
$addressList = $this->addressList;
$specifierList = $this->specifierList;
?>

<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <h1 class="text-2xl font-semibold tracking-tight">Edit Architect</h1>
        <p class="text-muted-foreground" class="font-light">Editting <?= $this->escapeHtml($architectID) ?> - <?= $this->escapeHtml($architect['architect_name']) ?></p>
    </header>

    <div class="features fade-in-up flex flex-col gap-4 md:gap-6">
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <h2>Architect</h2>
                    </div>
                </div>
                <div class="line"></div>
                <div class="widget-section">
                    <form action="/architect/<?= $architectID ?>/edit" method="post" class="form" id='architect-form' data-save-btn="#form-btn-save-architect" data-form="#architectForm">
                        <input type="hidden" id="owner_id" value='<?= $this->escapeHtml($user['id']) ?>' />
                        <div class="formRow">
                            <div class="grid gap-2">
                                <label for="architect_name">Architect Name</label>
                                <input type='text' name="architect_name" id='architect_name' class="no-autocomplete"
                                    original-title="Search by ID or Name" value='<?= $architect['architect_name'] ?? '' ?>' />
                                <input type="hidden" name='architect_id' id='architect_id' value='<?= $this->escapeHtml(
                                                                                                        $architect['architect_id'] ?? ''
                                                                                                    ) ?>' />
                            </div>

                            <div class="grid gap-2">
                                <label for="architect_company_id">Company</label>
                                <select id="architect_company_id" name="architect_company_id">
                                    <?php foreach ($company as $l) { ?>
                                        <option value='<?= $this->escapeHtml($l['company_id']) ?>' <?php if (
                                                                                                        $l['company_id'] ===
                                                                                                        ($architect['company_id'] ?? DEFAULT_COMPANY)
                                                                                                    ) {
                                                                                                        echo 'selected';
                                                                                                    } ?>>
                                            <?= $l['company_name'] ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="architect_rep_id">Architect Representative</label>
                                <input type="text" id="architect_rep_id" name="architect_rep_id"
                                    value='<?= $this->escapeHtml($architect['architect_rep_id'] ?? '') ?>' />
                            </div>

                            <div class="grid gap-2">
                                <label for="architect_type_id">Architect Type</label>
                                <select id="architect_type_id" name="architect_type_id">
                                    <option value="">-- Choose architect type --</option>
                                    <?php foreach ($this->architectType as $a) { ?>
                                        <option value='<?= $this->escapeHtml($a['architect_type_id']) ?>' <?= $a['architect_type_id'] ===
                                                                                                                ($architect['architect_type_id'] ?? '')
                                                                                                                ? 'selected'
                                                                                                                : '' ?>><?= $a['architect_type_desc'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="grid gap-2">
                                <label for="architect_class_id">Architect Class</label>
                                <input type="text" id="architect_class_id" name="architect_class_id"
                                    value='<?= $this->escapeHtml($architect['class_id'] ?? '') ?>'>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="line"></div>
                <div class="widget-footer">
                    <div class="widget-footer-button">
                        <button disabled id="form-btn-save-architect" type="submit" title="Save architect information"
                            class="button action save-architect-button small">
                            <span class="button-wrap text-[10px] font-bold">
                                <span class="icon icon-save"></span>
                                Save
                            </span>
                        </button>
                    </div>
                </div>
            </div>

            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <h2>Projects</h2>
                    </div>
                    <div class="widget-button">
                        <button type="button" title="Add new project for this architect"
                            class="button action has-icon add-project-button small" id="architect-edit-add-project">
                            <span class="button-wrap text-[10px] font-bold">
                                <span class="icon icon-add"></span>
                                New Project
                            </span>
                        </button>
                        <button id="export-selected" class="button action has-icon export-item-button small">
                            <span class="button-wrap text-[10px] font-bold">
                                <span class="icon icon-export"></span>
                                Export Selected
                            </span>
                        </button>
                    </div>
                </div>
                <div class="line"></div>
                <table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap" id="architect-projects-table" data-init="architectProjects">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="select-all" title="Select all projects"></th>
                            <th>ID</th>
                            <th>Name</th>
                            <th>No. of quotes</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <h2>Addresses</h2>
                    </div>
                    <div class="widget-button">
                        <button type="button" title="Add new address"
                            class="button action has-icon add-item-button small" id="architect-edit-add-address">
                            <span class="button-wrap text-[10px] font-bold">
                                <span class="icon icon-add"></span>
                                New Address
                            </span>
                        </button>
                    </div>
                </div>

                <div class="line"></div>
                <table cellpadding="0" cellspacing="0" width="100%" class="sTable wTable display nowrap" id="architect-addresses-table" data-init="architectAddresses">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <h2>Specifiers</h2>
                    </div>
                    <div class="widget-button">
                        <button type="button" title="Add new specifier"
                            class="button action has-icon add-item-button small" id="architect-edit-add-specifier">
                            <span class="button-wrap text-[10px] font-bold">
                                <span class="icon icon-add"></span>
                                New Specifier
                            </span>
                        </button>
                    </div>
                </div>

                <div class="line"></div>
                <table cellpadding="0" cellspacing="0" width="100%" class="sTable wTable display nowrap" id="architect-specifiers-table" data-init="architectSpecifiers">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    <?= $this->render('modal/project');?>
</div>
