<?php

$this->headTitle('Admin portal');
echo $this->headTitle();

$user = $this->user;
?>

<!-- Title area -->
<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <?= $this->partial('components/greeting'); ?>

        <div class="flex items-center justify-between ">
            <p class="text-muted-foreground">Here's all projects and quotes</p>

            <?= $this->partial('components/new-project-btn'); ?>
        </div>
    </header>

    <div class="flex flex-col gap-4 md:gap-6">
        <div class="fade-in-up">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <div class="widget-header">
                    <div class="widget-title">
                        <p class="leading-none font-semibold text-lg">Role Override</p>
                    </div>
                    <div class="widget-button">
                            <button type="button"
                                title="Add new shared user"
                                class="btn-sm-icon-outline shadow-sm text-muted-foreground"
                                id="widget-btn-add-role-override-user"
                                x-on:click="window.roleOverrideModalComponent.open = true"
                                data-tooltip="Override a user role">
                                <i data-lucide="plus"></i>
                            </button>
                    </div>
                </div>

                <div class="line"></div>

                <table width="100%" class="sTable display nowrap" id="admin-all-role-override-table" data-init="adminRoleOverride">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Role</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div class="fade-in-up">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id="admin-all-users-table" data-init="adminUsers">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Company</th>
                            <th>Location</th>
                            <th>Role</th>
                            <th>P2Q Role</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div id="project-table" class="fade-in-up"></div>

        <div class="fade-in-up" aria-labelledby="all_quotes">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id='admin-quote-table' data-init="adminQuote">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Project Name</th>
                            <th>Segment</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Project Status</th>
                            <th>Approval</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<?= $this->render('modal/role-override'); ?>
