<?php

$this->headTitle('Admin portal');
echo $this->headTitle();

$user = $this->user;
?>

<!-- Title area -->
<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <?= $this->partial('components/greeting'); ?>

        <div class="flex items-center justify-between ">
            <p class="text-muted-foreground">Welcome to Admin Dashboard.</p>

            <?= $this->partial('components/new-project-btn'); ?>
        </div>
    </header>

    <div class="flex flex-col gap-4 md:gap-6">
        <div class="grid grid-cols-1 gap-3 lg:grid-cols-3">
            <div class="fade-in-up widget-table flex flex-col gap-2 bg-widget-background rounded-xl p-6">
                <p class="leading-none font-semibold text-2xl tracking-tight">Market Segments</p>
                <p class="text-muted-foreground text-sm">Project segments can be added or editted here.</p>

                <div class="absolute top-4 right-4 z-10">
                    <button type="button"
                        title="Add new shared user"
                        class="btn-sm-icon-outline shadow-sm text-muted-foreground"
                        id="widget-btn-add-role-override-user"
                        x-on:click="window.roleOverrideModalComponent.open = true"
                        data-tooltip="Override a user role">
                        <i data-lucide="plus"></i>
                    </button>
                </div>

                <div class="line"></div>

                <table width="100%" class="sTable display nowrap" id="admin-market-segments-table" data-init="adminMarketSegment">
                    <thead>
                        <tr>
                            <th>Market Segment</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div class="fade-in-up widget-table flex flex-col gap-2 bg-widget-background rounded-xl p-6">
                <p class="leading-none font-semibold text-2xl tracking-tight">Project & Quote Statuses</p>
                <p class="text-muted-foreground text-sm">Customize the statuses for opportunity, project and quote.</p>
                <div class="absolute top-4 right-4 z-10">
                    <button type="button"
                        title="Add new shared user"
                        class="btn-sm-icon-outline shadow-sm text-muted-foreground"
                        id="widget-btn-add-role-override-user"
                        x-on:click="window.roleOverrideModalComponent.open = true"
                        data-tooltip="Override a user role">
                        <i data-lucide="plus"></i>
                    </button>
                </div>

                <div class="line"></div>

                <table width="100%" class="sTable display nowrap" id="admin-statuses-table" data-init="adminStatuses">
                    <thead>
                        <tr>
                            <th>Status</th>
                            <th>Project</th>
                            <th>Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div class="fade-in-up widget-table flex flex-col gap-2 bg-widget-background rounded-xl p-6">
                <p class="leading-none font-semibold text-2xl tracking-tight">Role Override</p>
                <p class="text-muted-foreground text-sm">Override a user's role. All default role are shown in <strong>All Users</strong> table.</p>

                <div class="absolute top-4 right-4 z-10">
                    <button type="button"
                        title="Add new shared user"
                        class="btn-sm-icon-outline shadow-sm text-muted-foreground"
                        id="widget-btn-add-role-override-user"
                        x-on:click="window.roleOverrideModalComponent.open = true"
                        data-tooltip="Override a user role">
                        <i data-lucide="plus"></i>
                    </button>
                </div>

                <div class="line"></div>

                <table width="100%" class="sTable display nowrap" id="admin-all-role-override-table" data-init="adminRoleOverride">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Role</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div class="fade-in-up">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id="admin-all-users-table" data-init="adminUsers">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Company</th>
                            <th>Location</th>
                            <th>Role</th>
                            <th>P2Q Role</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div id="project-table" class="fade-in-up"></div>

        <div class="fade-in-up" aria-labelledby="all_quotes">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id='admin-quote-table' data-init="adminQuote">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Project Name</th>
                            <th>Segment</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Project Status</th>
                            <th>Approval</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<?= $this->render('modal/role-override'); ?>
