<?php

$this->headTitle('Admin portal');
echo $this->headTitle();

$user = $this->user;

$hour = date('H'); // 24-hour format of the current hour

if ($hour >= 5 && $hour < 12) {
    $greeting = 'Good morning';
} elseif ($hour >= 12 && $hour < 18) {
    $greeting = 'Good afternoon';
} else {
    $greeting = 'Good evening';
}
?>

<!-- Title area -->
<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <h1 class="text-2xl font-semibold tracking-tight">
            <?= $this->escapeHtml($greeting) ?>, <?= $this->escapeHtml($user['first_name']) ?>!
        </h1>
        <p class="text-muted-foreground">Here's all projects and quotes</p>
    </header>

    <div class="flex flex-col gap-4 md:gap-6">
        <div class="fade-in-up" aria-labelledby="all_projects">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id="admin-project-table" data-init="adminProject">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ext. ID</th>
                            <th>Name</th>
                            <th>Owner</th>
                            <th>Shared</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Architect</th>
                            <th>Market Segment</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div class="fade-in-up" aria-labelledby="all_quotes">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id='admin-quote-table' data-init="adminQuote">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Project Name</th>
                            <th>Segment</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Project Status</th>
                            <th>Approval</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
