<?php
$this->headTitle('Approval portal');
echo $this->headTitle();

$user = $this->user;
$waitingTableCount = $this->waitingTableCount;
$approvedTableCount = $this->approvedTableCount;
$disapprovedTableCount = $this->disapprovedTableCount;

$hour = date('H'); // 24-hour format of the current hour

if ($hour >= 5 && $hour < 12) {
    $greeting = 'Good morning';
} elseif ($hour >= 12 && $hour < 18) {
    $greeting = 'Good afternoon';
} else {
    $greeting = 'Good evening';
}

$maintainenceMode = 0;
if ($maintainenceMode != 0 and $user['sale_role'] != 'admin') { ?>
    <div class="main-page-content">
        <header class="main-page-content-header">
            <h1>This page is currently in maintainence mode. Please check back later. Sorry for the inconvenience!</h1>
        </header>
    </div>
<?php } else { ?>

    <!-- Main page -->
    <div class="main-page-content">
        <header class="main-page-content-header">
            <h1><?= $this->escapeHtml($greeting) ?>, <?= $this->escapeHtml($user['first_name']) ?>!</h1>
            <p class="font-light">Here's the quick summary of approval status.</p>
        </header>

        <section class="features fade-in-up approval-page">
            <div class="widget-information approval-dashboard row-1">
                <a href="#waiting-table-section" class="widget-link feature fade-in-up col-1 rounded-2xl px-6 pt-6 pb-4 shadow-md">
                    <p class="widget-text-head mb-4">Waiting for approval
                    </p>
                    <h2 class="widget-text-bold"><?= $this->escapeHtml($waitingTableCount) ?> <span class="widget-text-desc">quotes</span></h2>
                </a>

                <a href="#approved-table-section" class="widget-link feature fade-in-up col-2 rounded-2xl px-6 pt-6 pb-4 shadow-md">
                    <p class="widget-text-head mb-4">Approved
                    </p>
                    <h2 class="widget-text-bold"><?= $this->escapeHtml($approvedTableCount) ?> <span class="widget-text-desc">quotes</span></h2>
                </a>

                <a href="#disapproved-table-section" class="widget-link feature fade-in-up col-3 rounded-2xl px-6 pt-6 pb-4 shadow-md">
                    <p class="widget-text-head mb-4">Rejected
                    </p>
                    <h2 class="widget-text-bold"><?= $this->escapeHtml($disapprovedTableCount) ?> <span class="widget-text-desc">quotes</span></h2>
                </a>
            </div>
        </section>

        <div class="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
            <section class="fade-in-up" id="waiting-table-section">
                <div class="widget-table in-line">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-waiting-table' data-init="approvalWaiting">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Architect</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Date</td>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>

            <section class="fade-in-up" id="approved-table-section">
                <div class="widget-table in-line">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-approved-table' data-init="approvalApproved">
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="select-all" title="Select all approve quotes"></th>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Architect</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Quote Date</th>
                                <th>Expire Date</th>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                                <th>P21 OE #</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>

            <section class="fade-in-up" id="disapproved-table-section">
                <div class="widget-table in-line">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-disapproved-table' data-init="approvalDisapproved">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Architect</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Quote Date</th>
                                <th>Expire Date</th>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>
        </div>
    </div>

<?php }
?>
