<?php
$this->headTitle('Architect portal');
echo $this->headTitle();

$user = $this->user;
$totalArchitects = $this->totalArchitects;
$totalCompleteProjects = $this->totalCompleteProjects;
$totalActiveProjects = $this->totalActiveProjects;

$hour = date('H');

if ($hour >= 5 && $hour < 12) {
    $greeting = 'Good morning';
} elseif ($hour >= 12 && $hour < 18) {
    $greeting = 'Good afternoon';
} else {
    $greeting = 'Good evening';
}
?>

<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <h1 class="text-2xl font-semibold tracking-tight">
            <?= $this->escapeHtml($greeting) ?>, <?= $this->escapeHtml($user['first_name']) ?>!
        </h1>
        <p class="text-muted-foreground">Here's the summary of your architects.</p>
    </header>

    <div class="features fade-in-up architect-page flex flex-col gap-4 text-primary">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
            <div class="feature fade-in-up rounded-xl flex flex-col gap-6 bg-[linear-gradient(142deg,var(--architect-dashboard-bg1)_0%,var(--architect-dashboard-bg2)_50%,var(--architect-dashboard-bg3)_100%)] p-6 shadow-md @container/card">
                <p class="text-muted-foreground text-sm">Total architect
                </p>
                <p class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"><?= $this->escapeHtml($totalArchitects) ?></p>
            </div>

            <div class="feature fade-in-up rounded-xl flex flex-col gap-6 bg-[linear-gradient(230deg,var(--architect-dashboard-bg1)_0%,var(--architect-dashboard-bg2)_50%,var(--architect-dashboard-bg3)_100%)] p-6 shadow-md">
                <p class="text-muted-foreground text-sm">Active projects
                </p>
                <h2 class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"><?= $this->escapeHtml($totalActiveProjects) ?></h2>
            </div>

            <div class="feature fade-in-up rounded-xl flex flex-col gap-6 bg-[linear-gradient(105deg,var(--architect-dashboard-bg1)_0%,var(--architect-dashboard-bg2)_50%,var(--architect-dashboard-bg3)_100%)] p-6 shadow-md">
                <p class="text-muted-foreground text-sm">Pending quotes
                </p>
                <h2 class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">0</h2>
            </div>

            <div class="feature fade-in-up rounded-xl flex flex-col gap-6 bg-[linear-gradient(246deg,var(--architect-dashboard-bg1)_0%,var(--architect-dashboard-bg2)_50%,var(--architect-dashboard-bg3)_100%)] p-6 shadow-md">
                <p class="text-muted-foreground text-sm">Completed projects
                </p>
                <h2 class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"><?= $this->escapeHtml($totalCompleteProjects) ?></h2>
            </div>
        </div>

        <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
            <div class="feature fade-in-up bg-widget-background rounded-xl p-6 shadow-md">
                <p class="leading-none font-semibold text-lg mb-4">
                    Top 5 architects
                </p>
                <table cellpadding="0" cellspacing="0" width="100%" class="sTable wTable display nowrap" id="top-5-architect-table" data-init="architectTop5">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Total Projects</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div class="feature fade-in-up bg-widget-background rounded-xl p-6 shadow-md">
                <p class="leading-none font-semibold text-lg mb-4 ">Architect category
                </p>
                <canvas class="chart" id="architectPieChart" width="80px" height="80px"></canvas>
            </div>

            <div class="feature fade-in-up bg-widget-background rounded-xl p-6 shadow-md">
                <p class="leading-none font-semibold text-lg mb-4">Recent activities
                </p>
                <p class="text-sm">John Doe created a new Project #1024<br>
                    <span style="font:italic">(2 minutes ago)</span>
                </p>
                <div class="line mt-4 mb-4"></div>
                <p class="text-sm">Jane Smith updated Project #1023<br>
                    <span style="font:italic">(5 minutes ago)</span>
                </p>
            </div>
        </div>

        <div class="widget-table bg-widget-background rounded-xl p-6">
            <div class="widget-header">
                <div class="widget-title">
                    <p class="leading-none font-semibold text-lg">Architects</p>
                </div>
                <div class="widget-button">
                    <button type="button" title="Add new architect" class="button action has-icon add-architect-button small" id="widget-btn-add-architect">
                        <span class="button-wrap text-[10px] font-bold">
                            <span class="icon icon-add"></span>
                            Add Architect
                        </span>
                    </button>
                </div>
            </div>

            <div class="line"></div>

            <div class="widget-section">
                <table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap" id="architect-all-table" data-init="architectAll">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Rep ID</th>
                            <th>Type</th>
                            <th>Class</th>
                            <th>Date added</th>
                            <th>No. of projects</th>
                            <th>No. of quotes</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
