<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array $user
 */
$this->headTitle('Home portal');
echo $this->headTitle();

$company = DEFAULT_COMPANY;
?>

<!-- Title area -->
<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <?= $this->partial('components/greeting'); ?>
        <div class="flex items-center justify-between ">
            <p class="text-muted-foreground">Here's the quick summary your projects and quotes.</p>

            <?= $this->partial('components/new-project-btn'); ?>
        </div>
    </header>

    <div class="flex flex-col gap-4 md:gap-6">
        <div id="project-own-projects-table" class="fade-in-up"></div>

        <div class="fade-in-up" aria-labelledby="assigned_projects" id="project-dashboard-assigned-project-section" data-nav="Assigned Projects">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id='dashboard-home-assigned-table' data-init="homeSharedProject">
                    <thead>
                        <tr>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Owner</th>
                            <th>Segment</th>
                            <th>Architect</th>
                            <th>No. of quotes</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <?php if ($user['p2q_system_role'] === 'admin' || $user['p2q_system_role'] === 'manager') { ?>
            <div class="fade-in-up" aria-labelledby="other_projects" id="project-dashboard-other-project-section" data-nav="Other Projects">
                <div class="widget-table bg-widget-background rounded-xl p-6">
                    <table width="100%" class="sTable display nowrap" id='dashboard-home-other-table' data-init="homeOtherProject">
                        <thead>
                            <tr>
                                <th>Project ID</th>
                                <th>Project Name</th>
                                <th>Owner</th>
                                <th>Shared</th>
                                <th>Segment</th>
                                <th>Architect</th>
                                <th>No. of quotes</th>
                                <th>Create date</th>
                                <th>Due date</th>
                                <th>Status</th>
                                <th>Make Quote</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        <?php } ?>

        <div class="fade-in-up" aria-labelledby="my_quotes" id="project-dashboard-quote-section" data-nav="My Quotes">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display nowrap" id='dashboard-home-quote-table' data-init="homeQuote">
                    <thead>
                        <tr>
                            <th>Quote ID</th>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Company Name</th>
                            <th>Project Status</th>
                            <th>Approval Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div class="fade-in-up" aria-labelledby="follow_up_logs" id="project-dashboard-note-section" data-nav="Follow Up Logs">
            <div class="widget-table bg-widget-background rounded-xl p-6">
                <table width="100%" class="sTable display" id='dashboard-home-note-table' data-init="homeNote">
                    <thead>
                        <tr>
                            <th>Log Time</th>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Next Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Right panel -->
<div class="sidebar-container">
    <aside id="sidebar-quicklinks" class="sidebar">
        <nav aria-label="Actions" class="sidebar-inner">
            <div class="sidebar-inner-nav">
                <div class="quick-links">
                    <ol>
                        <li>
                            <a href="/project/" target="_blank" class='quick-link add_pro' title="Add new project">
                                <span class='icon icon-add'></span>
                                Add Project
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </nav>
    </aside>
</div>
