<div class="h-full flex flex-1 flex-col gap-4 p-8">
    <header>
        <?= $this->partial('components/greeting'); ?>

        <div class="flex items-center justify-between ">
            <p class="text-muted-foreground">Welcome to the quoted items dashboard. Here you can search through the item list, or filter by customer name, contact, or project.</p>
        </div>
    </header>

      <div class="flex flex-col gap-4 md:gap-6">
        <div id="quotes-dash-quote-table" class="fade-in-up"></div>
</div>
