 <? $session = Zend_Registry::get('session');?>
  <!-- Title area -->
    <div class="titleArea">
        <div class="wrapper">
            <div class="pageTitle">
                <h5>My Quotes</h5>
                <span>Sales Landing Page.</span>
            </div>
            <div class="middleNav">
                <ul>
                    <li class="mUser"><a href="#" title="Share"><span class="users"></span></a>
                        <ul class="mSub1">
                            <li><a href="#" title="">Share user</a></li>
                            <li><a href="#" title="">Show Teamworks</a></li>
                        </ul>
                    </li>
                   
                    <li class="mOrders"><a href="#" title="Change Status"><span class="files"></span></a>
                        <ul class="mSub4">
                        	<li><a href="#" title="">Add</a></li>
                            <li><a href="#" title="">Save</a></li>
                            <li><a href="#" title="">Edit</a></li>
                            <li><a href="#" title="">Delete</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="line"></div>
    
 
 <!-- Main content wrapper -->
    <div class="wrapper">
    
        <!-- Note -->
       <!-- <div class="nNote nInformation hideit">
            <p><strong>INFORMATION: </strong>Quote Has been saved.</p>
        </div>-->
        
        <!-- Form -->
        <form action="" class="form">
        <div class="widget">
        <div class="title"><img src="/images/icons/dark/full2.png" alt="" class="titleIcon" /><h6>My Quotes</h6></div>  
          <table cellpadding="0" cellspacing="0" width="100%" class="display"  style="text-align:center;" id='quote_table'>
              <thead>
                  <tr>
                  	 <td class="sortCol action"><div>Action<span></span></div></td>
                  	  <td class="sortCol"><div>Quote No<span></span></div></td>
                      <td class="sortCol"><div>Project Name<span></span></div></td>
                      <td class="sortCol"><div>Quote Seg<span></span></div></td>
                      <td class="sortCol"><div>Quote Date<span></span></div></td>
                      <td class="sortCol"><div>Expire Date<span></span></div></td>
                      <td class="sortCol"><div>Status<span></span></div></td>
                  </tr>
              </thead>
              <tbody>
              	<? foreach($this->ownproject as $p) {?>
                  <tr>
                  		<td><!--<a href="#"><img src="images/icons/dark/close.png" alt="delete"></a>--><a target='_blank' href="/quote/edit/id/<?=$p['quote_id']?>"><img src="/images/icons/dark/pencil.png" alt="edit" style="margin:0px 4px"></a></td>
                  	  <td><a target='_blank' href="/quote/edit/id/<?=$p['quote_id']?>"><?=$p['quote_id']?></a></td>
                      <td><?=$p['project_name']?></td>
                      <td><?=$p['quote_segment']?></td>
                      <td><?=$p['quote_date']->format('Y-m-d')?></td>
                      <td><span class='<? if($p['expire_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['expire_date']->format('Y-m-d')?></span></td>
                      <td><?=$p['status_name']?></td>
                  </tr>
                <? } ?> 
              </tbody>
          </table>
        </div>
        <div class="widget">
        <div class="title"><img src="/images/icons/dark/full2.png" alt="" class="titleIcon" /><h6>All Projects</h6></div>  
          <table cellpadding="0" cellspacing="0" width="100%" class="display"  style="text-align:center;" id="project_table">
              <thead>
                  <tr>
                  	 <td class="sortCol"><div>Make Quote<span></span></div></td>
                      <td class="sortCol"><div>Project Name<span></span></div></td>
                      <td class="sortCol"><div>Project Owner<span></span></div></td>
                      <td class="sortCol"><div>Location<span></span></div></td>
                      <td class="sortCol"><div>Project#<span></span></div></td>
                      <td class="sortCol"><div>Market Segment<span></span></div></td>
                      <td class="sortCol"><div>Create Date<span></span></div></td>
                      <td class="sortCol"><div>Due Date<span></span></div></td>
                      <td class="sortCol"><div>Status<span></span></div></td>
                  </tr>
              </thead>
              <tbody>
              	<? foreach($this->projects as $p) {?>
                  <tr>
                  	 <td><a target='_blank' href="/quote/index/project/<?=$p['project_id']?>" alt='quote'><img src="/images/icons/dark/money.png" alt="edit" style="margin:0px 4px"></a></td>
                      <? if($p['owner'] == $session->user['id']) {?>
                      <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/edit/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                      <? } else { ?>
                      <td class='ps_<?=$p['status']?>'><a target='_blank' href="/project/view/id/<?=$p['project_id']?>"><?=$p['project_name']?></a></td>
                      <? } ?>
                      <td><?=$p['owner']?></td>
                      <td><?=$p['company_id']?></td>
                      <td><?=$p['quote_no']?></td>
                      <td><?=$p['market_segment']?></td>
                      <td><?=$p['create_date']->format('Y-m-d')?></td>
                      <td><span class='<? if($p['due_date']->format('Ymd') <= date('Ymd') ) echo 'red'; ?>'><?=$p['due_date']->format('Y-m-d')?></span></td>
                      <td class='stauts_<?=$p['status']?>'><?=$p['status_name']?></td>
                  </tr>
                <? } ?> 
              </tbody>
          </table>
        </div>
       
        </form>
        
        <div class="widget">
          <div class="title"><img src="/images/icons/dark/frames.png" alt="" class="titleIcon"><h6>Project Log</h6></div>
            <table cellpadding="0" cellspacing="0" width="100%" class="display dTable">
                <thead>
                    <tr>
                        <td width="10%" class="sortCol">Date</td>
                        <td width="30%" class="sortCol">Project Name</td>
                        <td width="30%" class="sortCol action">Action</td>
                    </tr>
                </thead>
                <tbody>
                	 <? foreach($this->log as $l) {?>
                    <tr>
                        <td align='center'><?=$l['added']->format('Y-m-d'); ?></td>
                        <td align='center'><?=$l['project_name']; ?></td>
                        <td align='center'><?=$l['action']; ?></td>
                    </tr>
                    <? } ?>
                </tbody>
            </table>
        </div>
            
    </div>
      <div class="statsRow">
        <div class="wrapper">
        	<div class="controlB">
            	<ul>
                	<!--<li><a href="/quote" title=""><img src="/images/icons/control/32/plus.png" alt="" /><span>Add Quote</span></a></li>-->
                   <!-- <li><a href="#" title=""><img src="images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/save.png" alt="" /><span>Save Project</span></a></li>
                    <li><a href="#" title=""><img src="images/icons/control/32/delete.png" alt="" /><span>Delete Project</span></a></li>-->
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
   <script>
	oTable = $('#project_table,#asso_table').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",
		"sDom": '<""l>t<"F"fp>',
		"aaSorting": [[ 6, "desc" ]]
	});
	 $('#quote_table').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",
		"sDom": '<""l>t<"F"fp>',
		"aaSorting": [[ 1, "desc" ]]
	});
	
	
	</script>