<?php

$this->headTitle('Admin portal');
echo $this->headTitle();

$user = $this->user;

$hour = date('H'); // 24-hour format of the current hour

if ($hour >= 5 && $hour < 12) {
    $greeting = "Good morning";
} elseif ($hour >= 12 && $hour < 18) {
    $greeting = "Good afternoon";
} else {
    $greeting = "Good evening";
}
?>

<!-- Title area -->
<div class="main-page-content">
    <header class="main-page-content-header">
        <h1>
            <?= $this->escapeHtml($greeting) ?>, <?= $this->escapeHtml($user['first_name']) ?>!
        </h1>
        <p>Here's all projects and quotes</p>
    </header>

    <section class="fade-in-up" aria-labelledby="all_projects">
        <div class="widget-table">
            <table width="100%" class="sTable display nowrap" id="admin-project-table" data-init="adminProject">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Ext. ID</th>
                        <th>Name</th>
                        <th>Owner</th>
                        <th>Shared</th>
                        <th>Create Date</th>
                        <th>Due Date</th>
                        <th>Architect</th>
                        <th>Market Segment</th>
                        <th>Status</th>
                        <th>Make Quote</th>
                    </tr>
                </thead>
            </table>
        </div>
    </section>

    <section class="fade-in-up" aria-labelledby="all_quotes">
        <div class="widget-table">
            <table width="100%" class="sTable display nowrap" id='admin-quote-table' data-init="adminQuote">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Project Name</th>
                        <th>Segment</th>
                        <th>Quote Date</th>
                        <th>Expire Date</th>
                        <th>Ship Required Date</th>
                        <th>Project Status</th>
                        <th>Approval</th>
                    </tr>
                </thead>
            </table>
        </div>
    </section>
</div>