<?php
$user = $this->user;
$waitingTableCount = $this->waitingTableCount;
$approvedTableCount = $this->approvedTableCount;
$disapprovedTableCount = $this->disapprovedTableCount;

$maintainenceMode = 0;
if ($maintainenceMode != 0 and $user['sale_role'] != 'admin') {
?>
        <div class="main-page-content">
            <header class="main-page-content-header">
                <h1>This page is currently in maintainence mode. Please check back later. Sorry for the inconvenience!</h1>
            </header>
        </div>
<?php } else { ?>

    <!-- Main page -->
        <div class="main-page-content">
            <header class="main-page-content-header">
                <h1>Welcome Back, <span style="font-weight: 300;"><?= $user['name'] ?></span></h1>
                <p>Here's the quick summary of quotes</p>
            </header>

            <section class="active fade-in-up">
                <div class="widget-table">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-waiting-table' data-init="approvalWaiting">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Arch Rep</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Date</td>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>

            <section class="active fade-in-up">
                <div class="widget-table">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-approved-table' data-init="approvalApproved">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Arch Rep</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Quote Date</th>
                                <th>Expire Date</th>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                                <th>P21 OE #</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>

            <section class="active fade-in-up">
                <div class="widget-table">
                    <table width="100%" class="sTable display nowrap" id='dashboard-approve-disapproved-table' data-init="approvalDisapproved">
                        <thead>
                            <tr>
                                <th>Quote ID</th>
                                <th>Project Name</th>
                                <th>Arch Rep</th>
                                <th>Customer</th>
                                <th>Taker</th>
                                <th>Segment</th>
                                <th>Quote Date</th>
                                <th>Expire Date</th>
                                <th>Ship Required Date</th>
                                <th>Status</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>
        </div>

<?php }
?>

<script>
    window.waitingTableCount = <?= $waitingTableCount ?>;
    window.approvedTableCount = <?= $approvedTableCount ?>;
    window.disapprovedTableCount = <?= $disapprovedTableCount ?>;
</script>