<?php
$user = $this->user; ?>
<main id="content" class="main-content">
    <section class="hero fade-in-up">
        <h1 >Welcome to Centura Quotation System</h1>
        <p>Your all-in-one platform for managing projects, approvals, and architectural collaboration with ease and efficiency.</p>
    </section>

    <section class="features welcome-page fade-in-up">
        <?php if ($this->escapeHtml($user['p2q_system_role']) == 'admin'): ?>
            <a href="/index/admin" class="feature fade-in-up">
                <h2>Admin Dashboard</h2>
                <p>Gain full control over user roles, permissions, and platform settings through the Admin Portal.</p>
            </a>
        <?php endif; ?>

        <a href="/index/home" class="feature fade-in-up">
            <h2>Project Dashboard</h2>
            <p>Streamline your project workflows, track progress, and stay organized with our intuitive tools.</p>
        </a>

        <?php if ($this->escapeHtml($user['approve_id']) ?? '' != null): ?>
            <a href="/index/approval" class="feature fade-in-up">
                <h2>Approval Dashboard</h2>
                <p>Easily manage approvals and ensure every step is properly authorized and documented.</p>
            </a>
        <?php endif; ?>

        <a href="/index/architect" class="feature fade-in-up">
            <h2>Architect Dashboard</h2>
            <p>Connect and collaborate with architects seamlessly to ensure design accuracy and quality.</p>
        </a>

        <a href="/project" class="feature fade-in-up">
            <h2>New Project</h2>
            <p>
                Kickstart your next project with our easy-to-use project creation tools and templates.
            </p>
        </a>
    </section>
</main>
