<?php

$this->headTitle('Project portal')->setSeparator(' - ')->setAutoEscape(false);
$user = $this->user;

?>

<!-- Title area -->
<main id="content" class="main-content">
    <div class="main-page-content">
        <header class="main-page-content-header">
            <div class="options-menu">
                <button class="quick-link options-button" id="options-button" type="button">
                    <span class='icon icon-menu'></span>
                    Options
                </button>

                <!-- Right panel -->
                <div class="sidebar-container" id="options-menu-items">
                    <a href="/project/" target="_blank" class='button quick-link add-project' title="Add new project">
                        <span class='icon icon-add'></span>
                        Add Project</a>
                </div>
            </div>

            <h1>Welcome Back, <span style="font-weight: 300;"><?= $user['name'] ?></span></h1>
            <p>Here's the quick summary your projects and quotes.</p>
        </header>

        <section aria-labelledby="my_projects" id="section1" data-nav="My Projects" class="active">
            <div class="widget-table">
                <table width="100%" class="sTable display nowrap" id='project_table'>
                    <thead>
                        <tr>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Shared</th>
                            <th>Segment</th>
                            <th>Specifier</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>

        <section aria-labelledby="assigned_projects" id="section2" data-nav="Assigned Projects">
            <div class="widget-table">
                <table width="100%" class="sTable display nowrap" id='assigned_projects_table'>
                    <thead>
                        <tr>
                            <th>Quote ID</th>
                            <th>Project Name</th>
                            <th>Owner</th>
                            <th>Segment</th>
                            <th>Specifier</th>
                            <th>Create Date</th>
                            <th>Due Date</th>
                            <th>Status</th>
                            <th>Make Quote</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>

        <?php if ($user['approve_id'] != null) { ?>
            <section aria-labelledby="other_projects" id="section3" data-nav="Other Projects">
                <div class="widget-table">
                    <table width="100%" class="sTable display nowrap" id='other_project_table'>
                        <thead>
                            <tr>
                                <th>Project ID</th>
                                <th>Project Name</th>
                                <th>Owner</th>
                                <th>Shared</th>
                                <th>Segment</th>
                                <th>Specifier</th>
                                <th>Create Date</th>
                                <th>Due Date</th>
                                <th>Make Quote</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </section>
        <?php } ?>

        <section aria-labelledby="my_quotes" <?php if ($user['approve_id'] != null) { ?> id="section4" <?php } else { ?> id="section3" <?php } ?> data-nav="My Quotes">
            <div class="widget-table">
                <table width="100%" class="sTable display nowrap" id='quote_table'>
                    <thead>
                        <tr>
                            <th>Quote ID</th>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th>Ship Required Date</th>
                            <th>Company Name</th>
                            <th>Project Status</th>
                            <th>Approval Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>

        <section aria-labelledby="follow_up_logs" <?php if ($user['approve_id'] != null) { ?> id="section5" <?php } else { ?> id="section4" <?php } ?> data-nav="Follow Up Logs">
            <div class="widget-table">
                <table width="100%" class="sTable display" id='project_log'>
                    <thead>
                        <tr>
                            <th>Log Time</th>
                            <th>Project ID</th>
                            <th>Project Name</th>
                            <th>Next Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </section>
</main>

<!-- Right panel -->
<div class="sidebar-container">
    <aside id="sidebar-quicklinks" class="sidebar">
        <nav aria-label="Actions" class="sidebar-inner">
            <div class="sidebar-inner-nav">
                <div class="quick-links">
                    <ol>
                        <li>
                            <a href="/project/" target="_blank" class='quick-link add_pro' title="Add new project">
                                <span class='icon icon-add'></span>
                                Add Project
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </nav>
    </aside>
</div>

<script>
    $(document).ready(function() {
        
        $('#project_table').DataTable({
            //select: true,
            ajax: {
                url: "/index/projectsalesrep",
                dataSrc: ''
            },
            columns: [
                {
                    data: "project_id_ext",
                    render: function(data, type, row, meta) {
                        return "<a target='_blank' href='/project/edit/id/" + row.project_id + "'>" + data + "</a>";
                    }
                },
                {
                    data: "project_name"
                },
                {
                    data: "shared_id"
                },
                {
                    data: "market_segment_desc"
                },
                {
                    data: "specifier_name"
                },
                {
                    data: "create_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        return date.toLocaleDateString();
                    }
                },
                {
                    data: "due_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        let today = new Date();
                        if (date <= today) {
                            return '<span class="red">' + date.toLocaleDateString() + '</span>';
                        } else {
                            return date.toLocaleDateString();
                        }
                    }
                },
                {
                    data: "status_desc"
                },
                {
                    data: "project_id",
                    render: function(data, type, row, meta) {
                        return "<a target='_blank' href='/quote/index/project/" + row.project_id + "'><span class='button-wrap'><span class='icon icon-money'></span></span></a>";
                    }
                },
            ],
            columnDefs: [{
                targets: '_all',
                className: 'dt-head-center'
            }, {
                targets: [0, 2, 3, 5, 6, 7],
                className: 'dt-body-center'
            }],
            processing: true,
            order: {
                name: 'project_id',
                dir: 'desc'
            },
            fixedColumns: {
                start: 1,
                end: 2
            },
            scrollX: true,
            layout: {
                topStart: function() {
                    let info = document.createElement('div');
                    info.innerHTML = '<h2>My Projects</h2><p><?//= count($this->ownproject) ?> projects';
                    return info;
                },
                bottomStart: 'pageLength'
            }
        });

        $('#assigned_projects_table').DataTable({
            //select: true,
            ajax: {
                url: "/index/assignedprojects",
                dataSrc: ''
            },
            columns: [
                {
                    data: "quote_no",
                    render: function(data, type, row, meta) {
                        {
                            return "<a target='_blank' href='/project/edit/id/" + row.project_id + "'>" + data + "</a>";
                        }
                    }
                },
                {
                    data: "project_name"
                },
                {
                    data: "owner"
                },
                {
                    data: "segment"
                },
                {
                    data: "Specifier_name"
                },
                {
                    data: "create_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        return date.toLocaleDateString();
                    }
                },
                {
                    data: "due_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        let today = new Date();
                        if (date <= today) {
                            return '<span class="red">' + date.toLocaleDateString() + '</span>';
                        } else {
                            return date.toLocaleDateString();
                        }
                    }
                },
                {
                    data: "status_name"
                },
                {
                    data: "project_id",
                    render: function(data, type, row, meta) {
                        return "<a target='_blank' href='/quote/index/project/" + row.project_id + "'><span class='button-wrap'><span class='icon icon-money'></span></span></a>";
                    }
                },
            ],
            columnDefs: [{
                targets: '_all',
                className: 'dt-head-center'
            }, {
                targets: [0, 2, 3, 5, 6, 7],
                className: 'dt-body-center'
            }],
            processing: true,
            order: {
                name: 'project_id',
                dir: 'desc'
            },
            fixedColumns: {
                start: 1,
                end: 2
            },
            scrollX: true,
            layout: {
                topStart: function() {
                    let info = document.createElement('div');
                    info.innerHTML = '<h2>Shared Projects</h2><p><?//= count($this->assignedproject) ?> shared projects';
                    return info;
                },
                bottomStart: 'pageLength'
            }
        });

        <?php if ($user['approve_id'] != null) { ?>
            $('#other_project_table').DataTable({
                ajax: {
                    url: "/index/otherprojects",
                    dataSrc: ''
                },
                columns: [
                    {
                        data: "quote_no",
                        render: function(data, type, row, meta) {
                            return "<a target='_blank' href='/project/edit/id/" + row.project_id + "'>" + data + "</a>";
                        }
                    },
                    {
                        data: "project_name"
                    },
                    {
                        data: "owner"
                    },
                    {
                        data: "worksheet_assign"
                    },
                    {
                        data: "segment"
                    },
                    {
                        data: "Specifier_name"
                    },
                    {
                        data: "create_date.date",
                        render: function(data) {
                            let date = new Date(data);
                            return date.toLocaleDateString();
                        }
                    },
                    {
                        data: "due_date.date",
                        render: function(data) {
                            let date = new Date(data);
                            let today = new Date();
                            if (date <= today) {
                                return '<span class="red">' + date.toLocaleDateString() + '</span>';
                            } else {
                                return date.toLocaleDateString();
                            }
                        }
                    },
                    {
                        data: "project_id",
                        render: function(data, type, row, meta) {
                            return "<a target='_blank' href='/quote/index/project/" + row.project_id + "'><span class='button-wrap'><span class='icon icon-money'></span></span></a>";
                        }
                    },
                ],
                columnDefs: [{
                    targets: '_all',
                    className: 'dt-head-center'
                }, {
                    targets: [0, 2, 3, 4, 6, 7],
                    className: 'dt-body-center'
                }],
                processing: true,
                order: {
                    name: 'project_id',
                    dir: 'desc'
                },
                fixedColumns: {
                    start: 1,
                    end: 1
                },
                scrollX: true,
                layout: {
                    topStart: function() {
                        let info = document.createElement('div');
                        info.innerHTML = '<h2>Other Projects At <?= $user['company'] ?></h2><p> <?//= count($this->otherprojects) ?> projects at <?= $user['company'] ?>';
                        return info;
                    },
                    bottomStart: 'pageLength'
                }
            });
        <?php } ?>

        $('#quote_table').DataTable({
            ajax: {
                url: "/index/quotesalesrep",
                dataSrc: ''
            },
            processing: true,
            //"serverSide": true,
            columns: [{
                    data: "quote_id",
                    render: function(data, type, row, meta) {
                        return "<a target='_blank' href='/quote/edit/id/" + data + "'>" + data + "</a>";
                    }
                },
                {
                    data: "project_id",
                    render: function(data, type, row, meta) {
                        return "<a target='_blank' href='/project/edit/id/" + data + "'>" + data + "</a>";
                    }
                },
                {
                    data: "project_name"
                },
                {
                    data: "quote_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        return date.toLocaleDateString();
                    }
                },
                {
                    data: "expire_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        let today = new Date();
                        if (date <= today) {
                            return '<span class="red">' + date.toLocaleDateString() + '</span>';
                        } else {
                            return date.toLocaleDateString();
                        }
                    }
                },
                {
                    data: "ship_required_date.date",
                    render: function(data) {
                        let date = new Date(data);
                        return date.toLocaleDateString();
                    }
                },
                {
                    data: "customer_name"
                },
                {
                    data: "project_status"
                },
                {
                    data: "approve_status",
                    render: function(data) {
                        if (data == -1) {
                            return '<span class="disapproved red">Disapproved</span>';
                        } else if (data == 10) {
                            return '<span class="approved green">Approved</span>';
                        } else if (data == 1) {
                            return '<span class="waiting orange">Waiting</span>';
                        } else {
                            return 'Not submitted';
                        }
                    }
                }
            ],
            columnDefs: [{
                    targets: '_all',
                    className: 'dt-head-center'
                },
                {
                    targets: [0, 1, 3, 4, 5, 7, 8],
                    className: 'dt-body-center'
                }
            ],
            order: [
                [0, "desc"]
            ],
            fixedColumns: {
                start: 2,
                end: 2
            },
            scrollX: true,
            layout: {
                topStart: function() {
                    let info = document.createElement('div');
                    info.innerHTML = '<h2>My Quotes</h2><p> <?//= count($this->ownquotes) ?> quotes';
                    return info;
                },
                bottomStart: 'pageLength'
            }
        });

        $('#project_log').DataTable({
            ajax: {
                url: "/index/memo",
                dataSrc: ''
            },
            processing: true,
            columns: [{
                    data: "date_added.date",
                    render: function(data) {
					let date = new Date(data);
					return '<p><b>' + date.toLocaleString('en-CA') + '</b></p>';
				}
                },
                {
                    data: "project_id",
                    render: function(data, type, row, meta) {
                        {
                            return "<a target='_blank' href='/project/edit/id/" + row.project_id + "'>" + row.project_id + "</a>";
                        }
                    }
                },
                {
                    data: "project_name"
                },
                {
                    data: "next_action",
                    render: function(data) {
                        let formattedText = data.replace(/(?:\r\n|\r|\n)/g, '<br>');
                        return '<p>' + formattedText + '</p>';
                    }
                },
            ],
            columnDefs: [{
                    targets: [0, 1, 2, 3],
                    className: 'dt-head-center'
                },
                {
                    targets: [0, 1],
                    className: 'dt-body-center'
                }
            ],
            fixedColumns: {
                //start: 3
            },
            scrollX: true,
            order: [
                [0, "desc"]
            ],
            layout: {
                topStart: function() {
                    let info = document.createElement('div');
                    info.innerHTML = '<h2>Follow Up Logs</h2><p> <?//= count($this->memo) ?> logs';
                    return info;
                },
                bottomStart: 'pageLength'
            }
        });
    })
</script>