

<a href="/project" target="_blank" class='button quick-link add-project' title="Add new project">
    <span class='icon icon-add'></span>
    Add Project
</a>

<a href="javascript:void(0)" class='button quick-link search-architect-button' title="Search architect">
    <span class='icon icon-search'></span>
    Search architect
</a>

<a href="#" class='button quick-link delete-architect-button' title="Delete architect">
    <span class='icon icon-trash'></span>
    Delete architect
</a>
 