<?php
$owner = $this->owner;
$project = $this->project;
$user = $this->user;
$architect = $this->architect;
$specifier = $this->specifier;
$projectID = $project['project_id'];
$this->headTitle('Edit Project: ' . $projectID)->setSeparator(' - ')->setAutoEscape(false);
$projectCreateDate = $project['create_date'];
$projectDueDate = $project['due_date'];
$projectRequiredDate = $project['require_date'];
?>

<!-- Right panel -->


<!-- Main content wrapper -->
<main id="content" class="main-content">
	<div class="main-page-content">

		<header class="main-page-content-header">
			<div class="options-menu">
				<button class="quick-link options-button" id="options-button" type="button">
					<span class='icon icon-menu'></span>
					Options
				</button>

				<div class="sidebar-container" id="options-menu-items">
					<a href="/project" target="_blank" class='button quick-link add_pro' title="Add new project">
						<span class='icon icon-add'></span>
						Add Project</a>
					<!--<li><a href="#" class='edit_pro' title="edit"><img src="/images/icons/control/32/doc_edit.png" alt="" /><span>Edit Project</span></a></li>-->
					<!--<li><a href="#" class='update_pro' title="update"><img src="/images/icons/control/32/refresh.png" alt="" /><span>Update Project</span></a></li>-->
					<a class='button quick-link' href="<?= 'http://' . SITEURL . "/dompdf/print.php?url=" . 'http://' . SITEURL . "/project/print/id/" . $project['project_id'] . "?company=" . substr($project['project_id_ext'], 0, 3) . "&name=Centura_Project_" . preg_replace("![^a-z0-9]+!i", "_", $project['project_name']) . '.pdf' ?>" title="print">
						<span class='icon icon-pdf'></span>
						Print Project</a>
					<a class='button quick-link make-quote' href="/quote/index/project/<?= $project['project_id'] ?>" title="Make quote">
						<span class='icon icon-dollar'></span>
						Make Quote
					</a>
					<a href="#" class='button quick-link delete_pro' title="delete">
						<span class='icon icon-trash'></span>
						Close Project</a>
				</div>
			</div>

			<h1>Edit Project</h1>
		</header>

		<!-- Form -->
		<section aria-labelledby="project-information" id="section1" data-nav="Project Information" class="active">
			<form action="/project/edit/id/<?= $projectID ?>" method="post" class="form" id='project_content'>
				<div class="widget-table">
					<!--<div class="widget-button">
						<div class="widget-pin">
							<input type="checkbox" id="project-pin" name="project-pin">
							<label for="project-pin">Pin project</label>
						</div>
					</div>-->
					<div class="widget-header">
						<div class="widget-title">
							<h2>Project Information</h2>
						</div>
					</div>
					<div class="line"></div>
					<div class="widget-section">
						<div class="formRow">
							<input type="hidden" id='project_id' value='<?= $projectID ?>'>
							<input type="hidden" id="user_session_id" name='user_session_id' value='<?= $user['id'] ?>'>
							<input type="hidden" id='create_date' name='create_date' value='<?= $projectCreateDate?->format('Y-m-d') ?? '' ?>' />

							<div class="oneTwo required-field">
								<label for="project_name">Project Name</label>
								<input type="text" id='project_name' class="validate[required]" placeholder="Project Name" name='project_name' value="<?= $project['project_name'] ?>" />
							</div>

							<div class="oneTwo required-field">
								<label for="project_address">Project Location</label>
								<input type="text" name='project_address' id="project_address" class="validate[required]" value='<?= $project['centura_location_id'] ?>' />
							</div>

							<div class="oneTwo">
								<label for="location_id">Centura Location</label>
								<select name="location_id" id="location_id">
									<?php foreach ($this->location as $l) { ?>
										<option value="<?= $l['location_id'] ?>" <?php if ($l['location_id'] == $project['centura_location_id']) echo 'selected' ?>><?= $l['branch_description'] ?></option>
									<?php } ?>
								</select>
							</div>

							<div class="oneTwo required-field">
								<label for="status">Project Stage</label>
								<select name="status" id="status" class="validate[required]">
									<option value="">-- Select Status --</option>
									<?php foreach ($this->status as $s) { ?>
										<option value="<?= $s['status_id'] ?>" <?php if ($s['status_id'] == $project['status']) echo 'selected' ?>><?= $s['status_desc'] ?></option>
									<?php } ?>
								</select>
							</div>

							<div class="oneTwo required-field">
								<label for='market_segment_id'>Project Segment</label>
								<select name="market_segment_id" id='market_segment_id' class="validate[required]">
									<option value="">-- Choose Segment --</option>
									<?php foreach ($this->seg as $s) { ?>
										<option value="<?= $s['market_segment_id'] ?>" <?php if ($s['market_segment_id'] == $project['market_segment_id']) echo 'selected' ?>><?= $s['market_segment_desc'] ?></option>
									<?php } ?>
								</select>
							</div>

							<div class="oneTwo form-worksheet-owner">
								<label for="owner_id">Worksheet Owner</label>
								<input id="owner_id" name="owner_id" type="text" value='<?= $project['owner_id'] ?>' readonly />
							</div>

							<div class="oneTwo required-field">
								<label for="reed">REED ID</label>
								<input type="text" name="reed" id="reed" value="<?= $project['reed'] ?>" class="validate[required]" />
							</div>

							<div class="oneTwo">
								<label for="due_date">Tender Due Date</label>
								<input id="due_date" type="text" name='due_date' class="datepicker" value='<?= $projectDueDate?->format('Y-m-d') ?? '' ?>' />
							</div>

							<div class="oneTwo">
								<label for='required_date'>Required Date</label>
								<input id='required_date' type="text" name='required_date' class="datepicker" value='<?= $projectRequiredDate?->format('Y-m-d') ?>' />
							</div>

							<?php if ($user['approve_id'] != null) { ?>
								<div class="oneTwo form-worksheet-owner">
									<label for="shared_id">Share Worksheet</label>
									<input id="shared_id" name="shared_id" type="text" value='<?= $project['shared_id'] ?>' />
								</div>
							<?php } else { ?>
								<input type="hidden" id="shared_id" name="shared_id" value='<?= $project['shared_id'] ?>' />
							<?php } ?>

							<div class="oneTwo">
								<label for="project_id_ext">Project ID</label>
								<input id="project_id_ext" type="text" name='project_id_ext' value="<?= $project['project_id_ext'] ?>" readonly />
							</div>
						</div>
					</div>

					<div class="line"></div>

					<details>
						<summary>Architect & Specifier</summary>
						<div class="widget-section">
							<div class="widget-header">
								<div class="widget-title">
									<h4>Architect</h4>
								</div>
								<div class="widget-button">
									<button type="button" title="Add new architect" class="button action has-icon add-item-button small" id="add_architect">
										<span class="button-wrap">
											<span class="icon icon-add"></span>
											New Architect
										</span>
									</button>
								</div>
							</div>
							<p>*If you want to edit the architect, please edit it in Architect Portal.</p>
							<div class="formRow">
								<div class="oneTwo">
									<label for="architect_name">Architect Name</label>
									<input readonly type='text' name="architect_name" id='architect_name' class="tipN" original-title="Search by ID or Name" value='<?= $architect['architect_name'] ?? '' ?>' />
									<input type="hidden" name='architect_id' id='architect_id' value='<?= $architect['architect_id'] ?? '' ?>' />
								</div>

								<div class="oneTwo">
									<label for="architect_company_id">Company</label>
									<select id="architect_company_id" name="architect_company_id">
										<?php foreach ($this->company as $l) { ?>
											<option value="<?= $l['company_id'] ?>" <?php if ($l['company_id'] === ($architect['company_id'] ?? '')) echo 'selected' ?>><?= $l['company_name'] ?></option>
										<?php } ?>
									</select>
								</div>

								<div class="oneTwo">
									<label for="architect_rep_id">Architect Representative</label>
									<input readonly type="text" id="architect_rep_id" name="architect_rep_id" value='<?= $architect['architect_rep_id'] ?? '' ?>' readonly />
								</div>

								<input type="hidden" name='address_id' id='address_id' />
								<div class="oneTwo">
									<label for="phys_address1">Address 1</label>
									<input readonly type='text' name="phys_address1" id='phys_address1' value='<?= $architect['phys_address1'] ?? '' ?>' />
								</div>

								<div class="oneTwo">
									<label for="phys_address2">Address 2</label>
									<input readonly type='text' name="phys_address2" id='phys_address2' value='<?= $architect['phys_address2'] ?? '' ?>' placeholder="Optional" />
								</div>

								<div class="oneTwo">
									<label for="phys_city">City 2</label>
									<input readonly type='text' name="phys_city" id='phys_city' value='<?= $architect['phys_city'] ?? '' ?>' placeholder="Optional" />
								</div>

								<div class="oneTwo">
									<label for="phys_state">Province</label>
									<input readonly type='text' name="phys_state" id='phys_state' value='<?= $architect['phys_state'] ?? '' ?>' placeholder="Optional" />
								</div>

								<div class="oneTwo">
									<label for="phys_postal_code">Postal Code</label>
									<input readonly type='text' name="phys_postal_code" id='phys_postal_code' value='<?= $architect['phys_postal_code'] ?? '' ?>' placeholder="Optional" />
								</div>

								<div class="oneTwo">
									<label for="phys_country">Country</label>
									<input readonly type='text' name="phys_country" id='phys_country' value='<?= $architect['phys_country'] ?? '' ?>' placeholder="Optional" />
								</div>

								<div class="oneTwo">
									<label for="central_phone_number">Company Phone Number</label>
									<input readonly id='central_phone_number' name='central_phone_number' type="tel" class="maskPhone" value='<?= $architect['central_phone_number'] ?? '' ?>' placeholder="(123) 456-7890" />
								</div>

								<div class="oneTwo">
									<label for="email_address">Email</label>
									<input readonly type="text" value="" id='email_address' name='email_address' value='<?= $architect['email_address'] ?? '' ?>' placeholder="Optional">
								</div>

								<div class="oneTwo">
									<label for="url">URL</label>
									<input readonly type="url" value="" id='url' name='url' value='<?= $architect['url'] ?? '' ?>' placeholder="Optional">
								</div>
							</div>
						</div>

						<div class="line"></div>

						<div class="widget-section">
							<h4>Specifier</h4>
							<p>*If you want to edit the specifier, please edit it in Architect Portal.</p>
							<div class="formRow">
								<input type="hidden" id='specifier_id' name="specifier_id" value='<?= $project['specifier_id'] ?>' />
								<input type="hidden" id='specifier_address_id' name="specifier_address_id" value='<?= $specifier['address_id'] ?>' />
								<div class="oneTwo ">
									<label for="specifier_name">Specifier</label>
									<select name='specifier_name' id='specifier_name'>
										<?php
										if (!empty($specifierList)):
											foreach ($specifierList as $spec): ?>
												<option value="<?= $spec['specifier_id'] ?>" <?php if ($spec['specifier_id'] === $project['specifier_id']) echo 'selected' ?>><?= $spec['first_name'] . ' ' . $spec['last_name'] ?></option>
										<?php endforeach;
										endif;
										?>
										<option value="new">+ Add New Specifier</option>
									</select>
								</div>

								<div class="oneTwo ">
									<label for="specifier_first_name">First Name</label>
									<input readonly type='text' id='specifier_first_name' name="specifier_first_name" class="tipN" value='<?= $specifier['first_name'] ?>' />
								</div>

								<div class="oneTwo ">
									<label for="specifier_last_name">Last Name</label>
									<input readonly type='text' id='specifier_last_name' name="specifier_last_name" placeholder="Optional" value='<?= $specifier['last_name'] ?>' />
								</div>

								<div class="oneTwo ">
									<label for="specifier_job_title">Job Title</label>
									<input readonly type='text' id='specifier_job_title' name="specifier_job_title" class="tipN" placeholder="Optional" value='<?= $specifier['job_title'] ?>' />
								</div>

								<div class="oneTwo ">
									<label for="specifier_phone_number">Phone Number</label>
									<input readonly type='tel' id='specifier_phone_number' name="specifier_phone_number" class="maskPhone" placeholder="(123) 456-7890" value='<?= $specifier['central_phone_number'] ?>' />
								</div>

								<div class="oneTwo ">
									<label for="specifier_email">Email</label>
									<input readonly type='text' id='specifier_email' name="specifier_email" class="tipN" placeholder="Optional" value='<?= $specifier['email_address'] ?>' />
								</div>
							</div>
						</div>
					</details>

					<div class="line"></div>

					<details>
						<summary>Contractor</summary>
						<div class="widget-section">
							<div class="formRow">
								<div class="oneTwo">
									<label for="general_contractor_name">General Contractor</label>
									<input type="text" id="general_contractor_name" name="general_contractor_name" placeholder="Add general contractor" value='<?php if (!empty($this->gerneral_contractor)) {
																																									echo $this->gerneral_contractor['customer_name'] . ' - ' . $this->gerneral_contractor['company_id'];
																																								} ?>' />
									<input type="hidden" id="general_contractor_id" name="general_contractor_id" value="<?= $project['general_contractor_id'] ?>" />
								</div>

								<div class="oneTwo">
									<label for="awarded_contractor_name">Awarded Sub Contractor</label>
									<input type="text" id="awarded_contractor_name" name="awarded_contractor_name" placeholder="Add awarded contractor" value='<?php if (!empty($this->awarded_sub_contracotr)) {
																																									echo $this->awarded_sub_contracotr['customer_name'] . ' - ' . $this->awarded_sub_contracotr['company_id'];
																																								} ?>' />
									<input type="hidden" id='awarded_contractor_id' name='awarded_contractor_id' value="<?= $project['awarded_contractor_id'] ?>">
								</div>
							</div>
						</div>
					</details>

					<?php if ($owner) { ?>

						<div class="line"></div>

						<div class="widget-footer">
							<div class="widget-footer-button">
								<button disabled id="save-project" type="button" title="Save project information" class="button action save-project-button small">
									<span class="button-wrap">
										<span class="icon icon-save"></span>
										Save
									</span>
								</button>
							</div>
						</div>
					<?php } ?>
				</div>
			</form>
		</section>

		<section aria-labelledby="quoted-items" id="section2" data-nav="Quoted Items">
			<div class="widget-table">
				<div class="widget-header">
					<div class="widget-title">
						<h2>Quoted Items</h2>
					</div>
					<div class="widget-button">
						<?php if ($owner) { ?>
							<button type="button" title="Add new item" class="button action has-icon add-item-button small" id="add_item">
								<span class="button-wrap">
									<span class="icon icon-add"></span>
									Add Item
								</span>
							</button>
							<!--<button type="submit" title="Save new items" class="button action has-icon small" id="save_item" disabled>
								<span class="button-wrap">
									<span class="icon icon-save"></span>
									Save
								</span>
							</button>
							<button type="submit" title="Delete items" class="button action has-icon small" id="delete-multiple-item" disabled>
								<span class="button-wrap">
									<span class="icon icon-trash"></span>
									Delete item
								</span>
							</button>-->
						<?php } ?>
					</div>
				</div>

				<div class="line"></div>

				<div class="widget-section">
					<table cellpadding="0" cellspacing="0" width="100%" class="sTable display nowrap" id="items">
						<thead>
							<tr>
								<th>Item</th>
								<th>Quality</th>
								<th>Unit Price</th>
								<th>UOM</th>
								<th>Total Price</th>
								<th>Note</th>
								<th>Options</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</section>

		<section aria-labelledby="quote-by-project" id="section3" data-nav="Quote by this project">
			<div class="widget-table">
				<div class="widget-header">
					<div class="widget-title">
						<h2>Project Quotes</h2>
					</div>
					<div class="widget-button">
						<?php if ($owner) { ?>
							<button onclick="location.href='/quote/index/project/<?= $projectID ?>'" type="button" title="Add new quote" class="button action has-icon add-quote-button small" id="add-quote">
								<span class="button-wrap">
									<span class="icon icon-add"></span>
									Make Quote
								</span>
							</button>
						<?php } ?>
					</div>
				</div>

				<div class="line"></div>

				<div class="widget-section">
					<table width="100%" class="sTable display" id='project-quote-table'>
						<thead>
							<tr>
								<th>Quote ID</th>
								<th>Architectural Rep.</th>
								<th>Quote Date</th>
								<th>Expire Date</th>
								<th>Ship Required Date</th>
								<th>Approve Status</th>
								<th>P21 Order ID</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</section>

		<section aria-labelledby="project-log" id="section4" data-nav="Project Log">
			<div class="widget-table">
				<div class="widget-header">
					<div class="widget-title">
						<h2>Project Log</h2>
					</div>
					<div class="widget-button">
						<?php if ($owner) { ?>
							<button type="button" title="Add new log" class="button action has-icon add-log-button small" id="opener">
								<span class="button-wrap">
									<span class="icon icon-add"></span>
									Add log
								</span>
							</button>
						<?php } ?>
					</div>
				</div>

				<div class="line"></div>

				<div class="widget-section">
					<table cellpadding="0" cellspacing="0" width="100%" class="sTable display" id='project_note'>
						<thead>
							<tr>
								<th>Log Time</th>
								<th>Log</th>
								<th>Next Action</th>
								<th>Follow Up Date</th>
								<th>Author</th>
								<th class="action">Options</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</section>

		<div id="dialog-item" title="Add Item">
			<form action="" class="dialog" id='item'>
				<div class="dialog-form">
					<div class="oneTwo required-field">
						<label for="item_id">Item ID</label>
						<input type="hidden" name="item_desc" id='item_input' />
						<input type="text" id="item_id" name='item_id' class="validate[required]" placeholder="Search by ID or name" />
					</div>

					<div class="oneTwo required-field">
						<label for='uom'>Unit Of Measure</label>
						<select name="uom" id='uom' class="validate[required]">
							<option value=''>-- Search for item first --</option>
						</select>
					</div>

					<div class="oneTwo required-field">
						<label for='price'>Price ($)</label>
						<input type="text" class="validate[required,custom[number]]" name="price" id='price' placeholder="*You can override the price" />
					</div>

					<div class="oneTwo required-field">
						<label for='qty'>Quantity</label>
						<input type="text" name="qty" id='qty' class="validate[required,custom[number]]" />
					</div>

					<div class="oneTwo dialog-note">
						<label for='note'>Note</label>
						<textarea rows="8" name='note' id='note' maxlength="255" class="validate[maxSize[255]]"></textarea>
						<input type="hidden" id="is_edit" value='0' />
					</div>
				</div>
			</form>
		</div>

		<div id="dialog-message" title="Add Log">
			<form action="" class="dialog" id='note'>
				<div class="dialog-form">
					<div class="oneTwo dialog-note">
						<label for="note_title">Title</label>
						<textarea rows="2" name='note_title' id='note_title' placeholder="Title"></textarea>
					</div>

					<div class="oneTwo required-field dialog-note">
						<label for="project_note">Content</label>
						<textarea rows="8" name='project_note' id='project_note' class="validate[required]" placeholder="Log content"></textarea>
					</div>

					<div class="oneTwo dialog-note">
						<label for="next_action">Next Action</label>
						<textarea rows="3" name="next_action" id='next_action' placeholder="Can be left empty"></textarea>
					</div>

					<div class="oneTwo dialog-note">
						<label for='follow_up_date'>Follow Up Date</label>
						<input type="text" name='follow_up_date' id='follow_up_date' class="datepicker" value='<?= date('Y-m-d') ?>' />
					</div>
				</div>
			</form>
		</div>
	</div>
</main>


<script type="text/javascript">
	let isOwner = <?= $this->owner ? 'true' : 'false' ?>;
</script>